.github/workflows/stale.yaml
Using labels `lifecycle/stale` and `lifecycle/frozen` per KF repos conventions.
Runs daily at 04:04.
Thanks for the suggestion @rimolive 
/assign @rimolive @rareddy
=> add Stale GH action

.github/workflows/build-image-pr.yml
Remove the operator check during the PR build check as not needed in kubeflow
=> kubeflow: remove operator test in pr check

.gitignore, api/openapi/model-registry.yaml, internal/converter/generated/mlmd_openapi_converter.gen.go, internal/converter/generated/openapi_converter.gen.go, internal/server/openapi/type_asserts.go, patches/type_asserts.patch, pkg/openapi/model_base_artifact.go, pkg/openapi/model_doc_artifact.go, pkg/openapi/model_model_artifact.go
This fixes an improper polymorphic type definition by moving its discriminator to the composing types.
There's also a small fix for ignoring `coverage.html`, that is generated when running `make test-cover`.
This problem was spotted while using the Kiota generator, and can be traced back to [the following pattern](https://github.com/microsoft/kiota/issues/2304),
which is incompatible with JSONSchema.
Following the same steps laid out on the last PR referencing OAS #17:
```
make FORCE_SERVER_GENERATION=true clean build
make test
```
then,
1. start an MLMD server
2. run `make proxy`
3. run `robot test/robot/ && TEST_MODE=python robot test/robot/MRandLogicalModel.robot`
=> OAS: Fix discriminator field definition for Artifact

test/robot/MRkeywords.resource
There is environment variable called `TEST_MR_HOST` for Robot Framework tests setting Model Registry host that can be used for testing Model Registry instance deployed anywhere, but there is not any environment variable for setting port of the instance for testing it.
This PR provides new environment variable called `TEST_MR_PORT` for setting test port of Robot Framework tests.
1. Deploy Model Registry instance anywhere with publicly reachable host and port.
2. Run Robot Framework tests against it with setting TEST_MR_HOST and TEST_MR_PORT environment variable:
```TEST_MR_HOST=<model-registry-hostname> TEST_MR_PORT=<model-registry-port> robot test/robot/UserStory.robot```
=> New(robot): Environment variable TEST_PORT for setting test port

.github/workflows/build-and-push-image.yml
The goal of this PR is to fix 2 issues in the current GHA invocation:
- `VERSION` needed to be pass down to push the tagged layer (the layers and rolling tags are already pushed from the steps above, what needs to happen is GHA need to instruct the script to just-push the newly created tag)
With this change:
- ensure `latest` and `main` tag are synced to the most recent image produced (except of release versions)
- we can always introduce a `latest-release` tag following similar GHA snippet later
=> fix GHA invocation of docker tag push script

manifests/kustomize/options/istio/kustomization.yaml, manifests/kustomize/options/istio/virtual-service.yaml
for consistency, do not tie down to a given namespace
`kubectl apply -n kubeflow -k manifests/kustomize/options/istio`
=> fix: ensure consistency ns(omitted) for istio manifests

go.mod, go.sum
see also: https://security.snyk.io/vuln/SNYK-GOLANG-GITHUBCOMCONTAINERDCONTAINERD-6219724
`make test`
- [n/a] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
=> fix CVE-2024-21626

.github/workflows/build-image-pr.yml
resolves #35 
Use Kind GHA script to dry-run the Model Registry image built on a pull_request, use [similarly to previously existing strategy](https://github.com/kubeflow/model-registry/pull/16), now adapted from using Operator pattern to use Manifest and Kind.
demo [here](https://github.com/kubeflow/model-registry/actions/runs/8232920576/job/22511345478?pr=36)
=> add testing of KF MR Manifests

clients/python/README.md, clients/python/src/model_registry/_client.py, clients/python/src/model_registry/_utils.py, clients/python/src/model_registry/exceptions.py, clients/python/src/model_registry/utils.py, clients/python/tests/test_client.py, clients/python/tests/test_utils.py
Provides an S3 URI builder util function with overloads that it can guarantee there's no metadata (e.g. from the environment) missing upon creating MR objects, either for UI or deployment purposes.
The usage of the helper is, although, optional. Proposed usage is presented on an example on the README file.
This work is based of off: https://issues.redhat.com/browse/RHOAIENG-3979
Inside the client folder, run
```py
poetry run pytest -vv --cov
```
=> Construct proper S3 URIs on `register_model`

internal/apiutils/api_utils.go, internal/server/openapi/api_model_registry_service_service.go, pkg/core/core.go, test/robot/MRkeywords.resource, test/robot/UserStory.robot
...handle gin-generated code by openapi-codegen internally, so to make properly string ptr semantic as expected by core lib, as a query param might not even be passed during requests
many thanks to @devguyio for reporting.
```
gmake test
robot test/robot/UserStory.robot
```
both passing.
Also, manually tested with:
```
curl -X 'GET' \
'http://localhost:8080/api/model_registry/v1alpha3/model_artifact?name=v8-model&parentResourceId=17' \
-H 'accept: application/json'
{"artifactType":"model-artifact","createTimeSinceEpoch":"1711018490528","customProperties":{},"description":"Model artifact for MNIST v8","id":"9","lastUpdateTimeSinceEpoch":"1711018490528","modelFormatName":"onnx","modelFormatVersion":"1","name":"v8-model","state":"UNKNOWN","storageKey":"aws-connection-models","storagePath":"mn …
```
=> fix: query param might be empty string value

.github/workflows/build-image-pr.yml
- based on, and pending on #43 (this PR in draft as will be rebased after #43 gets merged)
- resolves #44 
uses Kind as part of GHA workflow
- [n/a] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [n/a] The developer has manually tested the changes and verified that the changes work
=> add specific K8s version when testing with Kind

Makefile
wrong indentation of Makefile rule recipe as invoked by CI/GHA
Invoking `make docker/login` locally
=> fix wrong indentation in makefile rule recipe

test/robot/UserStory.robot
In this demo,
- RegisteredModel gets labels: my-label1, my-label2
- ModelVersion gets labels: my-label3, my-label4
- ModelArtifact gets labels: my-label5, my-label6
Custom property of type string, with empty string value, shall be considered a Label; this is also semantically compatible for properties having empty string values in general.
```
robot test/robot/UserStory.robot
```
Behind the scenes, request payload is exercised as:
```
POST Request : url=http://localhost:8080/api/model_registry/v1alpha3/registered_models 
path_url=/api/model_registry/v1alpha3/registered_models 
headers={'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '235', 'Content-Type': 'application/json'} 
body=b'{"name": …
```
=> demo storing label as custom property with empty string value

.dockerignore, .gitignore, Dockerfile, Makefile, docker-compose-local.yaml, docker-compose.yaml, scripts/install_protoc.sh
Improvements to make the build self-contained.
Various minor improvements to make sure that we are using the same versions of the tools and more.
Building locally on Mac and building the container image with `podman`
=> More controlled environment in the build

clients/python/src/model_registry/core.py, clients/python/src/model_registry/store/wrapper.py, clients/python/tests/store/test_wrapper.py
Addresses https://github.com/opendatahub-io/model-registry-bf4-kf/issues/169.
=> Py: Fix misleading errors on missing list results

api/openapi/model-registry.yaml, internal/converter/generated/mlmd_openapi_converter.gen.go, internal/converter/generated/openapi_converter.gen.go, internal/converter/mlmd_converter_util_test.go, internal/converter/mlmd_openapi_converter.go, internal/converter/mlmd_openapi_converter_util.go, internal/converter/openapi_converter.go, internal/server/openapi/type_asserts.go, pkg/core/core_test.go, pkg/openapi/model_model_version.go, pkg/openapi/model_model_version_create.go, test/robot/UserStory.robot
need to adapt property definition in OpenAPI
to accomodate openapi-codegen result;
according to contract (as also visible in swagger)
the `ModelVersion` is to contain property: `registeredModelId`
- change OpenAPI definition to a variant which accomodates the intended openapi-codegen result we need
- implement goverter functions
- new unit test functions
- extend integration test 
- extend E2E test (robotframework)
- make test
- robot test/robot/UserStory.robot
- [n/a] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
=> fix: OpenAPI ModelVersion shall contain registeredModelId property

clients/python/pyproject.toml
roll up next pyproject.toml version to 0.2.1a1
follow up of: https://github.com/kubeflow/model-registry/pull/71
=> alpha release: py: bump pyproject.toml to next

api/openapi/model-registry.yaml, clients/python/src/model_registry/types/contexts.py, clients/python/tests/conftest.py, clients/python/tests/types/test_context_mapping.py, docs/logical_model.md, internal/converter/generated/mlmd_openapi_converter.gen.go, internal/converter/generated/openapi_converter.gen.go, internal/converter/mlmd_converter_util_test.go, internal/converter/mlmd_openapi_converter.go, internal/converter/mlmd_openapi_converter_util.go, internal/converter/openapi_converter.go, internal/converter/openapi_mlmd_converter_util.go, internal/mlmdtypes/mlmdtypes.go, internal/testutils/test_container_utils.go, pkg/core/core_test.go, pkg/openapi/model_registered_model.go, pkg/openapi/model_registered_model_create.go, pkg/openapi/model_registered_model_update.go, test/robot/UserStory.robot
In the logical model for `RegisteredModel`, add property `owner` of type string.
> [!NOTE]  
> Sanity checks to work better with local testing while using Podman (5.0.1) has been implemented as part of this PR.
- add to OpenAPI logical model
- regenerate server, Go struct
- implement goverter mappings
- implement unit and integration test on Go side
- align structure in Python client
- implement test in Python client
- implement e2e testing with RobotFramework
- update documentation of logical model
- make test for Go
- poetry run pytest for Python
- run RobotFramework manually raising MLMD in docker and running model-registry proxy
=> add `owner` to `RegisteredModel` logical model

manifests/kustomize/OWNERS, manifests/kustomize/README.md
As discussed in the last Kubeflow Manifest WG meeting (2024-04-18), this PR aims to properly setup manifests folder to follow the [Kubeflow manifests guidelines](https://github.com/kubeflow/manifests/blob/master/proposals/20220926-contrib-component-guidelines.md#component-requirements)
Given that, with https://github.com/kubeflow/manifests/pull/2682 we are going to add a custom script to sync Kubeflow Model Registry manifests from this repository to the Kubeflow Manifests one. In this PR I am adding missing files to follow the aforementioned Kubeflow manifests guidelines.
These are the requirements for all components under `/contrib`:
* Instructions on how someone can install the component in a Kubeflow cluster
* Since Kubeflow manifests have standardized on …
=> Follow KF manifests guidelines

internal/server/openapi/api_model_registry_service_service.go, pkg/api/error.go, pkg/core/core.go, pkg/core/core_test.go
Closes: https://github.com/opendatahub-io/model-registry-bf4-kf/issues/305
This handles REST status codes coming from the server core layer using enums and error unwrapping as [introduced in GO 1.13](https://go.dev/blog/go1.13-errors).
Tested with httpie and go tests.
=> Handle REST status codes

.github/dependabot.yml
`directory` should point to manifest location [1], which is the `pyproject.toml` file in our case [2].
[1]: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#directory
[2]: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#pip-and-pip-compile
=> fix dependabot spec for python client

Dockerfile, Dockerfile.odh
to ensure better Container image Grades, bump to `ubi8/ubi-minimal:latest` for the base runtime image.
locally tested with:
- `docker build -t quay.io/opendatahub/model-registry:latest -f Dockerfile . --load`
- `docker compose -f docker-compose.yml up`
- (in another shell) `robot test/robot/UserStory.robot`
as I'm on ARM cpu I've had locally other changes to Dockerfile related to this, so using GHA in this PR to check for amd64 build itself.
=> chore: use ubi8/ubi-minimal:latest for security updates

internal/apiutils/api_utils.go, internal/server/openapi/api_model_registry_service_service.go, pkg/api/error.go
This fixes an unhandled error on the GetEnvironmentEnvironments route, as well as standardizes error value treatment using an error to http status converter. All status codes now use the standard net/http consts (enum).
Tested with `make test`.
=> Handle errors gracefully on routes

manifests/kustomize/base/model-registry-deployment.yaml, manifests/kustomize/base/model-registry-service.yaml, manifests/kustomize/options/istio/virtual-service.yaml, manifests/kustomize/overlays/db/kustomization.yaml, manifests/kustomize/overlays/db/patches/model-registry-deployment.yaml, manifests/kustomize/overlays/postgres/kustomization.yaml, manifests/kustomize/overlays/postgres/patches/model-registry-deployment.yaml
Seems to me the definition proposed in this changed manifest makes it working, and it's aligned with other Kubeflow components' approach.
Before, I was not able to reach by e2e test (from outside the cluster) the Model Registry REST API endpoint --unless of manual p.fwd.
This solution aligns for the REST API endpoint (the one on 8080) following similar strategy of other Kubeflow components: see [here for some examples](https://github.com/search?q=repo%3Akubeflow%2Fmanifests+%22kind%3A+VirtualService%22+language%3AYAML&type=code&l=YAML).
This way, request on the gateway for `/model-registry/...` will be routed to the correct service accordingly.
Install vanilla KF, used `1.9.0-rc.0` without networkpolicies.
(I'm skipping networkpolicies as _this PR_ I considered propaedeutic work to later …
=> fix istio VirtualService manifest

clients/python/README.md, clients/python/pyproject.toml
Until we will rebase the MR py client on top of MR REST API,
I'm suggesting to expand on documentation as proposed in this PR.
This also follow-up to: https://github.com/kubeflow/model-registry/issues/90#issuecomment-2141063884
Expand on use-case of the [Remote-only packaging of MLMD Python lib](https://github.com/kubeflow/model-registry/blob/main/docs/remote_only_packaging_of_MLMD_Python_lib.md) document, in relation to the MR python client.
- A notebook project NOT depending on MLMD either directly or indirectly,
- using Python > 3.10
- connecting to MR
=> docs(py): document workaround using MR client with newer py versions

.gitignore, pkg/api/error.go, pkg/core/core.go
As error codes were switched without being unwrapped, the full error (with custom data) was never matched against the actual error enum, and was only providing a patched message with the wrong status code (making tests pass even though the resulting status was wrong).
Remaining commits were WIP and can be sent separately.
Verified with httpie client.
=> Fix http error codes

clients/ui/bff/OWNERS
follow-up to:
- https://github.com/kubeflow/model-registry/issues/108
make Eder approver in subdir of the BFF work.
Note: Eder is [already a KF member](https://github.com/kubeflow/internal-acls/pull/681).
=> add ederign in OWNERS in clients/ui/bff/OWNERS

clients/python/src/model_registry/_client.py, clients/python/src/model_registry/types/contexts.py, clients/python/tests/conftest.py
This makes the owner property usable from the high-level Python API.
=> py: set author as owner when creating RegisteredModel

Makefile, go.mod
This commit will update go from go1.19 to go1.21@latest
=> Dependency Update: bump go from 1.19 to 1.21@latest

clients/python/src/model_registry/__init__.py
aligns to 
https://github.com/kubeflow/model-registry/blob/99372a5bc7007e6d8a9f3a2bab77cc9cf993ebfd/clients/python/pyproject.toml#L3
=> chore(py): align ver in init to project toml

clients/ui/frontend/package-lock.json, clients/ui/frontend/package.json, clients/ui/frontend/src/index.tsx
Remove some unused deprecated libraries from our package json
react-axe: help to fix and identify accessibility issues. The project was moved to another org so we will need to add them back later.
react-docgen-typescript-loader: it's not necessary. Leftover from the seed project
```shell
➜  frontend git:(main) ✗ npm install                                                                                                                  (kind-kubebuilder-cluster/default)
up to date, audited 1199 packages in 720ms
210 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
➜  frontend git:(main) ✗ npm audit                                                                                                                    (kind-kubebuilder-cluster/default)
found 0 …
```
=> chore: remove some unused deprecated libraries (react-axe and react-docgen-typescript-loader)

clients/python/README.md, clients/python/docs/reference.md, clients/python/src/model_registry/_client.py, clients/python/src/model_registry/core.py, clients/python/src/model_registry/types/__init__.py, clients/python/src/model_registry/types/options.py, clients/python/src/model_registry/types/pager.py, clients/python/tests/test_client.py, clients/python/tests/test_core.py
This adds listing methods for:
1. Registered Models, and
2. Model Versions associated with a Registered Model
The high-level listing methods manage a `ListOptions` instance providing a smart iterator.
The iterator can be configured in a builder style, and can be reused.
The Pager iterator can also be used at the core layer to provide a better experience for advanced users.
Updated tests to verify paging is correct.
=> Py: Extend high-level API with paging

test/robot/MRkeywords.resource, test/robot/ModelRegistry.py, test/robot/UserStory.robot
Show use of the format from `s3_uri_from` using REST based testing with RobotFramework
=> test: show s3_uri_from format in pure REST test

docker-compose.yaml
Aligns `docker-compose.yaml` image to consume upstream Kubeflow from dockerhub.
1.
`poetry run pytest` from `clients/python`:
2.
from `/`:
- `docker compose -f docker-compose.yaml up`
- `robot test/robot/UserStory.robot`
=> docker: align docker-compose image to upstream

clients/ui/docker-compose.yaml, clients/ui/frontend/.dockerignore, clients/ui/frontend/Dockerfile, clients/ui/frontend/Makefile, clients/ui/frontend/config/webpack.dev.js, clients/ui/frontend/nginx.conf
This PR allows the frontend to be served in a container using nginx and adds:
* Dockerfile for serving the frontend and proxying calls to the bff.
* An example docker-compose for running the stack.
* Webpack config for proxying and url rewriting for the frontend in dev mode.
* A frontend Makefile for building the docker image
* Run the example docker-compose file: `podman compose up -d` (swap podman for docker if that's your bag)
* Verify the frontend loads in a browser at: `localhost:8080`
* Verify the reverse proxy to the backend works via curl: `curl localhost:8080/api/v1/model-registry/` - this should return a valid response from the bff
* Run the frontend in dev mode using: `npm run start:dev` - run the bff directly using `make run PORT=4000 MOCK_K8S_CLIENT=true` in a separate …
=> Add Dockerfile for serving containerised frontend

scripts/install_protoc.sh
fixes #254 
Switches paths from relative to absolute for wget and any other command that uses it, to make it work with wget and wget2.
I tested this on my local machine by running `make bin/protoc`, and also by building the docker image.
=> fix: made install_protoc.sh compatible with wget2

api/openapi/model-registry.yaml, internal/converter/generated/mlmd_openapi_converter.gen.go, internal/converter/generated/openapi_converter.gen.go, internal/converter/generated/openapi_mlmd_converter.gen.go, internal/converter/mlmd_converter_util_test.go, internal/converter/mlmd_openapi_converter.go, internal/converter/mlmd_openapi_converter_util.go, internal/converter/openapi_mlmd_converter.go, internal/converter/openapi_mlmd_converter_util.go, internal/mapper/mapper.go, internal/mapper/mapper_test.go, internal/server/openapi/impl.go, internal/server/openapi/type_asserts.go, pkg/core/core_test.go, pkg/openapi/model_model_version.go, pkg/openapi/model_model_version_create.go, pkg/openapi/model_registered_model.go, pkg/openapi/model_registered_model_create.go, test/robot/Regression.robot
Resolves: #232 
Makes `name` a required property for contexts. This change causes the autogen OAPI models to be validated properly, but changes the type of context names to be a string, instead of a *string.
Updated tests, also created a new regression test case to cover previously crashing case.
=> openapi: require name for contexts

clients/ui/bff/api/model_registry_handler.go, clients/ui/bff/api/model_registry_handler_test.go, clients/ui/bff/data/model_registry.go, clients/ui/bff/data/model_registry_test.go, clients/ui/bff/integrations/k8s.go, clients/ui/bff/internals/mocks/k8s_mock.go
the `GET /api/v1/model-registry` endpoint will now return description and display name when using mocked out data.
1. Run the BFF using something like `make run PORT=4000 MOCK_K8S_CLIENT=true`
2. Run the following  curl: `curl localhost:4000/api/v1/model-registry/`
3. Verify 200 response and payload includes `displayName` and `description` properties
=> Adds description and display name properties to mocked ModelRegistry responses

clients/python/poetry.lock, clients/python/pyproject.toml, clients/python/src/model_registry/core.py, clients/python/src/model_registry/types/artifacts.py, clients/python/src/model_registry/types/base.py, clients/python/src/model_registry/types/contexts.py, clients/python/src/mr_openapi/api_client.py, clients/python/src/mr_openapi/configuration.py, clients/python/src/mr_openapi/models/artifact.py, clients/python/src/mr_openapi/models/metadata_value.py, clients/python/tests/basic_test.py, clients/python/tests/test_client.py, clients/python/tests/test_core.py, clients/python/tests/test_utils.py
Supersedes: #282 
Use `make tidy` to fix linter warnings.
=> Bump ruff to 0.6.1

clients/ui/frontend/src/__tests__/cypress/cypress.config.ts, clients/ui/frontend/src/__tests__/cypress/cypress/tests/mocked/application.cy.ts, clients/ui/frontend/src/__tests__/cypress/tsconfig.json, clients/ui/frontend/src/app/App.tsx, clients/ui/frontend/src/app/AppRoutes.tsx, clients/ui/frontend/src/app/NavSidebar.tsx, clients/ui/frontend/src/index.tsx, clients/ui/frontend/tsconfig.json
Updating the tsconfig files to reflect what we need to include. Mostly reflecting the same compiler options that ODH uses. Because of some changes to the config file I also had to update some import paths.
1. Ran the UI to make sure everything works normal
2. Ran cypress mock tests
=> Update tsconfig files

Makefile
implements https://github.com/kubeflow/model-registry/pull/265#issuecomment-2292505884:~:text=5%20days%20ago-,My%20biggest%20issue%20was%20the%20go%20binary%20in%20the%20bin%20directory.%20I%20thought%20that%20was%20an%20overkill,-.%20I%20was%20ok isolated from #265
=> chore: remove go from bin

clients/ui/frontend/docs/dev-setup.md, clients/ui/frontend/package-lock.json, clients/ui/frontend/package.json, clients/ui/frontend/src/app/Dashboard/Dashboard.tsx, clients/ui/frontend/src/app/Settings/Admin.tsx, clients/ui/frontend/src/app/Support/Support.tsx
Bumps [@patternfly/react-core](https://github.com/patternfly/patternfly-react) from 6.0.0-alpha.68 to 6.0.0-alpha.102.
Bumps [@patternfly/react-icons](https://github.com/patternfly/patternfly-react) from 6.0.0-alpha.34 to 6.0.0-alpha.35.
Bumps [@patternfly/react-styles](https://github.com/patternfly/patternfly-react) from 6.0.0-alpha.34 to 6.0.0-alpha.35.
The code changes was related to removal of <TextContent><Text component="p"> to  <Content component={ContentVariants.p}> from patternfly APIs.
```
npm run test:cypress-ci
```
- [X ] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) …
=> build(deps): bump @patternfly/react-{core|icons|style}

clients/ui/frontend/package-lock.json, clients/ui/frontend/package.json, clients/ui/frontend/src/app/App.tsx, clients/ui/frontend/src/app/AppContext.ts, clients/ui/frontend/src/app/useSettings.tsx, clients/ui/frontend/src/app/useTimeBasedRefresh.ts, clients/ui/frontend/src/components/browserStorage/BrowserStorageContext.tsx, clients/ui/frontend/src/components/browserStorage/index.ts, clients/ui/frontend/src/index.tsx, clients/ui/frontend/src/types.ts, clients/ui/frontend/src/utilities/const.ts, clients/ui/frontend/src/utilities/useDeepCompareMemoize.ts, clients/ui/frontend/src/utilities/useEventListener.ts
Add a High Level context (TBD the content of the context itself) to load before dashboard init.
Also added some utils to make sure we persist some of the data.
Change the harcoded values from the customHook to get different screens.
=> Add app context and revamps App.tsx

.github/pull_request_template.md
Following [github's pull request template instructions](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/creating-a-pull-request-template-for-your-repository), allow custom PR Template for UI contributions.
By default the common PR Template would appear, with a link to the UI one.
=> Add Pull Request Template for UI team

.github/workflows/csi-test.yml
This prevents CSI dependencies from being out-of-date.
=> GHA: trigger CSI tests on go.mod update

clients/ui/frontend/babel.config.js, clients/ui/frontend/config/transform.file.js, clients/ui/frontend/config/transform.style.js, clients/ui/frontend/jest.config.js, clients/ui/frontend/package-lock.json, clients/ui/frontend/package.json, clients/ui/frontend/src/__tests__/unit/jest.d.ts, clients/ui/frontend/src/__tests__/unit/jest.setup.ts, clients/ui/frontend/src/__tests__/unit/testUtils/hooks.spec.ts, clients/ui/frontend/src/__tests__/unit/testUtils/hooks.ts
Adding the unit testing directory and dependencies for Jest unit testing. I would like to rebase this off of https://github.com/kubeflow/model-registry/pull/290 when it's merged so I can update the github actions for testing the frontend.
Again a lot of this is carried over from ODH and removed some things that don't apply to us.
`npm run test:unit`
`npm run test:jest`
`npm run test:cypress-ci` and `npm run start:dev` to ensure there's no regressions.
=> Setup Jest for frontend unit testing

clients/ui/api/openapi/mod-arch.yaml
Add API specficiation for UI Modular Architecture project
Tested that the swagger is generating the UI in: https://editor-next.swagger.io/?url=https://raw.githubusercontent.com/lucferbux/model-registry/mod-arch-10569/clients/ui/api/openapi/mod-arch.yaml
=> Add mod arch OpenAPI spec

.github/workflows/python-tests.yml, clients/python/Makefile, clients/python/noxfile.py, clients/python/pyproject.toml, clients/python/tests/REST_bindings_test.py, clients/python/tests/conftest.py, clients/python/tests/test_client.py, clients/python/tests/test_core.py
As the majority of Python client tests depend on the current implementation of MR, build it in favor of using the last pushed version.
This also creates a new (e2e) test mode for the Python client to highlight the dependencies.
Updated on GHA, ran `make test-e2e` locally. Also tested with nox.
=> Test Python client against latest MR

clients/python/Makefile, clients/python/tests/conftest.py, clients/python/tests/regression_test.py, clients/python/tests/test_client.py, internal/converter/mlmd_converter_util_test.go, internal/converter/mlmd_openapi_converter_util.go
Fixes: #255
This makes all subsequent `:` (colon) separators (i.e. those provided by the user) part of the ctx name.
=> restrict captures to prefix when mapping *FromOwned

.github/labeler.yml, .github/workflows/labeler.yml
Introduce standard GH Labeler, to ease navigation of PRs list
Cannot be tested locally, will use subsequent PRs to calibrate as needed (for [more information](https://github.com/actions/labeler?tab=readme-ov-file#initial-set-up-of-the-labeler-action)).
=> chore: introduce GH Labeler for PR navigation

clients/python/src/model_registry/_client.py, clients/python/tests/conftest.py, clients/python/tests/regression_test.py
fixes #340
After running `registry.get_registered_model("X")` without providing an user_token in ModelRegistry initialization, I got the following error:
```
File /opt/app-root/lib64/python3.9/site-packages/mr_openapi/configuration.py:357, in Configuration.auth_settings(self)
350 auth = {}
351 if self.access_token is not None:
352 auth["Bearer"] = {
353 "type": "bearer",
354 "in": "header",
355 "format": "JWT",
356 "key": "Authorization", -->
357 "value": "Bearer " + self.access_token, <- affected line
358 }
359 return auth
TypeError: can only concatenate str (not "bytes") to str
```
thanks to @isinyaaa , we figured out that there was a bug in the token parsing function in the client code and switched from reading it from "bytes mode" to "text mode"
Uploaded the wheel on the notebook and …
=> py: fix access token parsing

clients/python/README.md, clients/python/src/model_registry/_client.py, clients/python/tests/test_client.py
Implements: #319
Updated e2e tests
=> py: client: add update method for supported types

.github/labeler.yml
fix typo in labeler config (lowercase `ui`) and quote all paths
n/a
=> gha: fix typo in labeler config and quote

clients/ui/bff/README.md, clients/ui/bff/api/app.go, clients/ui/bff/api/registered_models_handler.go, clients/ui/bff/data/registered_model.go, clients/ui/bff/data/registered_model_test.go
Adds an endpoint to fetch registered models by id.
Test rig setup:
1. Deploy MR backend (you can follow the guide using kind in the docs)
2. Deploy BFF with e.g. `make run PORT=4000 MOCK_K8S_CLIENT=true`
3. Add a model to one of the registries: 
```
curl -i -X POST "http://localhost:4000/api/v1/model-registry/model-registry/registered_models" \
-H "Content-Type: application/json" \
-d '{
"customProperties": {
"my-label9": {
"metadataType": "MetadataStringValue",
"string_value": "val"
}
},
"description": "bella description",
"externalId": "9927",
"name": "bella",
"owner": "eder",
"state": "LIVE"
}'
```
Test routine:
1. Verify the endpoint returns a 200 and the model from the endpoint: `curl -i localhost:4000/api/v1/model-registry/model-registry/registered_models/1`
2. Try with a different …
=> Adds an endpoint to get a registered model by id

clients/ui/frontend/src/__mocks__/mockRegisteredModel.ts, clients/ui/frontend/src/__mocks__/utils.ts, clients/ui/frontend/src/app/api/__tests__/errorUtils.spec.ts, clients/ui/frontend/src/app/api/__tests__/service.spec.ts, clients/ui/frontend/src/app/api/apiUtils.ts, clients/ui/frontend/src/app/api/errorUtils.ts, clients/ui/frontend/src/app/api/k8s.ts, clients/ui/frontend/src/app/api/service.ts, clients/ui/frontend/src/app/components/design/DividedGallery.scss, clients/ui/frontend/src/app/components/design/DividedGallery.tsx, clients/ui/frontend/src/app/components/design/DividedGalleryItem.tsx, clients/ui/frontend/src/app/components/design/TypeBorderCard.scss, clients/ui/frontend/src/app/components/design/TypeBorderedCard.tsx, clients/ui/frontend/src/app/const.ts, clients/ui/frontend/src/app/types.ts, clients/ui/frontend/src/typeHelpers.ts, clients/ui/frontend/src/types.ts, clients/ui/frontend/src/utilities/useFetchState.ts
Add the API module for the UI project with all the endpoints specified in the swagger.
Test coverage for the api module.
**No UI changes**.
Test coverage for the API module.
=> UI - Model Registry API spec

.github/workflows/python-tests.yml
Hopefully ease out local testing, without having to wait for a release for the py whl.
For more information, reference the [github documentation](https://docs.github.com/en/organizations/managing-organization-settings/configuring-the-retention-period-for-github-actions-artifacts-and-logs-in-your-organization#:~:text=By%20default%2C%20the%20artifacts%20and%20log%20files%20generated%20by%20workflows%20are%20retained%20for%2090%20days%20before%20they%20are%20automatically%20deleted.).
n/a
=> gha: provide py dist as gh artifact

api/openapi/model-registry.yaml, clients/python/noxfile.py, clients/python/poetry.lock, clients/python/pyproject.toml, clients/python/src/model_registry/_client.py, clients/python/src/model_registry/core.py, clients/python/src/model_registry/types/pager.py, clients/python/src/mr_openapi/models/order_by_field.py, clients/python/tests/test_client.py, pkg/openapi/model_order_by_field.go
Fixes: https://github.com/kubeflow/model-registry/issues/353
Updates the orderBy.Id -> ID as that's what's expected on MLMD.
=> py: fix order by ID

clients/ui/bff/Makefile, clients/ui/bff/README.md, clients/ui/bff/api/app.go, clients/ui/bff/api/helpers.go, clients/ui/bff/api/registered_models_handler.go, clients/ui/bff/api/registered_models_handler_test.go, clients/ui/bff/cmd/main.go, clients/ui/bff/config/environment.go, clients/ui/bff/data/model_registry_client.go, clients/ui/bff/data/registered_model.go, clients/ui/bff/data/registered_model_test.go, clients/ui/bff/internals/mocks/model_registry_client_mock.go, clients/ui/bff/internals/mocks/static_data_mock.go
This adds scaffolding to be able to serve mocked data for MR API endpoints. It also incudes endpoints to mock all existing BFF endpoints and their tests. The remaining endpoints will be added shortly after in a separate PR
1. Run the backend with the `MOCK_MR_API=true` flag (See README updates for more info)
2. Run each of the example curl requests listed in the README and verify the output
=> Adds ability to serve mocked data for MR API calls via cli flag

clients/ui/frontend/.eslintrc, clients/ui/frontend/package-lock.json, clients/ui/frontend/package.json, clients/ui/frontend/src/__tests__/unit/testUtils/hooks.ts, clients/ui/frontend/src/components/browserStorage/BrowserStorageContext.tsx
- Regenerated package-lock.json due to node major version bump.
- Removed victory types 
-  Bump @typescript-eslint/eslint-plugin
- Bump   @typescript-eslint/parser
npm install
npm run start:dev
No ui changes.
=> npm update and versions bumps

CONTRIBUTING.md, internal/testutils/test_container_utils.go
fixes #268 
I set Privileged to true to test containers because SELinux prevented containers from reading metadata from the `conn_config.pb` file, which caused the container to use the in-memory database that does not persist data instead of the SQLite one, causing all tests to fail.
I also improved podman detection on systems that do not require a machine by adding a check to the `DOCKER_HOST` environment variable.
It's worth noting that I tried other ways to get it to work, both disabling Ryuk and trying to set different SELinux policies by following the [testcontainers podman guide](https://golang.testcontainers.org/system_requirements/using_podman/#fedora), but none of them worked.
I tested this on my local machine by running `make test`
=> fix: make tests work on fedora

clients/ui/bff/Dockerfile, clients/ui/manifests/base/README.md, clients/ui/manifests/base/kustomization.yaml, clients/ui/manifests/base/model-registry-bff-deployment.yaml, clients/ui/manifests/base/model-registry-bff-role.yaml, clients/ui/manifests/base/model-registry-bff-service.yaml, clients/ui/manifests/base/model-registry-ui-deployment.yaml, clients/ui/manifests/base/model-registry-ui-service.yaml
Adding a manifests directory to the `clients/ui` directory for hosting our K8s resource definition files. This adds a basic deployment using kustomize for the UI and BFF. I also added a README with instructions on how to deploy using kind.
Follow the steps listed in the README.
=> Add manifests dir to define K8s resources for the UI

go.mod, internal/testutils/test_container_utils.go
extract single commit from PR https://github.com/kubeflow/model-registry/pull/324 until that will be merged 
so to avoid continue rebasing due to dependency tree updates.
=> keep deprecated method for mount for TestContainers to avoid direct API dep.

clients/python/tests/test_client.py, test/robot/UserStory.robot
migrate User Story _from_ RobotFramework:
https://github.com/kubeflow/model-registry/blob/12f6cb9593c5f2381fa099053fce8e1eadc6d4db/test/robot/UserStory.robot#L72-L91
_to_ pytest,
following awesome work from @isinyaaa to introduce e2e testing directly with pytest:
- https://github.com/kubeflow/model-registry/pull/326
`make test-e2e`
=> doc: migrate User Story from Robot to pytest

clients/ui/bff/README.md, clients/ui/bff/api/errors.go, clients/ui/bff/api/helpers.go, clients/ui/bff/api/model_registry_handler.go, clients/ui/bff/api/model_registry_handler_test.go, clients/ui/bff/api/registered_models_handler.go, clients/ui/bff/api/registered_models_handler_test.go
Updates the BFF API contract to use envelopes more consistently.
* All endpoints now use the standard `data` key for the primary payload
* POST/PATCH endpoints now accept a request body that matches the envelope format and formats the response body in the same way
* Run through the examples CURLs in the README
* Verify that the endpoints use the new envelope format ```{ "data": ... }``` for both request and response bodies
=> Update API models to use envelope format consistently

.github/workflows/fossa-license-scanning.yml, CONTRIBUTING.md, go.mod, internal/testutils/test_container_utils.go
Please reference for a complete summary: https://github.com/kubeflow/model-registry/issues/323
Resolves #323 by introducing FOSSA license scanning, a tool supported by CNCF, in the way recommended by the tool documentation and as implemented by other projects.
n/a
=> gha: fossa license scanning

clients/ui/bff/README.md, clients/ui/bff/api/model_versions_handler.go, clients/ui/bff/api/model_versions_handler_test.go, clients/ui/bff/api/registered_models_handler.go, clients/ui/bff/api/registered_models_handler_test.go, clients/ui/bff/integrations/http.go
Adds support for PATCH requests when mock mode is disabled.
* Deploy MR to kind
* Run BFF locally with MR API mock mode disabled, e.g. `make run PORT=4000 MOCK_K8S_CLIENT=true MOCK_MR_CLIENT=false`
* Create a RegisteredModel to work with: 
```
curl -i -X POST "http://localhost:4000/api/v1/model_registry/model-registry/registered_models" \
-H "Content-Type: application/json" \
-d '{ "data": {
"customProperties": {
"my-label9": {
"metadataType": "MetadataStringValue",
"string_value": "val"
}
},
"description": "Old description",
"externalId": "9927",
"name": "bella",
"owner": "eder",
"state": "LIVE"
}}'
```
* Create a ModelVersion to work with: 
```
curl -i -X POST "http://localhost:4000/api/v1/model_registry/model-registry/registered_models/1/versions" \
-H "Content-Type: application/json" …
```
=> Adds support for PATCH requests in live cluster mode

Dockerfile, Makefile, internal/server/openapi/type_asserts.go, scripts/gen_type_asserts.sh
Cleanup Makefile and Dockerfile to make them reproducable
Add multi-arch platform builds
CI will verify Makefile and Dockerfile changes
Dockerfile changes can be tested locally by updating model-registry.yaml
=> fix: fix Makefile and Dockerfile for idempotent images and to support multi-arch builds Fixes RHOAIENG-12078

clients/python/README.md
Updated legacy notes, comments WIP bug functionality.
=> Py: update README

clients/python/pyproject.toml, clients/python/src/model_registry/__init__.py
=> chore: py version bump

CONTRIBUTING.md, docs/mr_kind_deploy_ingress.md
I have added a small guide to deploy model registry on a kind cluster using an ingress instead of port-forward, hoping people will find it useful for local testing
followed locally the steps described in the guide
=> feat(docs): add kind - ingress instructions to deploy model registry

clients/python/README.md
Kubeflow Model Registry is an Alpha component, per website: https://www.kubeflow.org/docs/components/model-registry/overview/#:~:text=Kubeflow%20Model%20Registry-,Alpha,-This%20Kubeflow%20component
This adds the same banner on the readme for the python wheel/library.
Hopefully this could be also propaedeutic to simply have one of the next py version to drop the `.a1` suffix, I don't find it very ergonomic to access from pypi too.
@isinyaaa wdyt?
=> py: show Kubeflow alpha banner like website

csi/test/e2e_test.sh, csi/test/test_utils.sh
fixes a race condition found in the ci CSI tests: https://github.com/opendatahub-io/model-registry/actions/runs/10997757515/job/30534062040#logs
run the ci
=> fix(csi): prevent race condition in ci tests step

clients/ui/frontend/package-lock.json, clients/ui/frontend/package.json
[serve](https://www.npmjs.com/package/serve) is used on our dev environment to run cypress tests. It depends on path-to-regexp that has a known vulnerability. This is not a risk issue for our project because it's only a dev dependency but triggers dependabot alerts.
While we wait for an upgrade of serve library (https://github.com/vercel/serve/issues/811 and https://github.com/vercel/serve-handler/issues/211#issuecomment-2352276383), I've decided to manually patch in our dependencies to a [version](https://github.com/pillarjs/path-to-regexp/releases/tag/v3.3.0) with the fix. 
Meanwhile, we are also investigating migrating from serve to another HTTP serve library to run our cypress tests.
````
➜  frontend git:(remove-serve) npm audit …
```
=> temporarly bump on path-to-regexp

README.md
Providing a handy TOC/index linking to all documentation in shape of form helpful for an overview of the available content for Model Registry: introductory concepts, Python client, tutorials and development.
=> docs: provide an index/toc of the documentation

clients/ui/frontend/src/components/DashboardDescriptionListGroup.tsx
In my last PR I was using `text.iconColorSubtle` to get around the disabled color being to low of a color ratio on a white background. It was causing our a11y testing to fail. Turns out you don't need to pass color contrast ratios on disabled elements so conditionally adding the `aria-disabled` attribute will cause the tests to pass.
The color change is probably not noticeable enough to anyone but can add an image if requested.
Running cypress mock tests
=> Fix disabled text color on DescriptionListDescription

clients/ui/frontend/package-lock.json, clients/ui/frontend/package.json, clients/ui/frontend/src/app/pages/modelRegistry/ModelRegistryRoutes.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersions/ModelVersionsTable.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisteredModels/RegisteredModelListView.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisteredModels/RegisteredModelTable.tsx, clients/ui/frontend/src/index.html, clients/ui/frontend/src/index.tsx, clients/ui/frontend/src/style/MUI-theme.scss
Applies theming and styles to MR UI for Registered Models List View.
Before:
After:
Visual updates only - tested manually in UI.
-  [x] Code changes follow the [kubeflow contribution guidelines](https://www.kubeflow.org/docs/about/contributing/).
=> Apply MUI theming to Registered Model List View

clients/ui/frontend/package-lock.json, clients/ui/frontend/package.json
Superseeds https://github.com/kubeflow/model-registry/actions/runs/11013203031/job/30581022367?pr=417
For some reason, dependabot was adding some extra things. Let's try this one.
npm run start:dev
=> version bump for eslint-config-prettier

.github/workflows/build-and-push-ui-images.yml, Makefile, clients/ui/manifests/base/kustomization.yaml
Added a GH Action for building and pushing the UI and BFF images. Reuses the build script for Model Registry server, and edits the Makefile a little bit to get everything working. I also turned off image builds for MR server when a PR is being made only for UI / BFF changes. I can remove that if we want to keep building them.
Going to test the PR as `on: pull_request` then if it passes will update the PR to run the action `on: push`.
=> Add GitHub Action for building and pushing UI and BFF images

clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisterModel/PrefilledModelRegistryField.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisterModel/RegisterModel.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisterModel/RegisterVersion.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisterModel/RegisteredModelSelector.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisterModel/RegistrationCommonFormSections.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisteredModels/RegisteredModelListView.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/components/FormFieldset.tsx, clients/ui/frontend/src/style/MUI-theme.scss
Applies theming and styles to MR UI for Registered Model Form.
Before:
After:
Visual updates only - tested manually in UI. Navigate to Model Registry list view and click "Register Model" button in toolbar.
=> Apply MUI theming to Register Model Form

clients/ui/bff/internal/mocks/static_data_mock.go, clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelPropertiesTableRow.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersions/ModelVersionListView.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/components/FormFieldset.tsx, clients/ui/frontend/src/components/EditableTextDescriptionListGroup.tsx, clients/ui/frontend/src/style/MUI-theme.scss
Applies MUI theming to "Versions" and "Details" Screens
Model Versions List View - Before:
Model Versions List View - After:
Model Details Description Input - Before:
Model Details Description Input - After:
Model Details Properties Table - Before:
Model Details Properties Table - After:
What's been changed:
1. Model Versions List View
- "Register Version" Button - applied MUI hover color
- Page container - updated to apply MUI border radius and drop shadow
- Tabs - Fixed padding bug to center text within tab correctly
- Search input - replaced existing search filter component with new FormFieldset component to apply MUI theming
2. Model Details View
- Action buttons (i.e. "Edit", "Add Property") - applied MUI link styling to darken underline of link button when hovered
- "Description" …
=> Apply MUI theming to "Versions" and "Details" Screens

.github/workflows/build-image-pr.yml, .github/workflows/python-tests.yml, clients/python/Makefile, clients/python/noxfile.py, clients/python/poetry.lock, clients/python/tests/conftest.py, clients/python/tests/regression_test.py, clients/python/tests/test_client.py, scripts/cleanup.sh, scripts/deploy_on_kind.sh
Fixes: #380
Python e2e tests will use an environment variable to MR, delegating clean-up to a separate script.
The script is made environment-aware using envvars.
The CI has been updated to account for the changes, separating the Python workflows into 3 types to make it clearer.
=> use deployed MR for python e2e tests

clients/ui/frontend/package-lock.json, clients/ui/frontend/package.json, clients/ui/frontend/src/app/components/design/utils.ts
In this PR:
- Bump of @typescript-eslint/parser from 8.5.0 to 8.8.1
- Bump of @typescript-eslint/eslint-plugin from 8.5.0 to 8.8.1
- Bump of @typescript-eslint/eslint-plugin-import to 2.31.0
- Ignore some eslint warnings on util.js
- Bump of cookie (low sev cve)
Ran tests and web app.
=> chore(frontend): Version bumps

.github/workflows/python-tests.yml, scripts/deploy_on_kind.sh, scripts/utils.sh
I have added the repeat_until function to wait while the pod rollout is done by kind, enabled the kind load job and made the action more reliable
run the deploy_on_kind.sh script locally, debug on CI
=> fix(gha): prevent race condition on port-forward

clients/ui/bff/internal/integrations/k8s.go
Add displayName and description when we get service details from the cluster. This is based off of the fact that we expect MR or the user deploying the MR service to add the `displayName` and `description` to `annotations` on the service.
1. To reproduce deploy a kind cluster locally following the [guide](https://github.com/kubeflow/model-registry/blob/main/clients/ui/bff/docs/dev-guide.md) 
2. Run BFF in live mode like `make run PORT=4000 MOCK_K8S_CLIENT=false MOCK_MR_CLIENT=false`
3. Get model registries with `curl http://localhost:4000/api/v1/model_registry`. You should see the BFF log a couple errors because you will be missing a displayName and description
```
{
"data": [
{
"name": "model-registry-service",
"displayName": "",
"description": ""
}
]
}
```
4. Now stop the BFF and add …
=> Add displayName and description to GetServiceDetails

csi/GET_STARTED.md, manifests/kustomize/options/csi/clusterstoragecontainer.yaml, manifests/kustomize/options/csi/kustomization.yaml
Added manifests for CSI deployment, the following:
```yaml
- name: MODEL_REGISTRY_BASE_URL
value: "model-registry-service.kubeflow.svc.cluster.local:8080"
```
cannot be parameterized as an env from configmap because the way kserve works is to use it as a template for an initcontainer that is injected into the serving deployment, so it has to be viewed as a fallback URL to reach the default model registry.
```bash
docker build . -f Dockerfile -t mr/mr:0.1.1
LOCAL=1 IMG=mr/mr:0.1.1 ./scripts/deploy_on_kind.sh
```
then followed the guide from csi/GET_STARTED.md
=> feat(csi): add CSI manifests

clients/ui/frontend/src/app/components/DashboardModalFooter.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/components/ArchiveModelVersionModal.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/components/ArchiveRegisteredModelModal.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/components/RestoreModelVersionModal.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/components/RestoreRegisteredModel.tsx, clients/ui/frontend/src/style/MUI-theme.scss
Updates theming overrides to align with [PF breaking change standards](https://docs.google.com/document/d/1HipMvYqlUpTIP2H4QtCMAGdsu8TCCW7XKuR4imGarkA/edit#heading=h.c9wk66om5xcd).
N/A, refactoring only. 
To test modal refactoring updates: 
1. Model Registry list view -> Actions menu on table row -> "Archive model"
2. Model Registry list view -> Actions menu next to "Register Model" button in toolbar -> Click "View Archived Models" -> Archived models list view -> Actions menu on table row -> "Restore Model"
3. Model Registry list view -> Click on model -> Versions Tab -> Actions menu on table row -> Click "Archive model version"
4. Model Registry list view -> Click on model -> Versions Tab -> Actions menu next to "Register Model" button in toolbar -> Click "View Archived Versions"-> …
=> Apply PF Breaking Change Best Practices to MUI Theme Stylesheet

clients/ui/bff/.golangci.yaml
Adding a golangci-lint config file to increase our timeout, so we won't get failures in CI. Setting the timeout to 3m (default is 1m). Open to discussion if 3m is too big or too small.
Changed timeout to something really short (1ms) and got:
```
ERRO Timeout exceeded: try increasing it by passing --timeout option 
```
=> Add golangci-lint timeout to fix CI

csi/README.md
=> docs: typo fix

clients/ui/frontend/src/app/components/DashboardSearchField.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersionsArchive/ModelVersionsArchiveListView.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersionsArchive/ModelVersionsArchiveTable.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisteredModelsArchive/RegisteredModelsArchiveListView.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisteredModelsArchive/RegisteredModelsArchiveTable.tsx, clients/ui/frontend/src/style/MUI-theme.scss
Before - archived models list label: 
After - archived models list label: 
Before - archived models list search filter:
After - archived models list search filter:
Before - archived models list pagination:
After - archived models list pagination:
Before - close button border radius:
After - close button border radius
Before - archive version modal
After - archive version modal
1. Model Registry list view -> Actions menu next to "Register Model" button in toolbar -> Click "View Archived Models" -> Archived models list view -> Click on a model in the list -> Verify label text color is correct
2. Model Registry list view -> Actions menu next to "Register Model" button in toolbar -> Click "View Archived Models" -> Archived models list view -> Verify search filter and pagination has correct …
=> Applies bug fixes to UI screens

clients/ui/bff/Makefile, clients/ui/bff/go.mod, clients/ui/bff/internal/api/app.go, clients/ui/bff/internal/api/model_registry_handler_test.go, clients/ui/bff/internal/api/model_versions_handler_test.go, clients/ui/bff/internal/api/registered_models_handler_test.go, clients/ui/bff/internal/api/suite_test.go, clients/ui/bff/internal/api/test_utils.go, clients/ui/bff/internal/integrations/k8s.go, clients/ui/bff/internal/mocks/k8s_mock.go, clients/ui/bff/internal/mocks/k8s_mock_test.go, clients/ui/bff/internal/mocks/suite_test.go, clients/ui/bff/internal/repositories/model_registry_test.go, clients/ui/bff/internal/repositories/suite_test.go
Use envtest for kubernetes testing instead of hardcoded mock
This PR starts to use envtest for Kubernetes mocking. It also fixes a minor issue when there are no annotations on the service.
make run MOCK_K8S_CLIENT=true MOCK_MR_CLIENT=true and also ran the web app:
No UI changes.
=> feat(bff): Use envtest for kubernetes testing instead of hardcoded mock

clients/ui/bff/internal/mocks/k8s_mock.go
On go 23, this error occurs:
internal/mocks/k8s_mock.go:53:52: slog.Logger.Error arg "err" should be a string or a slog.Attr (possible missing key or value)
internal/mocks/k8s_mock.go:60:54: slog.Logger.Error arg "err" should be a string or a slog.Attr (possible missing key or value)
internal/mocks/k8s_mock.go:67:40: slog.Logger.Error arg "err" should be a string or a slog.Attr (possible missing key or value)
Ran the BFF and ran the FE.
=> Fixing slog.Logger.Error arg err should be a string or a slog.Attr (possible missing key or value)

clients/ui/frontend/package-lock.json, clients/ui/frontend/package.json, clients/ui/frontend/src/__tests__/cypress/cypress/pages/components/Notification.ts, clients/ui/frontend/src/__tests__/cypress/cypress/pages/modelRegistry.ts, clients/ui/frontend/src/__tests__/cypress/cypress/support/commands/api.ts, clients/ui/frontend/src/__tests__/cypress/cypress/support/commands/application.ts, clients/ui/frontend/src/__tests__/cypress/cypress/tests/mocked/modelVersionArchive.cy.ts, clients/ui/frontend/src/__tests__/cypress/cypress/tests/mocked/modelVersions.cy.ts, clients/ui/frontend/src/__tests__/cypress/cypress/tests/mocked/registeredModelArchive.cy.ts, clients/ui/frontend/src/app/App.tsx, clients/ui/frontend/src/app/context/NotificationContext.tsx, clients/ui/frontend/src/app/hooks/useNotification.ts, clients/ui/frontend/src/app/pages/modelRegistry/screens/components/ArchiveModelVersionModal.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/components/ArchiveRegisteredModelModal.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/components/RestoreModelVersionModal.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/components/RestoreRegisteredModel.tsx, clients/ui/frontend/src/app/types.ts, clients/ui/frontend/src/components/ToastNotification.tsx, clients/ui/frontend/src/components/ToastNotifications.tsx, clients/ui/frontend/src/index.tsx
This PR adds a new global context for Notifications. I also added a `useNotification` hook to allow for easier dispatching by calling the specific method you want to use `notification.success` or `notification.error`. I also looped in the removal of notifications into this hook. You can call it like: 
```javascript
notifications = useNotification() // returns state for notifications
...
notifications.remove(notification.id)
```
* I still not have tested restoring an archived version yet since I can't do it in mocked mode
There are a couple known issues at the moment:
1. The id count gets reset to 0 whenever you change pages meaning if you switch pages quickly and get another notification they will have the same id
2. The notification exit button looks out of place (I think it should be …
=> Add NotificationContext and useNotification hook

clients/python/Makefile, clients/python/noxfile.py, clients/python/tests/test_client.py
edit: this add a non-regression test based on user feedback
`make test-e2e`
=> py: non-regression of user-feedback flow

clients/ui/bff/internal/api/middleware.go, clients/ui/bff/internal/integrations/k8s.go, clients/ui/frontend/src/shared/api/apiUtils.ts
In this PR:
- middleware.go: load the bearerToken from x-forwarded-access-token and did a small refactoring to avoid leaking k8s client api;
- k8s.go: move the rest.inclusterConfig logic here for better encapsulation
- apiUtils.go: add the token parameter to the header also in calls where content type is set,
1. Built UI and BFF images locally and pushed to kind.
2. Used new 'make kind-deployment' to create and deploy everything to kind.
=> feat(bff): load x-forwarded-access-token in cluster setup

clients/ui/bff/Makefile, clients/ui/bff/cmd/main.go, clients/ui/bff/docs/dev-guide.md, clients/ui/bff/internal/api/middleware.go, clients/ui/bff/internal/config/environment.go
This PR allows developers to run a local MR cluster in kind and port forward their service to work with the BFF running locally.
Follow the [dev guide](https://github.com/kubeflow/model-registry/blob/main/clients/ui/bff/docs/dev-guide.md) all the way to step 4.
Port forward with:
```
kubectl port-forward svc/model-registry-service 8081:8080 -n kubeflow
```
Run the BFF with:
```
make run DEV_MODE=true DEV_MODE_PORT=8081
```
and the UI in a separate terminal.
You should see an empty MR that you can interact with (make models, versions, archive, restore, etc)
=> Add BFF dev mode for local K8s testing

clients/ui/bff/Makefile
Adds some docs to the Makefile for the `make help` command. It could be improved by documenting the args each command takes, but this is a start.
run `make help` and behold.
=> Improves 'make help' documentation

clients/ui/frontend/src/__mocks__/mockBFFResponse.ts, clients/ui/frontend/src/__tests__/cypress/cypress/support/commands/api.ts, clients/ui/frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelRegistry.cy.ts, clients/ui/frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistrySettings/modelRegistrySettings.cy.ts, clients/ui/frontend/src/__tests__/cypress/cypress/tests/mocked/modelVersionArchive.cy.ts, clients/ui/frontend/src/__tests__/cypress/cypress/tests/mocked/modelVersionDetails.cy.ts, clients/ui/frontend/src/__tests__/cypress/cypress/tests/mocked/modelVersions.cy.ts, clients/ui/frontend/src/__tests__/cypress/cypress/tests/mocked/registeredModelArchive.cy.ts
This changes what our `interceptApi` Cypress command returns, so that we don't have to wrap all of our mock calls with `mockBFFResponse`. I also duplicated a file that was a duplicate (`mockBFFResponse.ts` the function in this file was already in utils which makes more sense)
Just a test enhancement, so as long as tests pass we are good.
=> Limit use of mockBFFResponse in mock tests

clients/ui/OWNERS
Add @lucferbux and @Griffin-Sullivan as approvers in the UI repo
=> Add lucferbux and Griffin-Sullivan as approvers in the UI

clients/ui/frontend/src/app/App.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelPropertiesTableRow.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersions/ModelVersionListView.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersionsArchive/ModelVersionsArchiveListView.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisterModel/PrefilledModelRegistryField.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisterModel/RegisterModel.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisterModel/RegisteredModelSelector.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisterModel/RegistrationCommonFormSections.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisteredModels/RegisteredModelListView.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisteredModels/RegisteredModelsTableToolbar.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisteredModelsArchive/RegisteredModelsArchiveListView.tsx, clients/ui/frontend/src/shared/components/DashboardSearchField.tsx, clients/ui/frontend/src/shared/components/EditableTextDescriptionListGroup.tsx, clients/ui/frontend/src/shared/style/MUI-theme.scss, clients/ui/frontend/src/shared/utilities/const.ts
Adds env var to support toggling MUI theme on / off. 
Verify that the MUI theme is toggled on / off based on the value of `STYLE_THEME`. 
Tests N/A, visual updates only. 
=> Add enum and env var to conditionally render MUI theme

clients/python/src/model_registry/_client.py
Adds logging and additional keyword args to the Python client.
This also makes the custom_ca totally optional and not sourced by default by any means.
Logging settings can be further extended (e.g. with a prefix path for file logging) using other constructor flags.
=> py: client: add logging

clients/ui/bff/README.md, clients/ui/bff/internal/api/app.go, clients/ui/bff/internal/api/errors.go, clients/ui/bff/internal/api/healthcheck__handler_test.go, clients/ui/bff/internal/api/healthcheck_handler.go, clients/ui/bff/internal/api/middleware.go, clients/ui/bff/internal/api/model_versions_handler_test.go, clients/ui/bff/internal/api/registered_models_handler_test.go, clients/ui/bff/internal/api/test_utils.go, clients/ui/bff/internal/integrations/http.go, clients/ui/bff/internal/integrations/k8s.go, clients/ui/bff/internal/mocks/k8s_mock.go, clients/ui/bff/internal/mocks/k8s_mock_test.go, clients/ui/bff/internal/models/health_check.go, clients/ui/bff/internal/repositories/health_check.go, clients/ui/frontend/docs/dev-setup.md, clients/ui/manifests/user-rbac/kubeflow-dashboard-rbac.yaml, clients/ui/manifests/user-rbac/kustomization.yaml, clients/ui/scripts/deploy_kind_cluster.sh
In Kubeflow's Central Dashboard, the kubeflow-userid header carries the user's email address for authentication purposes. When a user accesses applications through the dashboard, each request includes this header, allowing the application to identify the user.
On the BFF, we are using kubeflow-userid header to do Authorization via SubjectAccessReview on all endpoints. For all endpoints we only authorize requests from users that can "get", "list" services via ClusterRole.
One thing that we need to double-check with other people from community (@tarilabs please chime in), is that instead of a ClusterRole, we should not do SubjectAccessReview for a given namespace. I've implemented in a 'cluster level' access because my understanding is that model registries access are not restricted by …
=> feat(bff): use 'kubeflow-userid' header to authorize BFF endpoints

clients/ui/bff/README.md, clients/ui/bff/internal/api/app.go, clients/ui/bff/internal/api/middleware.go, clients/ui/bff/internal/api/user_handler.go, clients/ui/bff/internal/api/user_handler_test.go, clients/ui/bff/internal/integrations/k8s.go, clients/ui/bff/internal/mocks/k8s_mock.go, clients/ui/bff/internal/mocks/k8s_mock_test.go, clients/ui/bff/internal/models/user.go, clients/ui/bff/internal/repositories/repositories.go, clients/ui/bff/internal/repositories/user.go
Create a new user endpoint to allow frontend to see if kubeflow-userid header is a cluster admin. 
This PR is a FUP of [discussion](https://github.com/kubeflow/model-registry/pull/599#issuecomment-2515156274), and it allows the frontend to enable and disable the namespace selector on the UI.
In this PR:
- clients/ui/bff/internal/api/app.go: added the GET /v1/user endpoint;
- clients/ui/bff/internal/api/middleware.go: skip the SAR on this endpoint. This operation is, in my point of view safe because it just provide the logged user email address and a boolean telling if it's a cluster admin or not;
- clients/ui/bff/internal/api/user_handler.go and clients/ui/bff/internal/api/user_handler_test.go: respective handler and it's tests;
- clients/ui/bff/internal/integrations/k8s.go: add the …
=> feat(bff): user info endpoint

clients/ui/api/openapi/mod-arch.yaml, clients/ui/bff/internal/models/health_check.go, clients/ui/bff/internal/models/user.go, clients/ui/frontend/src/__mocks__/mockUserSettings.ts, clients/ui/frontend/src/__tests__/cypress/cypress/support/commands/api.ts, clients/ui/frontend/src/__tests__/cypress/cypress/support/e2e.ts, clients/ui/frontend/src/app/App.tsx, clients/ui/frontend/src/app/AppRoutes.tsx, clients/ui/frontend/src/app/NavBar.tsx, clients/ui/frontend/src/shared/api/apiUtils.ts, clients/ui/frontend/src/shared/api/k8s.ts, clients/ui/frontend/src/shared/api/types.ts, clients/ui/frontend/src/shared/hooks/useSettings.tsx, clients/ui/frontend/src/shared/style/MUI-theme.scss, clients/ui/frontend/src/shared/types.ts, clients/ui/frontend/src/shared/utilities/const.ts
In this PR:
* Support `username` and `isAdmin` based on #630 
* Add elements in navbar to mimic Kubeflow Central Dashboard
* Removes part of the TODOs we need to fix before the release
1. In PoC mode and mock mode
2. Log in
3. Check that you can communicate with the backend
=> Improve username logic and add navbar elements

clients/ui/bff/README.md, clients/ui/bff/internal/integrations/k8s.go, clients/ui/bff/internal/mocks/k8s_mock.go
This PR sits on top of https://github.com/kubeflow/model-registry/pull/630 and update bff service filtering to match model registry services by component: model-registry label.
In this specific PR: ([commit](https://github.com/kubeflow/model-registry/commit/b8be495613111d00b187c0865815dc570e70f431))
- clients/ui/bff/README.md : add a FAQ section detailing what is setup on env test mock and also how we do model registry service filtering
On clients/ui/bff/internal/integrations/k8s.go
- Removed some duplicated logic on GetServiceNames()
- On GetServiceDetails, removed component filtering in favor of label filtering (much more efficient)
- I've also make all context with similar values (30seconds)
- clients/ui/bff/internal/mocks/k8s_mock.go: added label for our 3 services and created a new …
=> feat(bff): update bff service filtering to match model registry services by component: model-registry label

.github/workflows/csi-test.yml
As the image from ubuntu:latest switched to 24.04 in GHA, we need to change the package name for `netcat`
ref: https://github.com/kubeflow/model-registry/actions/runs/12356591704/job/34482831856
```shell
podman run -it --rm ubuntu:latest bash
root@9f67dd004abf:/# netcat -z localhost 80
bash: netcat: command not found
root@9f67dd004abf:/# apt-get update && apt-get install -y netcat
Get:1 http://security.ubuntu.com/ubuntu noble-security InRelease [126 kB]
Get:2 http://archive.ubuntu.com/ubuntu noble InRelease [256 kB]
Get:3 http://security.ubuntu.com/ubuntu noble-security/main amd64 Packages [702 kB]
Get:4 http://archive.ubuntu.com/ubuntu noble-updates InRelease [126 kB]
Get:5 http://archive.ubuntu.com/ubuntu noble-backports InRelease [126 kB]
Get:6 http://archive.ubuntu.com/ubuntu …
```
=> fix(ci): change netcat package on ubuntu 24.04

.github/workflows/python-tests.yml
proposal for https://github.com/kubeflow/model-registry/issues/614
please note
> Note All include combinations are processed after exclude
from: https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/running-variations-of-jobs-in-a-workflow#excluding-matrix-configurations
see https://github.com/kubeflow/model-registry/pull/659#issuecomment-2546855431
=> build: use also different K8s versions for E2E testing in GHA

clients/ui/bff/README.md, clients/ui/bff/internal/api/app.go, clients/ui/bff/internal/api/healthcheck__handler_test.go, clients/ui/bff/internal/api/healthcheck_handler.go, clients/ui/bff/internal/api/middleware.go, clients/ui/bff/internal/api/namespaces_handler.go, clients/ui/bff/internal/api/namespaces_handler_test.go, clients/ui/bff/internal/api/test_utils.go, clients/ui/bff/internal/api/user_handler_test.go, clients/ui/bff/internal/integrations/k8s.go, clients/ui/bff/internal/mocks/k8s_mock.go, clients/ui/bff/internal/models/namespace.go, clients/ui/bff/internal/repositories/namespace.go, clients/ui/bff/internal/repositories/repositories.go
This PR introduces a new endpoint (GET /v1/namespaces) in dev mode (standalone app) to populate the namespaces dropdown.
It's important to highlight that this new endpoint is only available in BFF dev mode (DEV_MODE=true)
```shell
make run MOCK_K8S_CLIENT=true MOCK_MR_CLIENT=true DEV_MODE=true
```
In this PR:
- clients/ui/bff/internal/api/middleware.go: 
1. Created context keys;
2. Created kubeflow group headers (preparing for a following PR)
3. Inject kubeflow-userid and kubeflow-groups header in the request context
4. Refactoring on exempt paths for RequireAccessControl to receive a list of paths to skip SAR
- clients/ui/bff/internal/api/namespaces_handler.go: core handler of this PR
- clients/ui/bff/internal/api/namespaces_handler_test.go: tests of the handler of this PR
- …
=> feat(bff): list user namespaces in dev mode

clients/ui/bff/README.md, clients/ui/bff/internal/api/app.go, clients/ui/bff/internal/api/middleware.go, clients/ui/bff/internal/api/model_registry_handler.go, clients/ui/bff/internal/api/model_registry_handler_test.go, clients/ui/bff/internal/api/model_versions_handler.go, clients/ui/bff/internal/api/model_versions_handler_test.go, clients/ui/bff/internal/api/namespaces_handler.go, clients/ui/bff/internal/api/registered_models_handler.go, clients/ui/bff/internal/api/registered_models_handler_test.go, clients/ui/bff/internal/api/test_utils.go, clients/ui/bff/internal/integrations/http.go, clients/ui/bff/internal/integrations/k8s.go, clients/ui/bff/internal/mocks/http_mock.go, clients/ui/bff/internal/mocks/k8s_mock.go, clients/ui/bff/internal/mocks/k8s_mock_test.go, clients/ui/bff/internal/repositories/model_registry.go, clients/ui/bff/internal/repositories/model_registry_test.go, clients/ui/bff/internal/repositories/namespace.go
Authorize endpoints based on kubeflow-userid and kubeflow-groups header
This PR sits on top of https://github.com/kubeflow/model-registry/pull/644
Important: **THIS PR makes namespace parameter mandatory**. It will require a FUP PR with frontend by @lucferbux to don't disrupt our develoopment
Authorization is performed using Kubernetes SubjectAccessReview (SAR), which validates user access to resources.
- `kubeflow-userid`: Required header that specifies the user’s email. Access is checked directly for the user via SAR.
- `kubeflow-groups`: Optional header with a comma-separated list of groups. If the user does not have access, SAR checks group permissions using OR logic. If any group has access, the request is authorized.
Access to Model Registry List:
- To list all model registries …
=> feat(bff): authorize endpoints based on kubeflow-userid and kubeflow-groups header

clients/ui/frontend/package-lock.json, clients/ui/frontend/package.json, clients/ui/frontend/src/shared/utilities/markdown.ts
Issue:
```
Type-checking in progress...
ERROR in ./src/shared/utilities/markdown.ts:18:14
TS2339: Property 'setAttribute' does not exist on type 'Node'.
16 |       // nodeType 1 = element type
17 |       if (node.nodeType === 1 && node.nodeName.toLowerCase() === 'a') {
> 18 |         node.setAttribute('rel', 'noopener noreferrer');
|              ^^^^^^^^^^^^
19 |       }
20 |     });
21 |
```
Found 1 error in 3399 ms.
I've also fixed broken dependabot PR: https://github.com/kubeflow/model-registry/pull/652/files
Small sanity check on the app.
- [X ] Code changes follow the [kubeflow contribution …
=> fix(frontend): fixing cve (low severity), build(deps): bump sass from 1.80.6 to 1.83.0,  and also type check

clients/ui/frontend/.env.cypress.mock, clients/ui/frontend/src/app/App.tsx, clients/ui/frontend/src/index.tsx, clients/ui/frontend/src/shared/api/apiUtils.ts, clients/ui/frontend/src/shared/context/DashboardScriptLoader.tsx, clients/ui/frontend/src/shared/context/NamespaceSelectorContext.tsx, clients/ui/frontend/src/shared/hooks/useQueryParamNamespaces.ts
Fix namespace selector in deployment, so it uses the kubeflow namespace selector from
=> Fix namespace selector

clients/ui/bff/Dockerfile, clients/ui/bff/Makefile, clients/ui/bff/cmd/main.go, clients/ui/bff/internal/api/app.go, clients/ui/bff/internal/api/app_test.go, clients/ui/bff/internal/api/middleware.go, clients/ui/bff/internal/api/test_utils.go, clients/ui/bff/internal/config/environment.go, clients/ui/bff/static/index.html, clients/ui/bff/static/sub/test.html
This PR is a preparation for the BFF and FE being served in production on the same container.
At "/" we are now serving static files:
As we used to do, we keep serving the BFF API on "/api/v1/*".
It is important also to highlight that on production (when using binaries), we need to copy the assets to the target containers. I've decided not to pack the static assets in the binary and serve them in the filesystem. I believe this makes it more coherent with our architecture (but I'm open to discussion and suggestions). If you would like more details on this, please look at MakeFile and Docker file changes.
Changes on this PR:
- Dockerfile: copying the static assets during build process and passing the target asset dir as parameter to binary
- Makefile: also added the STATIC_ASSETS_DIR …
=> feat(bff): serving static assets on bff

clients/ui/bff/internal/api/app.go, clients/ui/bff/internal/api/app_test.go
This PR sits on top https://github.com/kubeflow/model-registry/pull/699 and does proper handling of SPA Routes.
In this PR: (specific commit https://github.com/kubeflow/model-registry/commit/a7448dd24dcef51a457127ef141582ad88c992ee)
- app.go: add a fallback if a path does not exist to app.config.StaticAssetsDir/index.html
- app_test.go: test the fallback (we should not get a 404 like before).
In the video, every time the UI blinks, I reload it. Also, pay attention that on /api/v1/something I still keep using our default api 404 page.
https://github.com/user-attachments/assets/de58e81c-13a1-4eac-8e3d-b4c8bcb0bbd0
- 
**Please merge …
=> feat(bff): proper support for SPA routes 

clients/ui/frontend/src/app/App.tsx, clients/ui/frontend/src/shared/style/MUI-theme.scss
To achieve proper page alignment, the `Page` component requires the `sidebar` prop to render the `PageSidebar` component. The `sidebar` component is added to App.tsx and is closed by default.
Before:
After:
Simulate Integrated mode by commenting out instances of `isStandalone()` in App.tsx. 
=> Fix(frontend): Nav and Page Spacing

clients/ui/bff/Makefile, clients/ui/bff/README.md, clients/ui/bff/cmd/main.go, clients/ui/bff/internal/api/app.go, clients/ui/bff/internal/api/healthcheck__handler_test.go, clients/ui/bff/internal/api/healthcheck_handler.go, clients/ui/bff/internal/api/middleware.go, clients/ui/bff/internal/api/model_registry_handler.go, clients/ui/bff/internal/api/model_registry_handler_test.go, clients/ui/bff/internal/api/model_versions_handler.go, clients/ui/bff/internal/api/namespaces_handler.go, clients/ui/bff/internal/api/namespaces_handler_test.go, clients/ui/bff/internal/api/registered_models_handler.go, clients/ui/bff/internal/api/test_utils.go, clients/ui/bff/internal/api/user_handler.go, clients/ui/bff/internal/api/user_handler_test.go, clients/ui/bff/internal/config/environment.go, clients/ui/bff/internal/constants/keys.go, clients/ui/bff/internal/integrations/http.go, clients/ui/bff/internal/integrations/http_helpers.go, clients/ui/bff/internal/integrations/k8s.go, clients/ui/bff/internal/mocks/k8s_mock.go, clients/ui/bff/internal/mocks/k8s_mock_test.go, clients/ui/bff/internal/mocks/static_data_mock.go, clients/ui/bff/internal/repositories/model_registry.go, clients/ui/bff/internal/repositories/model_registry_test.go
Adds several logging related features:
* Ability to change logging verbosity through a cli arg or environment variable
* Adds a unique trace id to all requests via context to link them together
* Adds debug logging for upstream requests / responses with a unique request id   
Note: at some point in the future it would be good to add headers to the logging, however we have to be careful about logging confidential credentials etc, so I've intentionally left that part out for now.
Try this out with a real MR backend deployed to kind and a mock k8s client, e.g.
```make run PORT=4000 MOCK_K8S_CLIENT=true MOCK_MR_CLIENT=false LOG_LEVEL=debug```
Make some GET / POST / PATCH requests (the ones from the README are fine)
Verify you get the debug logging.
Also verify different log levels work, e.g. …
=> Adds ability to change logging verbosity and adds more debug telemetry

README.md
`internal/core/api.go` was moved to `pkg/api/api.go`
(1a7a4138d88267602b4901946e0956b5f1a09d1b), so updating the link.
Fixes #675.
Signed-off-by: Paul Boyd <pboyd@redhat.com>
=> fix: update api.go link in README.md

go.mod, go.sum
Bumping go deps to fix https://osv.dev/vulnerability/GO-2024-3333
`make test`
=> fix: bump go deps to fix GO-2024-3333

clients/ui/bff/Makefile, clients/ui/bff/README.md, clients/ui/bff/cmd/main.go, clients/ui/bff/go.mod, clients/ui/bff/go.sum, clients/ui/bff/internal/api/app.go, clients/ui/bff/internal/api/helpers.go, clients/ui/bff/internal/api/helpers_test.go, clients/ui/bff/internal/api/middleware.go, clients/ui/bff/internal/config/environment.go, clients/ui/bff/internal/constants/keys.go
NOTE: This PR is stacked on top of my logging PR, that will need to be merged first.
Adds W3C standards compliant support for CORS for the BFF
This can be tested by running the BFF in full mock mode as the headers are generated by a middleware that will run in all scenarios. The tests involve merely querying the health check endpoint with a different combination of headers. 
This to note: 
* CORS is only enforced by browsers, so all requests should be successful, the headers returned will vary and the browser will either accept or deny the request based on this.
* When the frontend is served by the BFF, CORS will not be required as it will be served from the same origin - as such the default behaviour is to not return any CORS headers, this disallows cross origin requests and is the most …
=> Adds BFF support for CORS

clients/python/tests/regression_test.py, internal/converter/openapi_reconciler_util.go, internal/server/openapi/api_model_registry_service_service.go
Trying to do a PATCH request to v1alpha3/artifacts/{artifactId} made mr panic:
```shell
http: panic serving 0.0.0.0:8080: runtime error: invalid memory address or nil pointer dereference
goroutine 25997 [running]:
net/http.(*conn).serve.func1()
/usr/lib/golang/src/net/http/server.go:1873 +0xb9
panic({0xb13ba0?, 0x13a8810?})
/usr/lib/golang/src/runtime/panic.go:920 +0x270
github.com/kubeflow/model-registry/internal/server/openapi.(*ModelRegistryServiceAPIService).UpdateArtifact(0xc0003c7c20, {0xb351a0?, 0xc000042190?}, {0xc00029e0ad, 0x1}, {0x0, 0x0})
/workspace/internal/server/openapi/api_model_registry_service_service.go:496 +0x12f
github.com/kubeflow/model-registry/internal/server/openapi.(*ModelRegistryServiceAPIController).UpdateArtifact(0xc000013c98, {0x7fb4fa6124b8, 0xc0001665c0}, …
```
=> fix: patch requests to artifact endpoint make mr panic

clients/ui/bff/README.md, clients/ui/bff/internal/api/app.go, clients/ui/bff/internal/api/artifacts_handler.go, clients/ui/bff/internal/api/artifacts_handler_test.go, clients/ui/bff/internal/api/suite_test.go, clients/ui/bff/internal/api/test_utils.go, clients/ui/bff/internal/mocks/k8s_mock.go, clients/ui/bff/internal/mocks/model_registry_client_mock.go, clients/ui/bff/internal/mocks/static_data_mock.go, clients/ui/bff/internal/mocks/types_mock.go, clients/ui/bff/internal/repositories/artifacts.go, clients/ui/bff/internal/repositories/model_registry_client.go
This PR introduces the endpoints for GET, POST, and PATCH for artifacts.
In this PR:
- clients/ui/bff/README.md: some formating and adding the new API endpoints
- clients/ui/bff/internal/api/app.go: adding the new routes  GET ../artifacts ../artifacts/{id}, POST and PATCH
- clients/ui/bff/internal/api/artifacts_handler.go: handler for the following endpoints
- clients/ui/bff/internal/api/artifacts_handler_test.go: companion test
- clients/ui/bff/internal/api/suite_test.go and clients/ui/bff/internal/api/test_utils.go: code formating
- clients/ui/bff/internal/mocks/k8s_mock.go: redundant error handling
- clients/ui/bff/internal/mocks/model_registry_client_mock.go: simple mocks for when MOCK_MR_CLIENT=true
- clients/ui/bff/internal/mocks/static_data_mock.go: companion mocks
- …
=> feat(bff) crud for api/v1/model_registry/{model_registry_id}/artifacts

clients/ui/frontend/src/app/NavBar.tsx, clients/ui/frontend/src/shared/style/MUI-theme.scss
Edit navbar styling to handle dynamic window sizing.
Adds media query to set proper margin on small viewports.
Tests N/A - styling updates only. 
1. `npm install` and run Model Registry UI. 
To run:
```
cd clients/ui/frontend && npm run start:dev   
```
```
cd clients/ui/bff && make run MOCK_K8S_CLIENT=true MOCK_MR_CLIENT=true
```
2. Resize viewport to test updates.
Current:
https://github.com/user-attachments/assets/83505676-47e9-45ec-83ca-7021cb60a66f
Kubeflow Central UI:
https://github.com/user-attachments/assets/f9166b87-5067-45a7-971b-e835b7e024df
=> fix(nav, masthead): Edit navbar styling to handle dynamic window sizing

clients/ui/Dockerfile, clients/ui/Makefile, clients/ui/scripts/deploy_kind_cluster.sh
Fix small issue with make command that was preventing to catch env variables
Tweak the env variables of `make frontend-build-standalone` and check if they are working
=> Fix issue with make command

clients/ui/frontend/src/shared/components/SimpleSelect.tsx
I got a missing key warning in Dev Mode, so I replaced the <> shorthand for fragments with an explicit <React.Fragment> and a key.
Run the web app in dev mode and also in production mode.
=> fix(frontend): adding missing key for SimpleSelect

clients/ui/frontend/package-lock.json, clients/ui/frontend/package.json
Fixing the PRs that dependabot was not able to automate it:
https://github.com/kubeflow/model-registry/pull/716
https://github.com/kubeflow/model-registry/pull/680
Run the test, and web app in dev and prod mode.
=> chore(frontend): FE version bump for eslint-plugin-react-hooks, typescript-eslint/parser and @typescript-eslint/eslint-plugin

scripts/install_protoc.sh
Upon pulling a fresh copy of the repo and executing `make image/build` the `install_protoc.sh` step fails with the following error/output:
```
docker build . -f Dockerfile -t kubeflow/model-registry:main
[+] Building 54.2s (23/26)                                                     docker:desktop-linux
=> [internal] load build definition from Dockerfile                                           0.0s
=> => transferring dockerfile: 1.86kB                                                         0.0s
=> [internal] load metadata for registry.access.redhat.com/ubi8/ubi-minimal:latest            2.3s
=> [internal] load metadata for registry.access.redhat.com/ubi8/go-toolset:1.22               2.8s
=> [internal] load .dockerignore                                                              0.0s …
```
=> Update install_protoc.sh script to support apple architectures

clients/python/src/model_registry/core.py, clients/python/src/mr_openapi/configuration.py
Exposes the verify_ssl attribute in the Configuration class to be modified when instantiating the class. Set it to "True" by default but update the client's behaviour to override it to False when an insecure connection is attempted.
The same change has been applied locally in order to test https://github.com/opendatahub-io/opendatahub-tests/pull/100 and the insecure connection now works correctly. Without this change, even though the ModelRegistry instance is created with the attribute "is_secure" set to False would fail to connect to the remote endpoint.
=> Update verify_ssl behaviour in Configuration class

.github/workflows/build-image-pr.yml, .github/workflows/csi-test.yml, .github/workflows/python-tests.yml, manifests/kustomize/overlays/db/kustomization.yaml, scripts/deploy_on_kind.sh
* #266
Bumps the version of the MySQL container image in the overlays/db kustomization to 8.0.39 which is multi-arch (amd64 / aarch64)
Deployed to a local `kind` cluster on an apple silicon MacBook, using official instructions to deploy using `kind` on macOS.
*[https://www.kubeflow.org/docs/components/pipelines/legacy-v1/installation/localcluster-deployment/#kind](https://www.kubeflow.org/docs/components/pipelines/legacy-v1/installation/localcluster-deployment/#kind)
*[https://www.kubeflow.org/docs/components/model-registry/installation/#standalone-installation](https://www.kubeflow.org/docs/components/model-registry/installation/#standalone-installation
)
The only variation of above was that I deployed to kind using my branch of the manifest:
```kubectl apply -k …
```
=> Bump mysql container image to one with an aarch64 image

manifests/kustomize/overlays/db/model-registry-db-deployment.yaml
It Looks like the mysql:8.0.3 image version may have been a mistake, and it really should be mysql:8.3.0. I updated the mysql image version from 8.0.3 to 8.3.0 in the manifest file. This resolves three issues:
1. The README suggest version 8.3.0 is being used in some notes near the bottom (see https://github.com/dandawg/model-registry#pull-image-rate-limiting), which is inconsistent with what is in the manifest (8.0.3) as is.
2. The mysql:8.0.3 image results in ImagePullBackoff errors on Kind (at least on Mac). This can also be verified with `docker pull mysql:8.0.3`. 
3. The mysql:8.0.x versions are older (7 years old!) and have more vulnerabilities, so it will be better to use 8.3.0.
Note: this should fix issue #266 
Limited testing on Kind on Mac M2. Once I updated the version, the …
=> fix: mysql version fix 8.0.3 -> 8.3.0

clients/python/Makefile, clients/python/templates/configuration.mustache
Given that the verify_ssl code change was made on generated code, if local users try to run make build, the change gets overwritten and the client fails with this error:
```
TypeError: Configuration.__init__() got an unexpected keyword argument 'verify_ssl'
```
This PR aims to add the change to the configuration file template so that it gets into the autogenerated code.
tested locally both manually and with e2e python tests
=> fix(python): client autogen to include verify_ssl param

pkg/inferenceservice-controller/controller.go, pkg/inferenceservice-controller/controller_test.go, pkg/inferenceservice-controller/suite_test.go, pkg/inferenceservice-controller/testdata/deploy/model-registry-svc.yaml, pkg/inferenceservice-controller/testdata/inferenceservices/inference-service-missing-name.yaml
This PR aims to add backwards compatibility to existing inferenceservices that are missing the new labels/annotations, so the following changes have been made:
- made the name label and URL annotation optional, the reconciler will try to connect to a model registry service in the namespace specified by the label or the default (if missing), if there's more than one MR service it will stop and fail.
- The reconciler will try to get the URL from the service's annotation if it's specified and it's present on the service, if it's missing it will build the URL using the name/namespace/rest-api port.
`make test`
=> feat(isvc): made name and url optional - added support to svc url annotation

clients/ui/frontend/src/app/App.tsx
Update navbar CSS to fix alignment for error screen, see attached images below. Test N/A, visual change only.
Before:
After:
1. Start frontend and backend of Model Registry UI.
Frontend: 
```clients/ui/frontend && npm run start:dev```
Backend:
```clients/ui/bff && make run MOCK_K8S_CLIENT=true MOCK_MR_CLIENT=true```
2.. Stop the backend to force error screen. 
=> fix(frontend): fixes error screen alignment

clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisterModel/RegistrationCommonFormSections.tsx
Fixes URI input field which was misaligned with the radio button, it should be in a new line and should span the full width. This happens in model registration modal.
Before
After
Click "Register Model" in Model Registry list view, and scroll down to "URI" field in the "Modal Location" section. 
- [] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
=> fix(frontend): fixes URI field alignment

clients/ui/frontend/src/shared/style/MUI-theme.scss
In integrated mode, we want to mimic as much as possible other deployments.
Before (Integrated Mode):
Before (Standalone Mode):
After (Standalone Mode):
Target: 
1. Go to Model Registry list view and verify that styling and padding of the page component aligns with integrated mode. 
=> fix(frontend): Remove extra page padding

manifests/kustomize/base/model-registry-deployment.yaml, manifests/kustomize/options/ui/base/model-registry-ui-deployment.yaml, manifests/kustomize/overlays/db/model-registry-db-deployment.yaml, manifests/kustomize/overlays/postgres/kustomization.yaml, manifests/kustomize/overlays/postgres/model-registry-db-deployment.yaml, manifests/kustomize/overlays/postgres/patches/model-registry-deployment.yaml
Set `seccompProfile`, forbid containers to run as root, and disable
unnecessary system calls. This applies to:
- Model registry itself
- Example database (MySQL and PostgreSQL)
- Model registry UI
Fixes #760 
Applying the manifests in a local cluster.
=> feat(manifests): add securityContext to deployments

clients/python/tests/test_client.py
ModelVersion.name can generally account for up to 250chars, assuming up to 10K RegisteredModels. This is because ModelVersion being a MLMD.Context owned entity, its name is prefixed with `RegisteredModel.id:` in the backend to preserve uniqueness for MLMD schema constraints
`make test-e2e`
- [no changes, just tests] The developer has manually tested the changes and verified that the changes work.
=> test: E2E pytest for ModelVersion.name length

.github/workflows/build-and-push-ui-images.yml, clients/ui/Makefile, clients/ui/scripts/deploy_kubeflow_cluster.sh, manifests/kustomize/README.md, manifests/kustomize/options/ui/overlays/istio/kustomization.yaml
Prepare kubeflow manifests for release adding a kubeflow manifest and allowing tagging in images
**Note: I still need to test the tag in my local environment**
Test deployment just following the instructions
=> Prepare kubeflow manifest for release

clients/python/README.md
When doing a fresh install of the python client for local development, I ran into an issue where dependencies would install, but there would be a bunch of unformatted files in my git working directory. After some checking it appears after a `make install` you need to run `make tidy` to format everything. This is already encapsulated in the `Makefile` as `all: install tidy`, so all thats actually needed is to just run `make`.
This updates the README.md to clarify this point
=> docs: clarify python client installation steps

api/openapi/model-registry.yaml, clients/python/src/mr_openapi/api/model_registry_service_api.py, pkg/api/error.go, pkg/core/artifact_test.go, pkg/core/inference_service_test.go, pkg/core/model_version_test.go, pkg/core/registered_model_test.go, pkg/core/serve_model_test.go, pkg/core/serving_environment_test.go, pkg/openapi/api_model_registry_service.go
Small change to return a 400 error if a user attempts to add a duplicate value. Previously, this was defaulting to a 500 internal service error which is not appropriate. 
https://issues.redhat.com/browse/RHOAIENG-19196
Locally reproduced this error to confirm that the resp status is 400 instead of 500.
=> change resp status from 500 to 409 for dup POST reqs

clients/ui/frontend/src/shared/style/MUI-theme.scss
Removes additional padding that is currently rendered with integrated mode. Also fixes breadcrumb issue in standalone mode. 
Padding (Integrated Mode):
Before:
After:
Breadcrumb (Standalone mode):
Before:
After:
To test updated padding in Integrated mode:
1. In App.tsx replaces lines 113 - 126 with:
```
masthead={
// isStandalone() ? (
//   <NavBar
//     username={username}
//     onLogout={() => {
//       logout().then(() => window.location.reload());
//     }}
//   />
// ) : (
''
// )
}
// isManagedSidebar={isStandalone()}
// sidebar={isStandalone() ? <NavSidebar /> : sidebar}
sidebar={sidebar}
```
2.  Verify additional padding has been removed. 
- All the commits have been [_signed-off_](https://github.com/kubeflow/community/tree/master/dco-signoff-hook#signing-off-commits)  (To pass …
=> fix(frontend): Update padding to fix upstream spacing

clients/ui/frontend/src/__tests__/cypress/cypress/support/commands/api.ts
Recent changes to the standalone UI were made to update all API requests to `/model-registry/api`. However the cypress tests were still intercepting `/api`. This fix simple updates the `interceptApi` function to prepend the new prefix. 
Not sure why the original PR did not run the tests. That will be looked at separately.
In the `clients/ui/frontend` dir:
- `npm run cypress:server:build`
- `npm run cypress:server`
- `npm run cypress:run:mock`
=> [UI] update path for all cypress interceptApi calls

clients/ui/frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelRegistry.cy.ts, clients/ui/frontend/src/app/pages/modelRegistry/ModelRegistryCoreLoader.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelRegistrySelector.tsx, clients/ui/frontend/src/shared/components/KubeflowDocs.tsx
Tweak UI to point at MR installation for empty views.
=> Tweak UI to point at MR installation

OWNERS
I'm happy to sponsor @Al-Pragliola into Reviewer role, following the current [Kubeflow community process](https://github.com/kubeflow/website/blob/816df01d87f31b462c13aabec4cc235e18f660bf/content/en/docs/about/membership.md?plain=1#L81).
- Alessio [achieved membership on Nov 26th](https://github.com/kubeflow/internal-acls/pull/722#event-15437602206), today is Feb 26th, 3 months ✅ 
- https://github.com/kubeflow/model-registry/pull/796#pullrequestreview-2612259993
- https://github.com/kubeflow/model-registry/pull/790#pullrequestreview-2611917842
- https://github.com/kubeflow/model-registry/pull/769#pullrequestreview-2599812855
- https://github.com/kubeflow/model-registry/pull/741#issuecomment-2619891138
- https://github.com/kubeflow/model-registry/pull/731#pullrequestreview-2572433196
- …
=> process: add Al-Pragliola as top level Reviewer

clients/ui/bff/internal/integrations/http.go, clients/ui/bff/internal/integrations/http_test.go
HTTP Get operations from BFF were not forwarding errors correctly.
In this PR:
- clients/ui/bff/internal/integrations/http.go: generated proper error object when there is an error with get operation
- clients/ui/bff/internal/integrations/http_test.go: test coverage for http.go
1-) Run model registry with docker compose -f docker-compose.yaml up
2-) Run BFF with make run MOCK_K8S_CLIENT=true MOCK_MR_CLIENT=false
3-) After this PR, we should:
```code
curl -i -H "kubeflow-userid: user@example.com" "localhost:4000/api/v1/model_registry/model-registry-bella/registered_models?namespace=bella-namespace"
HTTP/1.1 200 OK
Content-Type: application/json
Date: Wed, 26 Feb 2025 22:20:18 GMT
Transfer-Encoding: chunked 
````
If we manually stop mlmd-server from Model Registry (forcing them return a …
=> fix(bff): correctly forward errors from MR API on Get operations

pkg/api/error.go, pkg/core/artifact_test.go, pkg/core/inference_service_test.go, pkg/core/model_version_test.go, pkg/core/registered_model_test.go, pkg/core/serving_environment_test.go
Currently, when an user inputs a request with a query param that has an invalid syntax issue, it gets processed as a 500 internal service error. We should be processing these as a 400 bad request instead.
Link to original Jira with more details: https://issues.redhat.com/browse/RHOAIENG-19195 
This has been locally tested by creating new registered models and model artifacts, and then sending GET requests with bad query params for name and externalId in order to trigger the "Illegal syntax" error. For example: 
`GET /api/model_registry/v1alpha3/registered_model?%C3%B5%F1%A5%BC%A2x%1D%1C&externalId=1l%26%F3%AF%81%9Fd%F0%96%B0%AD%5C-%10%C3%AD%09%C3%BD%F3%BF%B9%B0%C2%98%C3%8B%C3%A7%F0%BF%BD%A4%3D%C2%BB%C2%B0%C3%AF`
- All the commits have been …
=> handle GET reqs with invalid query params as 400

clients/python/README.md, clients/python/poetry.lock, clients/python/pyproject.toml, clients/python/src/model_registry/_client.py, clients/python/src/model_registry/utils.py, clients/python/tests/.gitignore, clients/python/tests/conftest.py, clients/python/tests/test_client.py, clients/python/tests/test_utils.py
Adds a convenience method to perform a common operation within the python client, to both upload and register a model that exists locally on the filesystem.
=> Add `upload_artifact_and_register_model` method to python client

api/openapi/model-registry.yaml, clients/python/src/model_registry/_client.py, clients/python/src/model_registry/types/artifacts.py, clients/python/src/mr_openapi/models/model_artifact.py, clients/python/src/mr_openapi/models/model_artifact_create.py, clients/python/src/mr_openapi/models/model_artifact_update.py, clients/python/tests/test_core.py, docs/logical_model.md, internal/converter/generated/mlmd_openapi_converter.gen.go, internal/converter/generated/openapi_converter.gen.go, internal/converter/generated/openapi_reconciler.gen.go, internal/converter/mlmd_converter_util_test.go, internal/converter/mlmd_openapi_converter.go, internal/converter/mlmd_openapi_converter_util.go, internal/converter/openapi_converter.go, internal/converter/openapi_mlmd_converter_util.go, internal/mlmdtypes/mlmdtypes.go, pkg/core/core_test.go, pkg/openapi/model_model_artifact.go, pkg/openapi/model_model_artifact_create.go, pkg/openapi/model_model_artifact_update.go
Add the following model source properties to store metadata about origin of a model artifact
ModelSourceKind
ModelSourceClass
ModelSourceGroup
ModelSourceId
ModelSourceName
Note that these properties are used to reference an external source where a model artifact was created.
A fuller lineage model for tracking ML `Experiments` and `Runs` will be added in the future as model registry API resource types. 
These properties also support referencing arbitrary model artifact sources, without constraining it to ML models only. 
Fixes RHOAIENG-19885
Added new model source properties to existing unit tests for model artifacts in backend service as well as Python client API and tests. 
- All the commits have been [_signed-off_](https://github.com/kubeflow/community/tree/master/dco-signoff-hook#sign …
=> feat: add model source properties to store metadata about origin of a model artifact, fixes RHOAIENG-19885

clients/ui/frontend/src/app/pages/settings/DeleteModelRegistryModal.tsx, clients/ui/frontend/src/app/pages/settings/ModelRegistriesTable.tsx, clients/ui/frontend/src/app/pages/settings/ModelRegistrySettings.tsx
- Ports the remaining component used within the Model Registries list view: `DeleteModelRegistryModal.tsx`.
- Other components related to Model Registries admin setting list view have been migrated.
- See https://github.com/kubeflow/model-registry/tree/main/clients/ui/frontend/src/app/pages/settings.
- Components related to "Create" functionality for Model Registries have been added as part of kubeflow/model-registry/pull/852.
See full list here: https://github.com/opendatahub-io/odh-dashboard/tree/main/frontend/src/pages/modelRegistrySettings
Before:
After:
1. In `ModelRegistriesTableRow.tsx`, comment out the conditional expression for [isPlatformDefault()](https://github.com/kubeflow/model-registry/compare/main...jenny-s51:port-admin-list-view?expand=1#diff-2802868d8778078fa04cd2591e8f22 …
=> feat(frontend): port DeleteModelRegistry modal

clients/ui/bff/internal/api/app.go, clients/ui/bff/internal/api/middleware.go, clients/ui/bff/internal/api/model_registry_handler.go, clients/ui/bff/internal/api/model_registry_handler_test.go, clients/ui/bff/internal/api/model_registry_settings_handler.go, clients/ui/bff/internal/mocks/k8s_mock.go, clients/ui/bff/internal/models/model_registry.go, clients/ui/bff/internal/models/model_registry_kind.go, clients/ui/bff/internal/repositories/model_registry.go, clients/ui/bff/internal/repositories/model_registry_test.go
This PR creates a stub implementation of APIs for CRUD on Model Registries settings. The endpoints are only exposed if app.config.StandaloneMode=true.
```code
curl -i -H "kubeflow-userid: user@example.com" "localhost:4000/api/v1/settings/model_registry?namespace=kubeflow"
HTTP/1.1 200 OK
Content-Type: application/json
Date: Mon, 10 Mar 2025 19:42:57 GMT
Transfer-Encoding: chunked
{
"data": [
{
"apiVersion": "modelregistry.io/v1alpha1",
"kind": "ModelRegistry",
"metadata": {
"name": "model-registry",
"namespace": "kubeflow",
"creationTimestamp": "2024-03-14T08:01:42Z"
},
...
},
{
"apiVersion": "modelregistry.io/v1alpha1",
"kind": "ModelRegistry",
"metadata": {
"name": "model-registry-dora",
"namespace": "kubeflow",
"creationTimestamp": "2024-03-14T08:01:42Z"
},
"spec": {
...
},
{ …
```
=> feat(bff): Stub endpoints for CRUD Model Registries

manifests/kustomize/base/model-registry-deployment.yaml, manifests/kustomize/overlays/db/model-registry-db-deployment.yaml, manifests/kustomize/overlays/postgres/model-registry-db-deployment.yaml
This PR fixes Istio sidecar injection configuration in the Model Registry component by replacing deprecated annotations with the recommended labels approach. According to Istio documentation, controlling sidecar injection via annotations is no longer the preferred method.
The changes move `sidecar.istio.io/inject` from annotations to labels in:
- Base model-registry deployment
- DB overlay deployment
- Postgres overlay deployment
The changes maintain the same injection behavior but use the correct approach. These changes have been validated by deploying in a local Kubeflow environment with Istio and confirming proper sidecar injection behavior.
Issue: https://github.com/kubeflow/manifests/issues/2798
Part of PR: https://github.com/kubeflow/manifests/pull/3044
=> Fix Istio sidecar injection by moving from annotations to labels

Makefile
following up to https://github.com/kubeflow/model-registry/pull/899 we need this Makefile change thanks @Al-Pragliola for the findings
testing via GHA as this is a target invoked by GHA
=> build: fix Makefile following GHCR image rename

devenv/Tiltfile, devenv/configs/tiltfiles/frontend.tiltfile
This PR aims to fix the devenv container images override by updating the existing ones to ghcr.io
run devenv locally
=> fix(devenv): switch overridden images to ghcr.io

clients/ui/frontend/src/shared/context/NamespaceSelectorContext.tsx, clients/ui/frontend/src/shared/context/__tests__/NamespaceSelectorContext.test.tsx
Sorts the namespaces by name so that the namespace selector options are in alphabetical order.
This makes for a better experience when running the standalone app with a user who has access to many namespaces.
Modified unit test to return namespaces out of order. 
The existing tests assert alphabetical order already.
=> fix(frontend): sort namespaces by name for the namespace selector

internal/converter/mlmd_openapi_converter_util.go, internal/converter/openapi_mlmd_converter_util.go, pkg/api/error.go, pkg/core/registered_model_test.go
We currently return a 500 error if a user requests to register a model with a customProperties field that does not include a metadataType parameter. This is required **conditionally** since customProperties is an optional field. 
We need to return a 400 bad request if a user attempts to pass a malformed customProperties parameter and give a more informed error message. 
Linked Jira: https://issues.redhat.com/browse/RHOAIENG-19192
Locally tested using the following request:
`curl -v -X POST \
-H 'Authorization: [Filtered]' \
-H 'Content-Type: application/json' -d \
'{"name": "Name4","customProperties": {"additionalProp1": {"metadataType": "MetadataStringValue", "string_value": "teststr"}}}' \
--insecure http://localhost:8080/api/model_registry/v1alpha3/registered_models`
- All the commits …
=> 500 custom prop type

manifests/kustomize/README.md
Revamp docs for Kubeflow UI installation and installing MR in Profiles.
=> Revamp profile installation instructions for MR

.github/workflows/check-openapi-spec-pr.yaml, Makefile, api/openapi/model-registry.yaml
Sort the keys in the `paths`, `schemas` and `responses` objects in the OpenAPI spec for easier browsing. Also automating this step and verifying that the keys remain sorted with a github action.
- [Verified the output in the swagger editor](https://editor.swagger.io/?url=https://raw.githubusercontent.com/pboyd/model-registry/refs/heads/sort-openapi-schemas/api/openapi/model-registry.yaml)
- Manually tested the Makfile changes
=> chore(openapi): sort keys for easier browsing

Makefile, clients/python/Makefile
This merge request updates the image/build target in the Makefile to include the --load flag when building Docker images. This change ensures compatibility with Podman (desktop) and allows locally built images to be loaded into the Docker image store, enabling seamless deployment to Kind clusters during local development.
Issue description: https://github.com/kubeflow/model-registry/issues/766
Local Testing with Docker:
- Ran make image/build to verify that the image builds successfully and is loaded into the local Docker image store.
- Verified the built image using docker images.
- Deployed the image to a Kind cluster using make deploy-latest-mr.
- 
- All the commits have been [_signed-off_](https://github.com/kubeflow/community/tree/master/dco-signoff-hook#signing-off-commits)  (To …
=> Add --load flag to Docker build command in Makefile

.github/workflows/build.yml, Dockerfile, Dockerfile.odh, README.md, cmd/csi/Dockerfile.csi, docs/mr_go_library.md, go.mod
Upgrade to Go 1.23 now that [ubi8/go-toolset](https://catalog.redhat.com/software/containers/ubi8/go-toolset/5ce8713aac3db925c03774d1) image is available.
Verified that the code compiled.
=> chore: upgrade to Go 1.23

clients/ui/frontend/.env, clients/ui/frontend/docs/env-variables.md, clients/ui/frontend/src/shared/hooks/useNamespaces.ts, clients/ui/frontend/src/shared/hooks/useSettings.tsx, clients/ui/frontend/src/shared/utilities/const.ts, devenv/configs/tiltfiles/frontend.tiltfile
This pull request includes changes to update the environment variable for the username from `USERNAME` to `KUBEFLOW_USERNAME` across multiple files in the frontend client. The most important changes include updates to environment variables, documentation, and hooks.
=> Change USERNAME env to KUBEFLOW_USERNAME

Makefile, cmd/proxy.go, cmd/root.go, internal/server/openapi/routers.go, pkg/inferenceservice-controller/suite_test.go, templates/go-server/routers.mustache
`make build` is not working at the moment with go 1.24
I fixed this error by bumping our golangci-lint version to 2.0.2 and fixing subsequent lint issues
**NOTE**: to try this PR locally remember to clean your bin folder
run `make build` locally after bumping local golang version to v1.24.2
=> fix(proxy): compatibility with 1.24 bump golangci-lint

api/openapi/model-registry.yaml, clients/python/src/mr_openapi/api/model_registry_service_api.py, pkg/openapi/api_model_registry_service.go
I am not entirely sure if this is right, but currently https://github.com/opendatahub-io/opendatahub-tests/blob/main/tests/model_registry/test_rest_api_stateful.py#L29 is failing with error `hypothesis.errors.FlakyStrategyDefinition: Inconsistent data generation! Data generation behaved differently between different runs. Is your data generation depending on external state?` against post calls like these 
```
2025-04-14T13:19:06.307640 tests.model_registry.conftest INFO POST /api/model_registry/v1alpha3/serving_environments -> 409
FAILED
```
```
2025-04-14T13:12:44.818530 tests.model_registry.conftest INFO POST /api/model_registry/v1alpha3/registered_models -> 409
FAILED
```
- All the commits have been [_signed-off_](https://github.com/kubeflow/community/tree/master/dco-signoff-hook#signin …
=> Add 409 for post calls, without it stateful api T2 tests are failing intermittently

Dockerfile, clients/python/Makefile, scripts/deploy_on_kind.sh
Refactor of the mr Dockerfile, now there's a common stage that prepares the data, a dev-build stage that skips all the autogen/lint/vet and just builds the binary, and the normal stage that is built by default if no `--target` is specified, this greatly improves the build times when testing locally.
To take advantage of this new feature, you can use the `ARGS="--target dev-build"` when running the make image/build target, or use the `DEV_BUILD=true` when running the make test-e2e target in the clients/python folder.
I also increased the timeout when waiting for the mr deployment in the deploy_on_kind.sh script, as it occasionally failed and gave false negatives.
```shell
time make image/build .
...
real    2m41.152s
user    9m18.038s
sys     2m10.551s
```
vs
```shell
time ARGS="--target …
```
=> feat: improve dev QoL

.github/workflows/python-tests.yml, clients/python/.gitignore, clients/python/Makefile, scripts/deploy_local_kind_registry.sh
In the current setup with e2e tests, if you run the test suite twice in a row, you may get an unexpected failure due to port-forwards still persisting between test runs. This reduces iteration speed significantly as you will have to run the test suite for a 3rd time for everything to work again.
The solution I chose was to store the PIDs of the port-forward processes in a file, and after the test suite finishes executing to `kill` those PIDs.
Here is an example of the file produced (`.port-forwards.pid`)
```
46026
46036
46057
```
These pids are for portforward processes for the MR itself, Minio, and the in-Kind Docker Registry.
A key requirement is that even if the test suite fails, the PIDs are still cleaned up.
To facilitate this, I spilt the `test-e2e` target into two, a "run" and a …
=> Clean up port forwards after tests run

cmd/csi/GET_STARTED.md, cmd/csi/samples/modelregistry.clusterstoragecontainer.yaml, manifests/kustomize/options/controller/manager/manager.yaml, manifests/kustomize/options/csi/clusterstoragecontainer.yaml, manifests/kustomize/options/ui/base/model-registry-ui-deployment.yaml, test/csi/e2e_test.sh
CPU limits are largely unnecessary because pods are guaranteed their CPU request, and unused CPU time on the node might as well go to bursting pods.
=> chore(manifests): remove CPU limits

clients/python/src/model_registry/_client.py, clients/python/tests/test_client.py
closes https://github.com/kubeflow/model-registry/issues/935
Check if model + version exists before storing (overriding) existing models in place, throw an error that model is already registered without having a drift case when the new model is stored but the model + version artifact already exists. 
**-> From the issue**
**To Reproduce**
Steps to reproduce the behavior:
```
s3 = S3Params(bucket_name="models", s3_prefix="my_models/")
registry.upload_artifact_and_register_model(name="mnist", model_files_path="models/", version="v3", upload_params=s3, model_format_version="v1", model_format_name="onnx", storage_path="test")
registry.upload_artifact_and_register_model(name="mnist", model_files_path="models/", version="v3", upload_params=s3, model_format_version="v1", …
```
=> fix(client): Prevent model overwrite on duplicate registration

internal/server/openapi/api_model_registry_service_service.go
I'm cleaning up these TODOs for now as I do not believe that they are super useful. We do need to setup a system for role based authorization that will eventually be applied to these routes. Since that is a decent sized lift, I don't think that it is necessary to bloat the service with comments right now. Additionally, as new functionality is added and we don't want to have to keep adding TODOs.
=> remove todo 401

clients/ui/api/openapi/mod-arch.yaml, clients/ui/bff/internal/api/app.go, clients/ui/bff/internal/api/model_registry_settings_handler.go, clients/ui/bff/internal/api/model_registry_settings_rbac_handler.go, clients/ui/bff/internal/models/model_registry_settings_types.go, clients/ui/bff/internal/models/rbac_types.go
This pull request includes several changes to the `model-registry/clients/ui` project, focusing on adding new endpoints for model registry settings, certificates, and role bindings, and updating relevant handlers and models. The most important changes include the addition of GitHub Copilot instructions, new constants and endpoints in the Go backend, and updates to the model registry settings handler.
Backend updates:
* [`clients/ui/bff/internal/api/app.go`](diffhunk://#diff-3fabc91970bb3d088ae86035e9998bf9af2c2314adfc72a58e175952328b7888R38-R42): Added new constants for certificates and role bindings paths, and updated the `Routes` function to include new endpoints for certificates and role bindings. [[1]](diffhunk://#diff-3fabc91970bb3d088ae86035e9998bf9af2c2314adfc72a58e175952328b7888R38 …
=> Add STUB endpoints for settings RBAC

clients/python/Makefile
Sometimes if you are on a fresh env or decide not to use the `devenv` you might not have the extras installed for the python-client when executing the E2E tests.
This PR just adds a quick line to ensure all the extras are installed when running the E2E tests. Impact on runtime is quite minimal.
Locally
=> chore(python-client): ensure extras install when running e2e tests

.github/workflows/build-image-ui-pr.yml, .github/workflows/check-openapi-spec-pr.yaml, .github/workflows/controller-test.yml, .github/workflows/csi-test.yml, .github/workflows/ui-bff-build.yml, .github/workflows/ui-frontend-build.yml
to test the Dependabot/Renovate changes to GHA
are fully tested, we must ensure the path is explicitly included for 'on.pull_request.path' does include
in scope also the GHAs themselves.
Resolves #949
can't be tested locally being GHA-oriented trigger, so using this PR for testing
=> gha: when 'on.pull_request.path' include workflows

clients/python/tests/test_client.py, test/robot/UserStory.robot
tested locally using `make test-e2e-run`
```
PASSED tests/test_client.py::test_register_model_with_owner
...
69 passed, 1 xfailed, 45 warnings in 34.32s
```
=> Migrate robot test validating ability to store owner, to pytest

clients/python/tests/conftest.py
Add pytest_report_teststatus, for clear information about test results in console.
=> add pytest_report_teststatus to print results

pkg/inferenceservice-controller/controller.go, pkg/inferenceservice-controller/controller_test.go, pkg/inferenceservice-controller/suite_test.go
needs #917 
In this PR, I have added a new field to the InferenceService customProperties, which is the 'url' field.
This field is used to reconcile the url from the status of the cluster InferenceService, and update the url in the customProperties.
Also, I have also added new unit tests to test the new functionality.
*Why a customProperty and not a first class field?*
Because the url is part of the InferenceService status, and not the spec so it is ephemeral and should be treated as such in my opinion.
```shell
make test
```
And also, I have created a mock controller that periodically updates the URL in the InferenceService status, and the URL in the customProperties is updated accordingly.
```go
package controllers
import (
"context"
"fmt"
"time"
kservev1beta1 …
```
=> feat(controller): added reconciliation of inferenceservice url

ADOPTERS.md
Adding Red Hat as one of the adopters of the Model Registry
not applicable
=> Adding Red hat as one of the adopters of Kubeflow Model Registry

clients/ui/bff/internal/api/errors.go, clients/ui/bff/internal/api/middleware.go
This PR is a fup for #918. It prevents information disclosure about internal security mechanisms
- Modified the `forbiddenResponse` function to return a generic error message instead of specific access control details
- Changed the default forbiddenResponse to Access forbidden" 
```
curl -i -H "kubeflow-userid: usfsdfdser@example.com" "localhost:4000/api/v1/model_registry?namespace=kubeflow"                           (kind-kubeflow/default)
\HTTP/1.1 403 Forbidden
Content-Type: application/json
Date: Wed, 07 May 2025 14:39:22 GMT
Content-Length: 68
{
"error": {
"code": "403",
"message": "Access forbidden"
}
}
```
On server log:
```
time=2025-05-07T10:52:00.981-04:00 level=WARN msg="access denied" user=usfsdfdser@example.com verb=get resource=services namespace=kubeflow …
```
=> chore(bff): cleanup as a fup to #918

clients/ui/bff/.gitignore, clients/ui/bff/.vscode/launch.json, clients/ui/bff/.vscode/tasks.json, clients/ui/bff/Makefile
As more people move to VS Code and Cursor, this PR introduces debug support on BFF.
=> chore(bff): adding vscode/cursor debug capabilities on bff

clients/python/README.md, clients/python/tests/test_client.py, test/robot/UserStory.robot
Moving `As a MLOps engineer I want to track a Model from an S3 bucket Data Connection` robot TC to pytest.
Updated the troubleshooting section of the README to include a couple issues I encountered on MacOS with running `make test-e2e`
Ran `make test-e2e`, all tests pass when running from my IDE (VSC)
Somehow, when running the same command from my terminal, I get a single failure on test `test_create_tagged_version`
```
ValueError: Newline or carriage return detected in headers. Potential header injection attack.
```
Unsure how it will behave here in CI, but it's a test that hasn't been touched in a long time.
=> Move robot TC to pytest

clients/python/src/model_registry/types/contexts.py, clients/python/tests/types/test_context.py
When the MR py client is used to return information after registering a model (RegisteredModel) or ModelVersion, for example following [the tutorial](https://model-registry.readthedocs.io/en/latest/#basic-usage), we experienced that some users get confused by the "ID" which is internal to the backend (DB) for the actual name of the version.
To mitigate this confusion, it is proposed to change the str representation and bring "name" to the front, so to make it easier to recognize. This also avoids any d/s to consume this str representation in any specific order, which is not part of the contract.
Acceptance Criteria
Given I have a RegisteredModel or ModelVersion instance, When I print it out to be logged, Then the "name" attribute is presented first.
unit tests have been provided as part …
=> py: change str repr to mitigate confusion

manifests/kustomize/base/model-registry-deployment.yaml, manifests/kustomize/overlays/db/kustomization.yaml, manifests/kustomize/overlays/db/patches/model-registry-deployment.yaml, manifests/kustomize/overlays/postgres/kustomization.yaml, manifests/kustomize/overlays/postgres/patches/model-registry-deployment.yaml
As part of https://github.com/kubeflow/manifests/issues/2991, we need to fix up kustomize warnings in upstream. This MR does the same.
The rendered yamls after fixing warnings have been compared before and after the change to find out any deviations. Currently there aren't any see snapshot for details
No UI Changes
=> sorted out kustomize warnings in overlays/db and overlays/postgres

manifests/kustomize/README.md, manifests/kustomize/options/istio/kustomization.yaml, manifests/kustomize/overlays/db/kustomization.yaml, manifests/kustomize/overlays/postgres/kustomization.yaml, scripts/deploy_on_kind.sh
Remove `namespace: kubeflow` from the core model registry manifests.
Fixes #1045
Tested with a local kind cluster.
=> chore(manifests): remove default namespace

manifests/kustomize/overlays/db/kustomization.yaml, manifests/kustomize/overlays/db/model-registry-db-deployment.yaml
Looks like:
- https://github.com/kubeflow/model-registry/pull/703#issuecomment-2631972417
was merged few minutes after the agreed merge of:
- https://github.com/kubeflow/model-registry/pull/267#pullrequestreview-2590899049
this provide the required kustomize alignments
=> manifests: align mysql image version between #267 and #703

clients/ui/bff/internal/api/app.go, clients/ui/bff/internal/api/model_registry_settings_groups_handler.go, clients/ui/bff/internal/api/model_registry_settings_groups_handler_test.go, clients/ui/bff/internal/integrations/kubernetes/client.go, clients/ui/bff/internal/integrations/kubernetes/k8mocks/internal_k8s_client_mock.go, clients/ui/bff/internal/integrations/kubernetes/k8mocks/token_k8s_client_mock.go, clients/ui/bff/internal/integrations/kubernetes/shared_k8s_client.go, clients/ui/bff/internal/models/groups.go, clients/ui/bff/internal/repositories/model_registry_settings.go, clients/ui/bff/internal/repositories/model_registry_settings_test.go, clients/ui/bff/internal/repositories/repositories.go
This PR introduces a new stub endpoint to support listing user groups via the BFF. The purpose of this PR is to unblock frontend development for the group list on the model registry settings screens until we, as a community, decide how we are going to automate the creation of model registries. 
- GET /api/v1/settings/groups – returns a hardcoded list of group names (stub implementation).
- ModelRegistrySettingsRepository.GetGroups() to encapsulate group listing logic.
- GroupModel struct for consistent API response modeling.
- Unit tests for both the repository and handler using Ginkgo/Gomega.
- Mocks in both InternalKubernetesClientMock and TokenKubernetesClientMock to simulate group responses.
- Route registered only in StandaloneMode.
```
curl -i -H "kubeflow-userid: user@example.com" …
```
=> feat(bff): Add group stub (mocked) listing for settings endpoint

clients/python/Makefile, scripts/undeploy_local_registry.sh, scripts/undeploy_minio.sh
=> py: add options to cleanup local registry and minio set up for e2e tests

clients/ui/api/openapi/mod-arch.yaml, clients/ui/bff/internal/api/app.go, clients/ui/bff/internal/api/model_registry_settings_rbac_handler.go, clients/ui/bff/internal/api/model_registry_settings_rbac_handler_test.go
This pull request introduces a new PATCH endpoint for updating Role Bindings in the Model Registry settings, along with its handler implementation and corresponding tests. Additionally, it refactors the existing Role Binding creation logic to improve data handling.
* Added a PATCH endpoint (`PATCH /api/v1/settings/role_bindings/{roleBindingName}`) to update Role Bindings in the OpenAPI specification. The endpoint includes request body validation, response definitions, and operation metadata.
* Updated the router in `app.go` to register the new PATCH endpoint and link it to the `PatchRoleBindingHandler`.
* Implemented the `PatchRoleBindingHandler` in `model_registry_settings_rbac_handler.go` as a stub, handling input validation, name assignment, and returning a patched response.
* Modified …
=> Add rolebinding PATCH for bff

cmd/proxy.go, go.mod, internal/core/test_utils.go, internal/datastore/embedmd/mysql/connect.go, internal/datastore/embedmd/mysql/connect_test.go, internal/datastore/embedmd/mysql/migrate_test.go, internal/datastore/embedmd/service.go, internal/db/connector.go, internal/db/service/registered_model_test.go, internal/proxy/readiness.go, internal/proxy/readiness_test.go, internal/tls/config.go, internal/tls/config_test.go
closes #1019 
This PR adds comprehensive SSL/TLS support for connecting to secured MySQL databases in the embedded metadata store. The implementation includes new command-line flags, a dedicated TLS configuration package, and extensive testing.
**Changes Made**
_New Command-Line Flags_
Added the following flags to support SSL/TLS database connections:
- --embedmd-database-ssl-cert - Path to client SSL certificate file
- --embedmd-database-ssl-key - Path to client SSL private key file
- --embedmd-database-ssl-root-cert - Path to SSL root certificate file
- --embedmd-database-ssl-ca - Path to SSL CA certificate file
- --embedmd-database-ssl-cipher - Colon-separated list of SSL cipher suites
- --embedmd-database-ssl-verify-server-cert - Enable SSL server certificate verification
_New TLS …
=> feat: Add SSL/TLS Support for EmbedMD

cmd/proxy.go, internal/datastore/embedmd/mysql/migrate.go
Adding ALERT tag to ds connection error in order to handle these errors easier downstream/ elsewhere when reading pod logs.
=> add ALERT to ds connection err

internal/datastore/embedmd/mysql/connect.go
This PR reintroduces backoff retries when connecting to the DB as model registry did when trying to connect to MLMD before in #700 
tested on a local cluster with db replicas = 0 and with db in dirty state
=> feat: reintroduce retries when connecting to the db

manifests/kustomize/overlays/db/model-registry-db-deployment.yaml, manifests/kustomize/overlays/postgres/model-registry-db-deployment.yaml
Fixes #1251
The issue came up when using Longhorn and I was able to reproduce it using k3s with Longhorn (it's likely that other provisioners have this problem too). Verified that the problem does not exist after this change, and that our normal Kind test environments still work.
=> fix(manifests): add fsGroup to database deployments

internal/datastore/embedmd/mysql/connect.go
This PR addresses a bug where if the mysql DNS doesn't have a query param character `?`, it incorrectly appends `&tls=custom` which makes the DNS string invalid as it should be `?tls=custom`
tested locally with both 
`- --embedmd-database-dsn=$(MYSQL_USER_NAME):$(MYSQL_ROOT_PASSWORD)@tcp(model-registry-db:$(MYSQL_PORT))/$(MYSQL_DATABASE)?charset=utf8mb4&parseTime=True&loc=Local&tls=custom`
and
`- --embedmd-database-dsn=$(MYSQL_USER_NAME):$(MYSQL_ROOT_PASSWORD)@tcp(model-registry-db:$(MYSQL_PORT))/$(MYSQL_DATABASE)`
=> fix: prevent dsn format bugs when adding tls mode in mysql

catalog/internal/catalog/catalog.go, catalog/internal/catalog/catalog_test.go, catalog/internal/catalog/monitor.go, catalog/internal/catalog/monitor_test.go, catalog/internal/catalog/yaml_catalog.go, catalog/internal/server/openapi/api_model_catalog_service_service.go, catalog/internal/server/openapi/api_model_catalog_service_service_test.go, go.mod
Reload sources and static catalogs after changes are made to the files they were loaded from.
Local kind cluster and unit tests.
=> feat(catalog): reload sources and static catalogs

clients/ui/frontend/src/app/pages/settings/roleBinding/RoleBindingPermissions.tsx, clients/ui/frontend/src/app/pages/settings/roleBinding/RoleBindingPermissionsNameInput.tsx, clients/ui/frontend/src/app/pages/settings/roleBinding/RoleBindingPermissionsTable.tsx, clients/ui/frontend/src/app/pages/settings/roleBinding/RoleBindingPermissionsTableRow.tsx, clients/ui/frontend/src/app/pages/settings/roleBinding/RoleBindingPermissionsTableSection.tsx, clients/ui/frontend/src/app/pages/settings/roleBinding/utils.ts, clients/ui/frontend/src/app/shared/components/types.ts
This is a followup PR to https://github.com/kubeflow/model-registry/pull/1183 - based on this comment [here](https://github.com/kubeflow/model-registry/pull/1210#discussion_r2158839033)
This PR adds missing logic related to project permissions tab.
Once we have the Project context upstream -  Project permissions tab should work as expected
=> Add rolebinding to manage permissions-project tab

internal/datastore/embedmd/mysql/connect.go, internal/datastore/embedmd/postgres/connect.go, internal/datastore/embedmd/service.go, internal/db/connector.go, internal/proxy/readiness.go, internal/proxy/readiness_test.go
This PR fixes a bug where when running the readinessProbe, multiple db connection instances spawned in parallel
```
W0707 06:58:57.665677       1 connect.go:57] Retrying connection to MySQL (attempt 11/25): dial tcp 10.96.30.249:3306: connect: connection refused
W0707 06:58:59.642870       1 connect.go:57] Retrying connection to MySQL (attempt 7/25): dial tcp 10.96.30.249:3306: connect: connection refused
W0707 06:59:01.685816       1 connect.go:57] Retrying connection to MySQL (attempt 7/25): dial tcp 10.96.30.249:3306: connect: connection refused
W0707 06:59:06.644301       1 connect.go:57] Retrying connection to MySQL (attempt 8/25): dial tcp 10.96.30.249:3306: connect: connection refused
W0707 06:59:08.667016       1 connect.go:57] Retrying connection to MySQL (attempt 12/25): dial …
```
=> fix: prevent multiple db instances in parallel

.github/workflows/async-upload-test.yml, jobs/async-upload/Makefile, jobs/async-upload/tests/conftest.py
- adds test-e2e wiring to the existing ci/GHA
- bugfix for argparse to the `--e2e` option
- small refactor for performance, since Job doesn't for 99% case need to modify the server for local development switch defaults
locally with `make test`, `make test-e2e`.
=> ci: add test-e2e for the async-upload Job

clients/python/src/model_registry/types/artifacts.py
There are usecases where a ModelArtifact will not have a `uri` associated to it, such as when kicking off an model synchronization job (the uri will be pending as the synchronization happens). The data model for a ModelArtifact does not require the uri to be populated, so having these asserts in the client will cause errors to be thrown even though the returned (or supplied) data is valid.
This PR does present a breakage risk for consumers of the MR Client.
They might have logic which wraps a call to fetch a ModelArtifact with a try/catch block, and handle that case accordingly. With this change, that logic would need to be changed to check for existence (`is None`) instead.
- All the commits have been [_signed-off_](https://github.com/kubeflow/community/tree/master/dco-signoff-hook#signin …
=> chore(mr-client): match up the hand-rolled artifact data model to match the api

api/openapi/catalog.yaml, api/openapi/src/catalog.yaml, catalog/internal/catalog/catalog.go, catalog/internal/catalog/testdata/empty-catalog.yaml, catalog/internal/catalog/testdata/test-list-models-catalog.yaml, catalog/internal/catalog/yaml_catalog.go, catalog/internal/catalog/yaml_catalog_test.go, catalog/internal/server/openapi/api_model_catalog_service_service.go, catalog/internal/server/openapi/api_model_catalog_service_service_test.go, catalog/internal/server/openapi/pagination.go, catalog/internal/server/openapi/pagination_test.go, catalog/pkg/openapi/api_model_catalog_service.go, catalog/pkg/openapi/sortable.go
Implements `/api/model_catalog/v1alpha1/models` for static catalogs.
In a local kind cluster and unit tests.
=> feat(catalog): Implement ListModels endpoint

clients/ui/Makefile, clients/ui/bff/internal/api/middleware.go, clients/ui/bff/internal/api/model_registry_handler.go, clients/ui/bff/internal/integrations/kubernetes/shared_k8s_client.go, clients/ui/bff/internal/integrations/kubernetes/types.go, clients/ui/bff/internal/integrations/mrserver/http.go, clients/ui/bff/internal/integrations/mrserver/http_test.go, clients/ui/bff/internal/repositories/model_registry.go, clients/ui/frontend/config/dotenv.js, clients/ui/frontend/config/webpack.dev.js, clients/ui/frontend/src/app/utilities/const.ts, clients/ui/frontend/src/bootstrap.tsx
Enable MR access in federated mode.
This pull request introduces significant updates to support multiple deployment modes (standalone, federated, and Kubeflow) and enhance the handling of external addresses and authentication in the backend-for-frontend (BFF) service. Key changes include replacing legacy deployment mode flags with a unified `DEPLOYMENT_MODE` variable, adding support for federated mode-specific configurations, and improving the HTTP client to handle custom headers for authentication.
* Updated `Makefile` in `clients/ui` to replace legacy flags (`STANDALONE_MODE`, `FEDERATED_PLATFORM`) with `DEPLOYMENT_MODE` for better clarity and extensibility across deployment modes. [[1]](diffhunk://#diff-3c870f30eb606b04f3864f6e5fe5a2002c1eb5f0b278181ebe5a4f4aa67e3fe2L35-R35) …
=> Federated mr implementation

clients/ui/bff/internal/api/registered_models_handler_test.go, clients/ui/bff/internal/mocks/model_registry_client_mock.go
This PR aims to update `GetAllModelVersionsForRegisteredModelHandler` function to send model versions based on registered model id. 
As we are getting all the versions, we are having routing issue on the frontend
1. the versions of archived models are leading the active version details page - as they were having the active registered model id
2. the few archived versions of the active models are leading to the archived version details page of the archived model.
sending the model versions based on their registered ID will solve this issue - but we might need to add few versions in mocks to see other cases(ex - archived versions for active model - currently we don't have any archived versions mock under active model)
1. Go to a version inside archived models - the version details page …
=> Update mock version function to filter versions based on rmID

.github/workflows/build-and-push-image.yml
follow-up to https://github.com/kubeflow/model-registry/pull/1334
The build-and-push-image workflow was incorrectly calling the prepare.yml as a step action instead of using it as a reusable workflow. This caused the error "Can't find 'action.yml', 'action.yaml' or 'Dockerfile' under .github/workflows/prepare.yml".
Example: https://github.com/kubeflow/model-registry/actions/runs/16379707719/job/46288348593
The prepare job is already correctly called at the top of the jobs section, so the duplicate call in the steps was unnecessary and likely the cause of the failure.
cannot be tested locally ci/GHA, we need to fix on merge-to-main. …
=> fix: remove incorrect prepare workflow call in build-and-push-image.yml

Makefile, jobs/async-upload/Makefile
merging #1326 the 
https://github.com/kubeflow/model-registry/pull/1326/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52
root Makefile changes I didn't catch during review it inadvertently included inconsistency since:
- in root Makefile and in ci/GHA, we use `IMG` without trailing `:tag`
- the ./scripts/deploy_on_kind.sh uses IMG with `:tag`
this [reverts](https://github.com/tarilabs/model-registry/commit/8356c82a6bdeeca62ba42b8e34e918733e9f4489) the changes in root Makefile and make the whole if/elseif consistent without the trailing tag:
before (currently on main):
https://github.com/kubeflow/model-registry/blob/8356c82a6bdeeca62ba42b8e34e918733e9f4489/Makefile#L34-L40
after (this PR):
```sh
ifdef IMG
IMG := ${IMG}
else ifdef IMG_REGISTRY
IMG := …
```
=> ci: fix root Make image/push

clients/ui/frontend/.env, clients/ui/frontend/docs/env-variables.md, clients/ui/frontend/src/app/pages/modelRegistry/screens/__tests__/utils.spec.ts, clients/ui/frontend/src/app/pages/modelRegistry/screens/types.ts, clients/ui/frontend/src/app/pages/modelRegistry/screens/utils.ts, clients/ui/frontend/src/app/pages/settings/__tests__/ModelRegistryTableRowStatus.spec.tsx, clients/ui/frontend/src/app/types.ts, clients/ui/frontend/src/app/utilities/const.ts, clients/ui/frontend/src/concepts/modelRegistry/types.ts, clients/ui/frontend/src/concepts/modelRegistry/utils.ts
Ported https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/pages/modelRegistrySettings/__tests__/ModelRegistryTableRowStatus.spec.tsx and https://github.com/opendatahub-io/odh-dashboard/blob/main/frontend/src/pages/modelRegistry/screens/__tests__/utils.spec.ts from the midstream
Unit tests passing
=> feat: added unit test files to frontend

clients/ui/frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersionArchive.cy.ts, clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetails.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsHeaderActions.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsTabs.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsView.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersions/ModelVersionsTableRow.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersionsArchive/ArchiveModelVersionDetails.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersionsArchive/ModelVersionArchiveDetails.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/getModelVersionTuningData.ts
Upstream port of https://github.com/opendatahub-io/odh-dashboard/pull/4206
=> Fix artifacts fetched twice on model version details page

clients/python/Makefile, scripts/deploy_on_kind.sh
* Fixed kubectl output handling in deploy_on_kind.sh to properly handle multiple pods with the same image.
In the process of trying `make test-fuzz` I had a previously existing kind cluster with a deployment of model registry, due to the nature of rolling updates multiple pods were detected and the utils.sh script went into an infinite loop.
Run `make test-fuzz`on an existing kind cluster deployment, you can run this twice if you don't have a previous deployment.
=> fix: Handle rolling update when running e2e tests on an existing kind cluster

internal/core/experiment_test.go, internal/db/filter/parser.go, internal/db/filter/parser_test.go, internal/db/filter/query_builder.go
This adds handling of array values so we can do something like `id IN (6,7,8)` to filterQuery:
curl 'http://localhost:8080/api/model_registry/v1alpha3/experiment_runs?filterQuery=id+IN+(6,7,8)'
AI-assisted: Cursor (claude-4-sonnet)
=> fix filterQuery IN operator

clients/ui/frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersionDetails.cy.ts, clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersions/ModelVersionsCard.tsx, clients/ui/frontend/src/app/pages/modelRegistry/screens/components/ViewAllVersionsButton.tsx
"View versions" links now don't trigger a page reload and fixed related Cypress tests. Fixed the same for versions links in the "Latest versions" card
https://github.com/user-attachments/assets/2b8eaddb-2313-4615-b2ce-545977cd3aea
Click on the "View versions" links in the Version dropdown link and the latest versions card - this shouldn't trigger a page reload 
=> fix: prevent page reload on "View versions" link clicks

Makefile, README.md, docker-compose-local.yaml, docker-compose.yaml
- Add profile-based configuration to support both MySQL and PostgreSQL databases in docker-compose.yaml and docker-compose-local.yaml
- Add comprehensive make targets for easy compose management with auto-detection of docker-compose vs podman-compose
- Update README.md with complete documentation for database profiles and new make targets
Changes:
- docker-compose.yaml: Add mysql/postgres profiles with proper shell syntax
- docker-compose-local.yaml: Add mysql/postgres profiles with proper shell syntax
- Makefile: Add compose/* targets with automatic compose command detection
- README.md: Document profile usage and new make targets
Features:
- Support for both MySQL and PostgreSQL via --profile flag
- Environment variable DB_TYPE controls database selection
- Make targets: compose/up, …
=>   feat(compose): add database profile support with MySQL and PostgreSQL

.github/workflows/trivy-image-scanning.yaml
implement Kubeflow Community guideline
make it similar to Spark Operator
for the published images by this Working Group, Model Registry execute the check weekly on the published images
and on-demand (helpful for testing, etc)
segregate result in individual files
in case of future debugging needs
thanks to discussion with @kramaranya.
using from : https://github.com/kubeflow/spark-operator/blob/master/.github/workflows/trivy-image-scanning.yaml 
but making a matrix for the images which are published by this working group.
Since there is no easy way to effectively test this setup even with Act, relying on the GitHub Action workflow_dispatch and amending in future if needed
- All the commits have been [_signed-off_](https://github.com/kubeflow/community/tree/master/dco-signoff-hook#signing-of …
=> ci: add Trivy scan results to Security tab

jobs/async-upload/README.md, jobs/async-upload/job/config.py, jobs/async-upload/job/models.py, jobs/async-upload/samples/sample_job_s3_to_oci.yaml, jobs/async-upload/tests/integration/test_integration_async_upload.py, jobs/async-upload/tests/test_config.py, jobs/async-upload/tests/test_download.py, jobs/async-upload/tests/test_models.py, jobs/async-upload/tests/test_mr_client.py, jobs/async-upload/tests/test_upload.py
This is the initial phase to expand the capability of the async upload job. There are usecases where a user might want to perform more than simply "updating an artifact" once the async job completes.
Additional use cases include (but may not be limited to): fully-registering the model in the model-registry (providing all metadata required to register a new model) and adding an additional version to an existing registered model (and the metadata required for that)
This PR will just add these upload-intents as options, with the default setting to "upload_artifact" (the initial functionality).
This will not change the behavior of the system as-is, but does enable the expansion of these other upload intents safely.
Unit tests ensuring the default config behavior is maintained
- All the …
=> [Async Upload] Add initial intent options for more usecases

clients/python/src/model_registry/_client.py, clients/python/tests/test_client.py
- When user do not supply explicitly user_token=, add fallback to read from K8s SA token file when envvar `KF_PIPELINES_SA_TOKEN_PATH` is not set
- Change token from envvar log level from warning to info for consistency
- Add test coverage for token source priority and fallback logic
- Ensure envvar `KF_PIPELINES_SA_TOKEN_PATH` token takes precedence over K8s file token when both are available
In a simple Notebook, typically we rely on envvar `KF_PIPELINES_SA_TOKEN_PATH` to point to the path containing a SA token, since in most environment we faced this envvar is set into the Notebook with the KFP SA token (and we refer to that, not necessarily the SA token of the Jupyter Notebook itself).
Instead, in a simple example of K8s workload (eg KFP, or simply a Pod), I typically resort to …
=> feat(client): add K8s SA token fallback for user authn

Dockerfile, catalog/internal/server/openapi/api_model_catalog_service_service.go, catalog/internal/server/openapi/api_model_catalog_service_service_test.go, catalog/pkg/openapi/go.mod, cmd/csi/Dockerfile.csi, go.mod, go.work
* Unescape model names in model catalog's model endpoints (fixes #1554)
- Publish the catalog's generated Go client as a package
See steps in #1554
=> Unescape catalog model names / publish catalog openapi client

clients/ui/bff/internal/integrations/kubernetes/k8mocks/base_testenv.go, clients/ui/bff/internal/repositories/model_catalog.go, manifests/kustomize/options/catalog/base/service.yaml
Name the model-catalog service `model-catalog-service` instead of `model-catalog-model-catalog-service`.
Applied to a dev cluster.
=> fix(catalog): remove the duplicated model-catalog prefix from the service name

internal/tls/config_test.go, main.go
We have received the following report:
```
ID: ADA-KUBEFL-12
Type: Vulnerability
Severity: Moderate
Vulnerable Component: Model Registry main function
```
While the default configuration of Model Registry do not expose port 6060: https://github.com/kubeflow/model-registry/blob/d8744430a18c186b3d3330708a835f302c801016/manifests/kustomize/base/model-registry-deployment.yaml#L59-L61
it is not considered ideal anyway as a misconfiguration may lead to expose pprof endpoint in production.
Allegedly, this endpoint was used _once_ for local testing of some goroutine refactor; so instead of simply removing it, we're commenting it away with reference to the report ID; this should allow a contributor to easily re-enable it if needed, while providing a reminder to not commit it in the effective code …
=> ADA-KUBEFL-12: remove pprof from "production code"

clients/ui/Makefile, clients/ui/docs/local-deployment-guide.md
As discussed with @ederign - the DEV_MODE_PORT environment variable is outdated and replaced by the DEV_MODE_MODEL_REGISTRY_PORT and DEV_MODE_CATALOG_PORT variables, but it was not updated in the Makefile commands `dev-bff-kubeflow` and `dev-bff-federated`. The latter also included MOCK_MR_CLIENT=false but not MOCK_MR_CATALOG_CLIENT=false so this adds the latter for consistency.
Using k9s to port forward the model registry and model catalog services to ports 8085 and 8086, running the BFF with `make dev-bff-kubeflow` or `make dev-bff-federated` and attempting to curl BFF endpoints for each of those services.
```sh
curl -i -H "X-Forwarded-Access-Token: $TOKEN" "localhost:4000/api/v1/model_registry/modelregistry-sample/registered_models?namespace=kubeflow"
```
Note that the model catalog …
=> Makefile: Replace old DEV_MODE_PORT in federated commands with correct variables

clients/ui/bff/internal/integrations/kubernetes/k8mocks/base_testenv.go, clients/ui/bff/internal/repositories/model_catalog.go, manifests/kustomize/options/catalog/base/deployment.yaml, manifests/kustomize/options/catalog/base/kustomization.yaml, manifests/kustomize/options/catalog/base/service.yaml, manifests/kustomize/options/catalog/overlay/destination-rule.yaml, manifests/kustomize/options/catalog/overlay/virtual-service.yaml
Rename `model-catalog-service` to just `model-catalog`.
Local cluster and unit tests.
=> feat(catalog): rename the model-catalog service

api/openapi/catalog.yaml, api/openapi/src/catalog.yaml, catalog/internal/catalog/catalog.go, catalog/internal/server/openapi/api_model_catalog_service_service_test.go, catalog/internal/server/openapi/type_asserts.go, catalog/pkg/openapi/model_catalog_source.go
In this PR I added a labels field to CatalogSource entities in the Model Catalog API to support labeling and categorization of catalog sources.
```yaml
catalogs:
- name: Sample Catalog
id: sample_custom_catalog
type: yaml
enabled: true
properties:
yamlCatalogPath: sample-catalog.yaml
```
```shell
curl --request GET -s  --url http://localhost:8080/api/model_catalog/v1alpha1/sources | jq
{
"items": [
{
"enabled": true,
"id": "sample_custom_catalog",
"labels": [],
"name": "Sample Catalog"
}
],
"nextPageToken": "",
"pageSize": 10,
"size": 1
}
```
```yaml
catalogs:
- name: Sample Catalog
id: sample_custom_catalog
type: yaml
enabled: true
labels: []
properties:
yamlCatalogPath: sample-catalog.yaml
```
```shell
curl --request GET -s  --url http://localhost:8080/api/model_catalog/v1alpha1/sources …
```
=> feat: add labels field to catalog sources

clients/ui/bff/internal/mocks/model_catalog_client_mock.go
Incorrect conversion of an integer with architecture-dependent bit size from strconv.Atoi to a
lower bit size type int32 without an upper bound check.
make build
- [NA] **For first time contributors**: Please reach out to the [Reviewers](https://github.com/kubeflow/model-registry/blob/main/OWNERS) to ensure all tests are being run, ensuring the label `ok-to-test` has been added to the PR.
=> bff(chore): clamp int values before casting to int32 in pagination

devenv/configs/tiltfiles/catalog.tiltfile, docker-compose-local.yaml, docker-compose.yaml
Adding postgres to tilt and docker compose for dev.
Locally
=> feat(catalog): add postgres for catalog dev

clients/python/tests/fuzz_api/model_registry/test_mr_stateless.py, cmd/proxy.go, internal/converter/openapi_converter_util.go, internal/converter/openapi_converter_util_test.go, internal/core/experiment_run.go, internal/core/metric_history_test.go, internal/db/service/metric_history.go, internal/db/service/metric_history_test.go, internal/server/middleware/router.go, internal/server/middleware/validation.go, internal/server/middleware/validation_test.go, internal/server/openapi/api_model_registry_service_service.go
Added validation for "0x00" character that is not allowed in TEXT field in postgresql, it'll be detected in body/queryparams and give status code 400 as a result, I have also added validation for the stepIds param for metric history
Fuzz tests: https://github.com/kubeflow/model-registry/actions/runs/17863772761/job/50800965915
=> fix: unicode characters in stepids

clients/python/src/model_registry/_client.py, clients/python/tests/test_client.py
Previously the user_token_envvar kwarg for ModelRegistry.__init__ was given an explicit default string value, so passing in None or another falsy value would override the default. With this change, passing a falsy value results in the default being tried. This also errors when the user passes a non-empty string value but the env var is not set.
This allows the async-job to automatically use the default value as expected. Previously, we had to explicitly specify a value like this:
```
- name: MODEL_SYNC_REGISTRY_USER_TOKEN_ENVVAR
value: KF_PIPELINES_SA_TOKEN_PATH
```
because failing to do so sets user_token_envvar to None.
If you have …
=> fix user token handling

.github/workflows/build-and-push-async-upload.yml, .github/workflows/build-and-push-csi-image.yml, .github/workflows/build-and-push-image.yml, .github/workflows/build-and-push-ui-images-standalone.yml, .github/workflows/build-and-push-ui-images.yml
I've tested in my fork to generate SBOM at least for our main container images, based on related discussions for graduation.
This provides and attach a spdx sbom to the images, albeit with some limitations:
- when using `docker/build-push-action` it uses the Docker format, so it's not recognized by cosign ootb and it's not signed
- when using docker/podman/container-engine manually, it's not signed
in other words:
| image                              | generates SBOM? | cosign-compatible format? | signed? |
|------------------------------------|-----------------|---------------------------|---------|
| model-registry/job/async-upload    | ✅               | no                        | no      |
| model-registry/storage-initializer | ✅               | ✅                         | no      |
| …
=> feat(ci): introduce first step to sbom

.github/dependabot.yml
in /jobs/async-upload we use Poetry pyproject.toml we also export the dependencies via Poetry export plugin into requirements.txt for hermetic builds.
Due to the way dependabot works atm however, this leads to PRs from dependabot which only updates requirements.txt and ignore pyproject.toml and importantly ignore poetry.lock bumps
We need the opposite. We need to the Dependabot to update our lock file governed by Poetry, and in second instance we need to (manually) update the requirements.txt via makefile
I can't see practical ways to test this beyond merging this PR and waiting the next cycle.
=> ci: dependabot prefers requirements.txt

clients/python/tests/fuzz_api/model_registry/test_mr_stateless.py, internal/core/artifact.go
This PR fixes current main CI failures on fuzz tests (e.g. https://github.com/kubeflow/model-registry/actions/runs/18311924976/job/52142359445)
API now returns 404 when trying to create an artifact on a non existing model version at endpoint `/api/model_registry/v1alpha3/model_versions/{model_version_id}/artifacts`
going from
(status 500)
```
{
"code":"Internal Server Error",
"message":"error creating attribution: violates foreign key constraint"
}
```
to
(status 404)
```
{
"code": "Not Found",
"message": "no model version found for id 2: not found"
}
```
=> fix: return 404 in artifact creation on non existing model version

catalog/cmd/catalog.go, catalog/internal/catalog/performance_metrics.go
Adds the initial structure for loading the performance metrics data from a filepath into the database. Currently this is just setting up the configuration and the initial checks to validate that the data is present and can be loaded.
This is the first part of a series of PRs to actually load this performance metric data into the database, there will be additional PRs that build off of this one.
Locally using docker/docker-compose
=> Setup initial structure for loading performance data
