- clients/python/pyproject.toml
bumping pyproject.toml before release of Alpha 0.2.0
> alpha release: py: bump pyproject.toml

- csi/Dockerfile
This commit will update the ubi8 image tag to latest
> Signed-off-by: tonyxrmdavidson <tonyxrmdavidson@yahoo.co.uk>

- clients/python/pyproject.toml
> py(chore): bump to next version

- manifests/kustomize/README.md
as discussed in Scrum, wdyt @rareddy ?
> docs: prereq to verify pwd in correct directory

- api/openapi/model-registry.yaml
update the openapi description to reflect the
actual semantic and actually available verbs.
Resolves #63
> openapi: wrong ref to delete, list GET and PATCH

- clients/python/README.md
- clients/python/poetry.lock
- clients/python/pyproject.toml
Fixes some missing updates from #152 and #180 .
> Py: Update README.md and fix ruff pin

- .github/dependabot.yml
adding bff and frontend to dependabot weekly checks
I'm not sure how to test this locally.
> chore: adding bff and frontend to dependabot weekly checks

- .github/dependabot.yml
@lampajr could you kindly take a look 👀  ?
per title
> chore: onboard CSI on dependabot

- .github/workflows/ui-frontend-build.yml
Fixing the build after ebe6bc0abc39e4e3ded9a44b1331589dff04e086 .
We are moving to cypress for testing and it should be re introduced by https://github.com/kubeflow/model-registry/pull/234
- [X ] The commits and have meaningful messages; the author will squash them [after approval](https://github.com/opendatahub-io/opendatahub-community/blob/main/contributor-cheatsheet.md#:~:text=Usually%20this%20is%20done%20in%20last%20phase%20of%20a%20PR%20revision) or will ask to merge with squash.
- [X ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ X] The developer has manually tested the changes and verified that the changes work
> chore: removing temporarly test execution

- .openapi-generator-ignore
- internal/server/openapi/api_model_registry_service_service.go
- internal/server/openapi/error.go
- internal/server/openapi/helpers.go
- test/robot/Regression.robot
Resolves: #95
Tested with making POST/PATCH API calls with random missing/mispelled fields.
> wrap default openapi error handler

- clients/python/src/mr_openapi/models/model_version.py
- clients/python/src/mr_openapi/models/model_version_create.py
- clients/python/src/mr_openapi/models/registered_model.py
- clients/python/src/mr_openapi/models/registered_model_create.py
Missing model updates after #253.
> py: update contexts

- .github/workflows/build.yml
No need to setup protoc twice. `make build` also invokes `deps`.
> GHA: build: simplify action

- README.md
…o adds informaiton on a known issue regarding DB deployment and how to mitigate it when it happens
Change 'Known Isues' to 'Tips'
This commit will change the title of the section of the README to Tips
Change Title to Generic Reference
This commit will change the title from Model-Registry-db mysql:8.3.0 to use a generic title which will reflect that pull image rate limiting is not confined to mysql:8.3.0
Change Description of Issue
This commit will change the description to use the model-registry-db container issue as an example to demonstrate image rate limiting.
Specify Error Description is an Example
This commit will expand the description of the error to show it is an example of a wider issue.
> Add Tips section to README.md

- clients/ui/OWNERS
> Add alexcreasy to owners of ui

- csi/Makefile
Follow-up to #288 . Aligns with CSI build.
> csi: drop go from bin

- Makefile
- scripts/build_deploy.sh
- scripts/gen_openapi_server.sh
- scripts/gen_type_asserts.sh
- scripts/install_protoc.sh
> tidy scripts

- csi/go.mod
- csi/go.sum
Resolves https://github.com/kubeflow/model-registry/issues/311
`go mod tidy` locally
> chore: fix go .mod and .sum for CSI

- clients/python/pyproject.toml
- clients/python/src/model_registry/__init__.py
version bump chore following release.
> chore: version bump

- .github/workflows/python-tests.yml
- .github/workflows/ui-bff-build.yml
- .github/workflows/ui-frontend-build.yml
> GHA: ignore unrelated file changes

- .github/pull_request_template.md
I suggest adding an explicit item for DCO, as I found myself explaining it several times :)
wdyt @ederign ?
> chore: explicit bulletpoint for DCO

- clients/python/src/model_registry/types/pager.py
- clients/python/tests/regression_test.py
> py: fix paging when missing token

- clients/ui/bff/README.md
Fixes a small error in the readme
> Fixes URL error in the README

- clients/python/README.md
- clients/python/src/model_registry/_client.py
- clients/python/src/model_registry/types/base.py
- clients/python/src/model_registry/types/pager.py
- clients/python/tests/test_client.py
- clients/python/tests/test_core.py
Closes: #357
This should sort out semantics issues.
> Py: rename pager `limit` method to `page_size`

- clients/ui/bff/README.md
- clients/ui/bff/api/app.go
- clients/ui/bff/api/registered_models_handler.go
- clients/ui/bff/api/registered_models_handler_test.go
- clients/ui/bff/data/registered_model.go
- clients/ui/bff/data/registered_model_test.go
- clients/ui/bff/integrations/http.go
- clients/ui/bff/internals/mocks/http_mock.go
- clients/ui/bff/internals/mocks/model_registry_client_mock.go
* Adds scafolding for PATCH endpoints
* Adds stub for patching RegisteredModels
* Fixes a bug where the location header in the response of POST/PATCH endpoints did not return the correct URL
* Run in mock mode
* Run new PATCH request in README via curl
* Verify response is in correct envelope format
* Verify location header does not contain an unparsed template placeholder
> Adds scaffolding and mock support for PATCH endpoints

- clients/ui/frontend/.gitignore
- clients/ui/frontend/src/__tests__/cypress/.gitignore
Some GHA are failing due to lack of cleanup of downloads folder: https://github.com/kubeflow/model-registry/actions/runs/10948937500/job/30401082009?pr=403 
@isinyaaa gently provided a quick fix. This PR is just some FUP PR for our better code organization.
- [X ] The commits have meaningful messages; the author will squash them after approval or in case of manual merges will ask to merge with squash.
- [NA ] Testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
- [ X] The developer has manually tested the changes and verified that the changes work.
- [X ] Code changes …
> Small cleanup on cypress gitignore

- .github/workflows/ui-bff-build.yml
- clients/ui/bff/Makefile
- clients/ui/bff/docs/contributing.md
- clients/ui/bff/internal/api/errors.go
- clients/ui/bff/internal/data/model_version_test.go
- clients/ui/bff/internal/data/registered_model_test.go
Adding golangci-lint for BFF linting. This combines multiple linters to run against the BFF. I've also added a GitHub Action to run only against the BFF directory and a contributing doc with steps on how to install and run the linter locally.
Ran locally and added GHA
> Add golangci-lint for BFF linting

- clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisteredModels/RegisteredModelListView.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisteredModels/RegisteredModelTable.tsx
- clients/ui/frontend/src/index.tsx
Fix linting and accessibility issues that were introduced in the latest PR
> Fix linting and accessibility issues

- clients/ui/bff/internal/api/model_registry_handler.go
- clients/ui/bff/internal/api/model_versions_handler.go
- clients/ui/bff/internal/data/model_version_test.go
- clients/ui/bff/internal/data/registered_model_test.go
- clients/ui/bff/internal/mocks/k8s_mock.go
- clients/ui/bff/internal/mocks/model_registry_client_mock.go
A small code clean up to better model some go idioms. 
`make test`
> Cleans up some unused function params in BFF

- clients/python/pyproject.toml
- clients/python/src/model_registry/__init__.py
see also https://github.com/kubeflow/model-registry/issues/435#:~:text=drop%20the%20.a1%20suffix%20for%20the%20Model%20Registry%20python%20client
> chore: bump py versions

- clients/ui/bff/internal/mocks/model_registry_client_mock.go
Add archive models to mocks so we can display archive views.
1. In mock mode
2. Go to archive models
3. Select model
4. Go to the third version and click
> Add archived model to mocks

- clients/ui/frontend/src/style/MUI-theme.scss
Fixes UI Bugs for Labels cc @lucferbux 
Before
Registered Model List View (Default State)
Registered Model List View (Hover Overflow Label)
Registered Model Details Edit View
After:
Registered Model List View (Default State)
Registered Model List View (Hover Overflow Label)
Registered Model Details -> Labels -> Edit
Testing: 
1. Go to Registered Model List view and verify that overflow label is visible by default. 
2. Click a model, go to "Details" and verify the overflow label is shown by default. 
3. Click "Edit" button to the right of the Labels section, and verify the "Add label" button is visible by default. 
If you have UI …
> Fix UI Bugs for Labels

- clients/ui/bff/internal/mocks/static_data_mock.go
Add mocked properties to mocked registered models and versions
1. Run bff in mocked mode
> Add mocked properties to models and versions

- manifests/kustomize/base/kustomization.yaml
align manifest for 0.2.9 alpha, PR targets release branch
> chore: align manifest for 0.2.9 alpha

- README.md
update readme link for more proper location available now
> docs: update readme link

- README.md
- clients/python/pyproject.toml
- clients/python/src/model_registry/__init__.py
> chore: version bump and add alpha version policy in readme

- manifests/kustomize/base/kustomization.yaml
to avoid spurious formatting during relese
such as for example:
https://github.com/kubeflow/model-registry/pull/488/files
make the base formatting of this file consistent with the result of `kustomize edit set image ...`
> chore: format kustomization file

- Makefile
- api/openapi/model-registry.yaml
- clients/python/src/mr_openapi/models/doc_artifact.py
- clients/python/src/mr_openapi/models/doc_artifact_create.py
- clients/python/src/mr_openapi/models/doc_artifact_update.py
- clients/python/src/mr_openapi/models/model_artifact.py
- clients/python/src/mr_openapi/models/model_artifact_create.py
- clients/python/src/mr_openapi/models/model_artifact_update.py
- clients/python/src/mr_openapi/models/registered_model.py
- clients/python/src/mr_openapi/models/registered_model_create.py
- clients/python/tests/test_client.py
- internal/converter/generated/mlmd_openapi_converter.gen.go
- internal/converter/generated/openapi_converter.gen.go
- internal/converter/mlmd_converter_util_test.go
- internal/converter/mlmd_openapi_converter_util.go
- internal/server/openapi/api_model_registry_service.go
- internal/server/openapi/type_asserts.go
- pkg/openapi/factories.go
- pkg/openapi/model_doc_artifact.go
- pkg/openapi/model_doc_artifact_create.go
- pkg/openapi/model_doc_artifact_update.go
- pkg/openapi/model_model_artifact.go
- pkg/openapi/model_model_artifact_create.go
- pkg/openapi/model_model_artifact_update.go
- templates/go-server/controller-api.mustache
> core: openapi factories, do not require artifactType

- clients/ui/frontend/package-lock.json
- clients/ui/frontend/package.json
Fixed uncommited files issue from dependabot at https://github.com/kubeflow/model-registry/actions/runs/11666368298/job/32481155391?pr=529
> build(deps): bump @typescript-eslint/parser from 8.9.0 to 8.12.2 in clients/ui/frontend

- manifests/kustomize/base/kustomization.yaml
- manifests/kustomize/options/csi/kustomization.yaml
> chore: align manifest for 0.2.10

- clients/ui/.env
- clients/ui/.gitignore
- clients/ui/Makefile
- clients/ui/README.md
- clients/ui/manifests/base/kustomization.yaml
- clients/ui/scripts/deploy_kind_cluster.sh
Added a way to build and push images automatically based on env variables.
1. Change `.env.local` with values to your own private repo
2. Run `make build`
3. Run `make push`
4. Run `make kind-deployment`
> Enhance builds and push

- clients/ui/.env
We don't tag a `dev-latest` it should only be `latest`
> Fix UI and BFF image tags for our make deployment script

- clients/ui/frontend/nginx.conf
We need this for istio integration, since Nginx is defaulting to 1.0. Istio complains and asks for http version upgrade (status code 426)
Error goes away on my cluster after testing this with a local image. Would like to merge this so I can test with our normal images.
I would suggest we try running this on a local cluster to see if it works correctly.
> Upgrade nginx proxy http version

- manifests/kustomize/base/kustomization.yaml
- manifests/kustomize/options/csi/kustomization.yaml
> chore: align manifest for 0.2.11

- clients/python/pyproject.toml
- clients/python/src/model_registry/__init__.py
> chore: bump py version

- clients/ui/.env.test
- clients/ui/.gitignore
- clients/ui/frontend/.env.test
- clients/ui/frontend/src/__tests__/cypress/cypress/utils/testConfig.ts
Add `env.test` variable and overrides root `.gitignore` to get the file tracked
> Add env.test file

- manifests/kustomize/base/kustomization.yaml
- manifests/kustomize/options/csi/kustomization.yaml
> chore: align manifest for 0.2.12

- clients/python/pyproject.toml
- clients/python/src/model_registry/__init__.py
following recent release, chore version bump of the MR python client
> chore: bump py version to 0.2.13

- manifests/kustomize/base/kustomization.yaml
- manifests/kustomize/options/csi/kustomization.yaml
> chore: align manifest for 0.2.13

- clients/ui/bff/README.md
Follow up of https://github.com/kubeflow/model-registry/pull/742 to fix the docs about the base version.
> Fix golang base version

- clients/python/pyproject.toml
- clients/python/src/model_registry/__init__.py
> chore: bump py version to next v0.2.14

- cmd/proxy.go
Model Registry was using a full CPU when idle. I traced it back to some
recent error handling code that had a select with a normally closed
channel.
The problem is that `errMLMDChan` closes quickly and afterwards the `select`
never blocks. Since it's in a loop, it's constantly re-running the select. I
don't think it affected the behavior, but it does hit the CPU pretty hard (to
say nothing of my laptop battery, which is really why I noticed).
Sanity check on model registry behavior.
> fix: high cpu load when idle

- pkg/inferenceservice-controller/controller.go
Fixed a typo that caused the inferenceservice reconciler function to check the wrong annotation in the model registry service
local cluster + tests
> fix(isvc): switched to the correct annotation in mr svc

- clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisterModel/RegistrationCommonFormSections.tsx
- clients/ui/frontend/src/shared/style/MUI-theme.scss
Slash for "Path" input should be aligned inside of the input field.
Before:
After:
1. In Model Registry list view, click "Register Model" button.
2. Scroll down to "Model Location" -> "Object storage"
3. Verify "Path" field has proper alignment and "/" icon is positioned within the form field. 
> fix(frontend): update path icon alignment, remove Split and revert to TextInputGroup

- clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelRegistry.tsx
- clients/ui/frontend/src/app/pages/settings/ModelRegistrySettings.tsx
- clients/ui/frontend/src/shared/components/ApplicationsPage.tsx
Hides the title icon and adds a separator in the main title section.
Before:
After:
Tests N/A, visual updates only. 
1. Go to Model Registry list view and verify that the title icon has been removed, and the divider renders under the title and description. 
2. In the left nav, click "Settings" -> "Model Registry" and verify that the title icon has been removed and the divider renders under the title and description. 
> fix(frontend): Hide title icon and add divider

- clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisterModel/RegistrationCommonFormSections.tsx
Fix an issue with our linter that wasn't caught in the given PR.
Running `npm run test`
> Fix build issue

- clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersions/ModelVersionListView.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisteredModels/RegisteredModelsTableToolbar.tsx
1. Fixes alignment of **Register Model** action in main toolbar for Registered Models screen. 
2. Fixes alignment of **Register New Version** action in main toolbar for Model Versions screen. 
Before - Registered Models List:
Before - Model Versions List:
After - Registered Models List:
After - Model Versions List:
1. In Model Registry list view, verify the **Register Model** action in the main toolbar is aligned with the input field in the main toolbar. 
2. Click on a registered model in the Model Registry list view.
3. In the list view for the model versions, verify the  **Register New Version** action in the main toolbar is aligned with the input field in the main toolbar. 
Tests N/A, UI updates only.
- All the commits have been …
> fix(frontend): Fix alignment of "Register" toolbar action

- clients/ui/frontend/src/app/NavBar.tsx
- clients/ui/frontend/src/shared/style/MUI-theme.scss
Updates Model Registry and Namespace selector to match with MUI theming. 
Before:
After:
Kubeflow Disabled Namespace selector: 
MUI Disabled Select: 
> fix(frontend): Update disabled dropdown styling to match with KF

- clients/ui/frontend/src/shared/style/MUI-theme.scss
Updated the padding on the breadcrumb to align with the page title in the Model Versions list view.
Before:
After:
1. Navigate to Model Registry list view.
2. Click on a model.
3. Verify the breadcrumb is aligned with the page title. 
4. Click on a model version. 
5. Verify the breadcrumb is aligned with the page title.
Tests N/A, visual updates only. 
> fix(frontend): Fix breadcrumb padding

- api/openapi/model-registry.yaml
- clients/python/src/mr_openapi/models/artifact_list.py
- clients/python/src/mr_openapi/models/inference_service_list.py
- clients/python/src/mr_openapi/models/model_artifact_list.py
- clients/python/src/mr_openapi/models/model_version_list.py
- clients/python/src/mr_openapi/models/registered_model_list.py
- clients/python/src/mr_openapi/models/serve_model_list.py
- clients/python/src/mr_openapi/models/serving_environment_list.py
- internal/server/openapi/type_asserts.go
- pkg/openapi/model_artifact_list.go
- pkg/openapi/model_inference_service_list.go
- pkg/openapi/model_model_artifact_list.go
- pkg/openapi/model_model_version_list.go
- pkg/openapi/model_registered_model_list.go
- pkg/openapi/model_serve_model_list.go
- pkg/openapi/model_serving_environment_list.go
Slight improvement in declaring the items field in the list request as required, so that the autogen does not set it to omitempty, which causes json umarshal to remove the field.
local testing
> feat(openapi): make items a required field in List requests

- clients/ui/frontend/src/shared/components/table/TableBase.tsx
Fixes alignment of "next" and "previous" control buttons within pagination component. 
Before:
After:
1. Navigate to Model Registry list view, verify the alignment of "next" and "previous" buttons is correct.
2. Click on a model, verify the alignment of pagination arrows is correct in model versions list view. 
Tests n/a, visual changes only. 
> fix(frontend): Fix alignment of pagination nav control buttons

- manifests/kustomize/base/kustomization.yaml
- manifests/kustomize/options/csi/kustomization.yaml
- manifests/kustomize/options/ui/base/kustomization.yaml
> chore: align manifest for 0.2.14

- proposals/README.md
Kubeflow has adopted the KEP process for documenting large changes. Refer to https://github.com/kubeflow/community/tree/master/proposals for more details.
cc @kubeflow/kubeflow-steering-committee
> docs: Add information about KEPs

- clients/python/pyproject.toml
- clients/python/src/model_registry/__init__.py
> chore: bump py version to next v0.2.15

- clients/ui/frontend/package-lock.json
- clients/ui/frontend/package.json
Dependabot messed up with package-lock.json.
Run tests and web app locally.
> build(deps): bump @typescript-eslint/eslint-plugin from 8.21.0 to 8.24.0 in /clients/ui/frontend

- clients/ui/Dockerfile
- clients/ui/bff/Makefile
Improves Dockerfile and Makefile to handle multiple go files in the main package, should fix broken CI job.
> Fixes broken CI job

- clients/ui/frontend/src/shared/style/MUI-theme.scss
Applies missing page padding in default PF theme.
Before - List:
After - List:
Before - Details:
After - Details:
In `const.ts`, update line 17 to:
```
export const isMUITheme = (): boolean => STYLE_THEME === Theme.Default;
```
Tests n/a, visual changes only. 
> fix(frontend): fix missing page padding in default PF theme

- clients/ui/frontend/src/app/NavBar.tsx
- clients/ui/frontend/src/app/NavSidebar.tsx
Fixes navbar to apply correct logo and position in default theme. 
Before:
After:
1. In `clients/ui/frontend/src/shared/utilities/const.ts`, change line 17 to:
```
export const isMUITheme = (): boolean => STYLE_THEME === Theme.Default;
```
2. Verify that icon renders within masthead and uses dark variant. 
> fix(frontend): fix navbar to apply correct logo and position in default theme

- clients/ui/frontend/src/__tests__/cypress/cypress/pages/appChrome.ts
- clients/ui/frontend/src/__tests__/cypress/cypress/pages/navBar.ts
- clients/ui/frontend/src/__tests__/cypress/cypress/tests/mocked/kubeflowStandalone/navBar.cy.ts
- clients/ui/frontend/src/app/App.tsx
- clients/ui/frontend/src/app/NavBar.tsx
- clients/ui/frontend/src/shared/context/NamespaceSelectorContext.tsx
- clients/ui/frontend/src/shared/context/__tests__/NamespaceSelectorContext.test.tsx
Add testing coverage for navbar
Run testing stack
> Add testing coverage for NavBar

- clients/ui/frontend/package-lock.json
- clients/ui/frontend/package.json
FUP for: https://github.com/kubeflow/model-registry/actions/runs/13499773662/job/37715116142?pr=828
Quick local sanity check
> build(deps): bump eslint-import-resolver-typescript from 3.6.3 to 3.8.3 in /clients/ui/frontend

- manifests/kustomize/options/ui/base/kustomization.yaml
- manifests/kustomize/options/ui/base/model-registry-ui-deployment.yaml
Update model registry image convention
Running `kustomize build manifests/kustomize/options/ui/base` and checking if the image is properly replaced.
> Update model registry image name convention

- .github/pull_request_template.md
- .github/workflows/ui-bff-build.yml
- .github/workflows/ui-frontend-build.yml
- .gitignore
Add new check for new contributions and change UI GA to only trigger with UI changes
No testing added
> Add new check to PR templates and tweak UI GA

- .github/workflows/build-image-ui-pr.yml
Runs an image build of the UI container on PR. This would have caught a recent case where a merged PR broke the container image build.
- See if CI job passes!
> Run container image build of UI on PR

- clients/ui/frontend/src/app/pages/settings/ModelRegistriesTable.tsx
- clients/ui/frontend/src/app/pages/settings/ModelRegistryCreateModal.tsx
- clients/ui/frontend/src/app/pages/settings/ModelRegistryCreateModalFooter.tsx
- clients/ui/frontend/src/app/pages/settings/ModelRegistryDatabasePassword.tsx
- clients/ui/frontend/src/app/pages/settings/ModelRegistrySettings.tsx
- clients/ui/frontend/src/app/pages/settings/PasswordInput.tsx
- clients/ui/frontend/src/concepts/k8s/K8sNameDescriptionField/K8sNameDescriptionField.tsx
- clients/ui/frontend/src/concepts/k8s/K8sNameDescriptionField/ResourceNameField.tsx
- clients/ui/frontend/src/concepts/k8s/ResourceNameDefinitionTootip.tsx
- clients/ui/frontend/src/shared/components/FieldGroupHelpLabelIcon.tsx
Migrates the code related to create a new Model Registry from midstream.
Before:
After:
1. Navigate to Settings -> Model Registry 
2. Click "Create Model Registry Button"
3. Verify modal renders as expected. 
> feat(frontend): Create Model Registry Modal

- manifests/kustomize/base/kustomization.yaml
- manifests/kustomize/options/csi/kustomization.yaml
- manifests/kustomize/options/ui/base/kustomization.yaml
> chore: align manifest for 0.2.15

- clients/ui/frontend/package-lock.json
- clients/ui/frontend/package.json
This PR updates:
- https://github.com/kubeflow/model-registry/pull/873
- https://github.com/kubeflow/model-registry/pull/874
- https://github.com/kubeflow/model-registry/pull/844
- @babel/helpers  CVE
- @babel/runtime  CVE
I did a quick local sanity check.
> build(deps): frontend maintenance

- clients/ui/frontend/src/concepts/k8s/ResourceNameDefinitionTootip.tsx
Closes #882 
Before:
After:
1. Navigate to Model Registry -> Settings -> Model Registry.
2. Click "Create Model Registry" button.
3. Under "Name" input field click the question icon to toggle the tooltip text.
4. Reference to Openshift should now be removed in tooltip text.
- [] The developer has added tests or explained why testing cannot be added.
> fix(frontend): Remove midstream reference from resource name tooltip

- clients/ui/frontend/package-lock.json
- clients/ui/frontend/package.json
Dependency update to address warning from `npm audit`. Used `npm audit --force`
Updates `@module-federation/enhanced` from `0.8.9` to `0.11.1`
`npm audit`
Sanity check to bring up frontend.
Built and deployed with module federation in a test environment with a host application.
> build(deps): bump @module-federation/enhanced from 0.8.9 to 0.11.1

- devenv/.dockerignore
- devenv/.gitignore
- devenv/Makefile
- devenv/README.md
- devenv/Tiltfile
- devenv/configs/helm-values/jupyterhub.yaml
- devenv/configs/kustomize/ui-rbac/clusterrolebinding.yaml
- devenv/configs/kustomize/ui-rbac/kustomization.yaml
- devenv/configs/tiltfiles/frontend.tiltfile
- devenv/configs/tiltfiles/jupyterhub.tiltfile
- devenv/configs/tiltfiles/pythonclient.tiltfile
- devenv/configs/tiltfiles/setup.tiltfile
- devenv/tilt_config.json
- tilt-ui.dockerfile
- tilt.dockerfile
closes #851 
**What is Tilt?**
A tool that makes working with microservices a little less painful when developing locally, it uses the current Kubernetes context to deploy and manage your services, it supports live updates, and much more [here](https://docs.tilt.dev/)
**How does it make our lives easier?**
- Model registry (backend)
monitors file changes in the project directory (go files), rebuilds the binary and swaps it into the docker image, does port forwarding automatically (to localhost:8080)
- model registry (python client)
monitors file changes in the clients/python folder, builds the wheel file and uploads it to a jupyter notebook hosted on the cluster using jyputerhub, so you just need to pip install the newer wheel file to test the changes on the cluster
- model registry (ui) …
> feat: Introduce Tilt as a dev environment

- .github/workflows/build-and-push-csi-image.yml
- .github/workflows/build-and-push-image.yml
- .github/workflows/build-and-push-ui-images.yml
- .github/workflows/build-image-pr.yml
- .github/workflows/python-tests.yml
- Makefile
- manifests/kustomize/base/kustomization.yaml
- manifests/kustomize/base/model-registry-deployment.yaml
- manifests/kustomize/options/csi/clusterstoragecontainer.yaml
- manifests/kustomize/options/csi/kustomization.yaml
- manifests/kustomize/options/ui/base/kustomization.yaml
- scripts/build_deploy.sh
See https://github.com/kubeflow/model-registry/pull/872#issuecomment-2737538957
> gha: cherry-pick #872 to v0.2.15 branch

- .github/workflows/build-and-push-csi-image.yml
- .github/workflows/build-and-push-image.yml
- .github/workflows/build-and-push-ui-images.yml
- .github/workflows/build-image-pr.yml
- .github/workflows/python-tests.yml
- Makefile
- manifests/kustomize/base/model-registry-deployment.yaml
- manifests/kustomize/options/csi/clusterstoragecontainer.yaml
- manifests/kustomize/options/ui/base/kustomization.yaml
- scripts/build_deploy.sh
> [feature] change default image repository to ghcr

- .github/workflows/build-and-push-csi-image.yml
- .github/workflows/build-and-push-image.yml
- .github/workflows/build-and-push-ui-images.yml
- .github/workflows/build-image-pr.yml
- .github/workflows/build-image-ui-pr.yml
- .github/workflows/csi-test.yml
- Makefile
- manifests/kustomize/base/model-registry-deployment.yaml
- manifests/kustomize/options/csi/clusterstoragecontainer.yaml
- manifests/kustomize/options/ui/base/kustomization.yaml
- scripts/build_deploy.sh
- test/csi/e2e_test.sh
- test/csi/setup_test_env.sh
- test/scripts/install_modelregistry.sh
taking suggestions from KSC, we are renaming the
images contextually with the recent migration to
ghcr.io so to align with other KF WGs direction.
```
ghcr.io/kubeflow/model-registry                     ---> ghcr.io/kubeflow/model-registry/server
ghcr.io/kubeflow/model-registry-ui                  ---> ghcr.io/kubeflow/model-registry/ui
ghcr.io/kubeflow/model-registry-storage-initializer ---> ghcr.io/kubeflow/model-registry/storage-initializer
```
see also: https://cloud-native.slack.com/archives/C073N7B6K3R/p1742475367994499?thread_ts=1741893292.124179&cid=C073N7B6K3R
reference to:
- https://github.com/kubeflow/model-registry/pull/872
- https://github.com/kubeflow/model-registry/pull/897
using GHA run to check the action job update run correctly and related e2e testing
- All the commits …
> build: update image name with prefix following KSC

- manifests/kustomize/base/kustomization.yaml
- manifests/kustomize/options/csi/kustomization.yaml
- manifests/kustomize/options/ui/base/kustomization.yaml
> chore: align manifest for 0.2.15.2

- manifests/kustomize/base/kustomization.yaml
- manifests/kustomize/options/csi/kustomization.yaml
- manifests/kustomize/options/ui/base/kustomization.yaml
> chore: align manifest for 0.2.15.3

- api/openapi/model-registry.yaml
We have a limitation where this link: https://editor.swagger.io/?url=https://raw.githubusercontent.com/kubeflow/model-registry/main/api/openapi/model-registry.yaml
From the MAIN README.md
https://github.com/kubeflow/model-registry/blob/2153ca45db1ecd3e33c0ea74bd8ef1d8cf53740d/README.md?plain=1#L38
Or this link: https://www.kubeflow.org/docs/components/model-registry/reference/rest-api/#swagger-ui
from the Kubeflow website,
shows a wrong example for Metadata custom properties, missing the discriminator.
This unfortunately is yet another limitation of Swagger codegen suite of tools, it seems.
This fixes at least this example which seems to be a pitfall for many users.
We however encourage users to make use of the MR py client: https://model-registry.readthedocs.io/en/latest/
Manually …
> docs: fix annoyance in Swagger GUI generated example

- clients/ui/frontend/src/app/api/k8s.ts
Updates the [k8s client](https://github.com/kubeflow/model-registry/blob/main/clients/ui/frontend/src/shared/api/k8s.ts) file with the endpoints needed for settings panel.
Ran sanity checks in the UI - no testing issues. 
> feat(frontend): Create REST API for Model Registry Settings

- .github/workflows/ui-bff-build.yml
- clients/ui/bff/.golangci.yaml
- clients/ui/bff/Makefile
- clients/ui/bff/internal/integrations/http.go
port golangci-lint to v2 as the CI is failing for bff build after https://github.com/kubeflow/model-registry/pull/919
> fix(bff): port to golangci-lint v2

- manifests/kustomize/base/kustomization.yaml
- manifests/kustomize/options/csi/kustomization.yaml
- manifests/kustomize/options/ui/base/kustomization.yaml
> chore: align manifest for 0.2.16

- clients/python/pyproject.toml
- clients/python/src/model_registry/__init__.py
periodic version bump for the next MR py client release
no special testing required
> chore: bump MR py client version

- .github/workflows/build-and-push-ui-images-standalone.yml
- clients/ui/.env
- clients/ui/README.md
- clients/ui/scripts/deploy_kind_cluster.sh
feat(ci): add GitHub Actions workflow for building and pushing UI standalone image
1. In my fork, running the action with a merge and a version tag:
> Enable standalone image build

- clients/python/tests/test_client.py
remove spurious values in test case, likely originated by copy-pasting from others
> tests: remove spurious values from test case

- README.md
This PR updates the README.md to correct the UI documentation. The previous documentation referenced an outdated or incorrect folder structure, which could mislead developers by pointing them to invalid paths.
NA
- [X ] The commits have meaningful messages; the author will squash them after approval or in case of manual merges will ask to merge with squash.
NA
> Fixing UI file navigation in README

- clients/python/README.md
- clients/python/src/model_registry/_client.py
> Address typos in error message and examples

- clients/python/README.md
Add a troubleshooting section for the python client README
> Update README for the python client

- clients/python/README.md
> Address typo in example for S3Params

- scripts/deploy_on_kind.sh
fix the default which followed on:
- https://github.com/kubeflow/model-registry/pull/899#pullrequestreview-2703646773 
- https://github.com/kubeflow/model-registry/pull/872
- https://github.com/kubeflow/model-registry/pull/897
- https://github.com/kubeflow/model-registry/pull/901 
> scripts: fix default for the MR server image

- Dockerfile
fixing linting issue on Dockerfile https://github.com/kubeflow/model-registry/pull/984#discussion_r2049048476
no need
> chore: fix inconsistent case in Dockerfile

- clients/python/README.md
Fix a typo found during [an ODH sync](https://github.com/opendatahub-io/model-registry/pull/192#discussion_r2050845969).
> chore: fix typo in clients/python/README.md

- README.md
- clients/ui/README.md
- docs/logical_model.md
- docs/mr_kind_deploy_ingress.md
> Fix typos and broken link in ui/README

- clients/ui/CONTRIBUTING.md
Fixed the broken link `local kubernetes deployment` in `clients/ui/CONTRIBUTING.md`
> Fix the broken link

- clients/python/poetry.lock
- clients/python/pyproject.toml
resets urllib3 lock file pin
properly maintain boto3 extra in TOML config
this PR is raised with the intent to check this resolution resolves conflict as highlighted in #1009 
poetry install --all-extras 
succeeded locally, now testing for Nox/CI/CD
> py: resolve dependency conflict for extra boto3

- manifests/kustomize/base/kustomization.yaml
- manifests/kustomize/options/csi/kustomization.yaml
- manifests/kustomize/options/ui/base/kustomization.yaml
> chore: align manifest for 0.2.17

- Dockerfile
Small comment handy for capturing dicussion + diagram
> chore: add comment

- clients/python/pyproject.toml
- clients/python/src/model_registry/__init__.py
bump MR py client version to next v0.2.18
> chore: bump MR py client version to next v0.2.18

- ADOPTERS.md
> chore: add ADOPTERS.md per KSC/Graduation discussion

- ADOPTERS.md
This PR adds an adopter to the Kubeflow Model Registry project.
> add company to model registry adopters

- RELEASE.md
> docs: fix typo

- clients/python/README.md
- in the previous section, the client is referred as `registry.method()`
- suggest to the reader the expected import, useful for copy-paste
found these friction point when consuming the tutorial
> docs(py): minor fix for the tutorial

- ADOPTERS.md
Just added myself in the ADOPTERS list
> chore: Update ADOPTERS.md

- .github/workflows/first-time-contributor-pr.yml
instead of just relying on self-assessed bulletpoint in PR template:
https://github.com/kubeflow/model-registry/blame/de5f225d96a4daeca77506d233082b1c4ea5afa3/.github/pull_request_template.md#L21
this adds a comment to help out with the review of the PR.
unfortunately this is a GHA with trigger which cannot be easily tested locally (the goal is to provide a comment on a  PR)
@lucferbux wdyt?
> gha: workflow for comment first-time PR, onboarding

- clients/python/README.md
this section belongs to the "listing model/Pager" section, not the "Store to OCI and Register" one
> doc(py): fix by move this section in the correct place

- README.md
> docs: add Blog about KF 1.10 entry

- clients/ui/frontend/src/app/pages/modelRegistry/ModelRegistryCoreLoader.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelRegistry.tsx
- clients/ui/frontend/src/app/pages/settings/ModelRegistrySettings.tsx
Closes #933 
In Model Registry UI, navigate to Model Registry list view and Model Registry settings. Verify iconography and descriptions have been added. 
Before:
After:
> Apply Iconography, Descriptions, and Color Palette to Page Sections

- clients/ui/frontend/package-lock.json
- clients/ui/frontend/package.json
- Update sass to v1.87.0
- Update TypeScript ESLint packages to v8.31.1
- Update ESLint plugins:
- eslint-plugin-prettier to v5.4.0
- eslint-plugin-react to v7.37.5
Fixes and closes:
- https://github.com/kubeflow/model-registry/pull/1064 
- https://github.com/kubeflow/model-registry/pull/946
- https://github.com/kubeflow/model-registry/pull/1060
- https://github.com/kubeflow/model-registry/pull/1038
Basic sanity check.
> chore(frontend): update development dependencies

- clients/python/pyproject.toml
- clients/python/src/model_registry/__init__.py
To exercise the Pypi release process from this repo, creating a no fix/bug/change release following [post-release](https://packaging.python.org/en/latest/specifications/version-specifiers/#post-releases) designation.
> py: v0.2.17.post1 designation (no fix/bug/changes)

- clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelPropertiesTableRow.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersions/ModelVersionListView.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersionsArchive/ModelVersionsArchiveListView.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisterModel/PrefilledModelRegistryField.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisterModel/RegisterModelDetailsFormSection.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisterModel/RegisteredModelSelector.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisterModel/RegistrationCommonFormSections.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisteredModels/RegisteredModelListView.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisteredModelsArchive/RegisteredModelsArchiveListView.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/components/FormFieldset.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/components/ThemeAwareSearchInput.tsx
- clients/ui/frontend/src/app/pages/settings/ModelRegistryCreateModal.tsx
- clients/ui/frontend/src/app/pages/settings/components/ThemeAwareFormGroupWrapper.tsx
- clients/ui/frontend/src/shared/components/EditableTextDescriptionListGroup.tsx
- clients/ui/frontend/src/shared/style/MUI-theme.scss
This PR refactors how we handle theme-dependent UI components in our codebase. Previously we had to include conditional `isMUITheme` checks at every usage point of our custom components. 
- Moved the MUI theme conditional logic inside the `FormFieldset` component itself
- Removed redundant conditional checks at component usage sites
- Introduced `ThemeAwareFormGroupWrapper` and `ThemeAwareSearchInput` components to encapsulate conditional MUI theme logic.
- Refactored components to use these new theme-aware wrappers, removing redundant `isMUITheme` checks at usage sites.
#992  will handle additional instances of the conditional check for page headers and descriptions, as that logic is being removed there.
Manual testing was performed by toggling between the default (PatternFly) and MUI …
> Refactor Theme-Dependent MUI Component Instances

- CONTRIBUTING.md
per $subject so to update proper links to https://www.kubeflow.org/docs/about/contributing/
and check-off https://github.com/kubeflow/model-registry/issues/1080
> docs: refresh CONTRIBUTING.md

- ADOPTERS.md
> Add @tiansiyuan

- OWNERS
Per [community membership handbook](https://github.com/kubeflow/website/blob/54005ba799ba489721586b45e3e11276c3de24ee/content/en/docs/about/membership.md?plain=1#L136-L157), I'm proposing to add @ederign as `approvers` in `OWNERS` for this repo.
requirement is [met](https://github.com/user-attachments/assets/b8d3895c-5f8f-4d2a-ba93-b6e88c786993).
1. https://github.com/kubeflow/model-registry/pull/992
2. https://github.com/kubeflow/model-registry/pull/982
3. https://github.com/kubeflow/model-registry/pull/898
4. https://github.com/kubeflow/model-registry/pull/895
5. https://github.com/kubeflow/model-registry/pull/872
6. https://github.com/kubeflow/model-registry/pull/866
7. https://github.com/kubeflow/model-registry/pull/854
8. https://github.com/kubeflow/model-registry/pull/850
9. …
> OWNERS: add ederign as approvers

- .github/workflows/first-time-contributor-pr.yml
this workflow was not really running as intended ([Tide was expecting the Job NOT to skip in its entirety](https://github.com/kubeflow/model-registry/pull/1087#event-17577863569)), so amending to beta-testing it step by step
> chore: move 1st time contrib GHA in Beta mode

- CONTRIBUTING.md
- ROADMAP.md
per current process, provides a `ROADMAP.md` file as requested.
> docs: document ROADMAP.md per current process

- .github/pull_request_template.md
- Tide takes care of squash per standard Kubeflow
- Clarifies policy for https://github.com/kubeflow/model-registry/issues/1083#issue-3048958082
n/a
> docs: update Pull Request template

- Makefile
- api/openapi/src/lib/common.yaml
- api/openapi/src/model-registry.yaml
- scripts/merge_openapi.sh
Split the OpenAPI spec file into smaller pieces and merge them before generating code. The existing checks validate that the generated spec is up-to-date.
Tested the script and verified that there are no differences between the original spec and generated one.
> chore(openapi): split openapi spec file

- clients/python/pyproject.toml
- clients/python/src/model_registry/__init__.py
> chore: bump MR py client version to v0.2.19

- .github/workflows/first-time-contributor-pr.yml
by executing different steps
need be tested in GHA
> gha: test 1st time contributors steps

- jobs/async-upload/Dockerfile
- jobs/async-upload/README.md
- jobs/async-upload/job/entrypoint.py
- jobs/async-upload/job/healthcheck.py
- jobs/async-upload/pyproject.toml
Based on the discussion found here: https://github.com/kubeflow/model-registry/issues/1108
This is the initial scaffolding needed to build a container to perform the async job described in #1108
It includes a relatively complete README and Dockerfile. Also, a pyproject file and placeholder python entrypoints and healthchecks.
The goal is to have the foundation in place before starting to write the actual logic of using the MR python client to perform async job.
Locally by executing:
```bash
docker build --build-arg VCS_REF=$(git rev-parse --short HEAD) --build-arg BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ') -t test/async-upload-job .
docker run test/async-upload-job
Hello, world!
```
- All the commits have been [_signed-off_](https://github.com/kubeflow/community/tree/master/dco-signoff-ho …
> Set up initial async job scaffolding

- manifests/kustomize/overlays/db/model-registry-db-deployment.yaml
follow-up to 
- https://github.com/kubeflow/model-registry/pull/1113
as requested in 
- https://github.com/kubeflow/manifests/pull/3137#pullrequestreview-2853615708
for consistency of the defaults (considered without the kustomize)
GHAs
> manifests: align default to #1113

- clients/python/src/model_registry/_client.py
- clients/python/src/model_registry/_utils.py
- clients/python/src/model_registry/utils.py
- clients/python/tests/conftest.py
- clients/python/tests/test_client.py
- clients/python/tests/test_utils.py
closes https://github.com/kubeflow/model-registry/issues/1075
Reduce tech debt in client and increase developer experience both as library and while developing.
1. Updated docs
3. Rename and ensure utility functions are correctly named
4. Refactor S3 helper funcs into `utils.py`
5. Add support for large model uploads to S3
6. Tested support for large models uploads regressively
7. Fixed lingering Temp dir from older client release generated when a default path is used
8. Other general fixes and improvements
Tests added:
`tests/test_client.py`
Fixture added to:
`conftest.py`
> refactor: General MR Client Improvements & Hardening

- pkg/inferenceservice-controller/controller.go
- pkg/inferenceservice-controller/controller_test.go
This PR fixes a bug in the inference service reconciler. For authenticated requests to a model registry, the bearer token from the controller container was omitted, resulting in a 401 Unauthorized error response when attempting to set the desired state of an inference service to UNDEPLOYED when a user deletes an inference service in a cluster.
A workaround for existing users (from opendatahub) is to manually remove the finalizer `modelregistry.opendatahub.io/finalizer` from the stuck inferenceservices
Manually tested in a local cluster -- added an unit test for general deletion logic in this PR
> fix(insvc): bug in the inferenceservice reconciler deletion

- clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisteredModels/RegisteredModelListView.tsx
- clients/ui/frontend/src/shared/style/MUI-theme.scss
Closes #931 and #1141
This PR includes the following theming refinements:
- Fixed menu toggle styling for hover and focus states to apply blue outline when focused and black outline when hovered
- Aligned toolbar input field to match 48px height of menu toggle
- Ensured consistent alignment between components
- Also fixes padding issue with filter labels. 
This PR resolves the initial issue of the misalignment between the upper and lower toolbar items by appliying the correct MUI theming (see below). This was not an issue with alignment of the components but rather a missing border on the menu toggle which has been applied with these changes. 
Before - Menu Toggle:
After - Menu Toggle:
Before - Menu Toggle (full screen):
After - Menu Toggle (full screen):
Before - Label padding:
After - …
> fix(ui): Fix Toolbar Alignment in Model Registry UI

- OWNERS
Per [community membership handbook](https://github.com/kubeflow/website/blob/6a8ddc316df1c308f5747047265345d7db2d4fa3/content/en/docs/about/membership.md?plain=1#L136-L157), I'm proposing to add @Al-Pragliola as `approvers` in `OWNERS` for this repo.
requirement is met, Alessio has been contributing as Reviewer role since [Feb 26th](https://github.com/kubeflow/model-registry/pull/836#event-16487362615), today is May 26th, 3 months ✅.
1. https://github.com/kubeflow/model-registry/pull/1090
2. https://github.com/kubeflow/model-registry/pull/1050
3. https://github.com/kubeflow/model-registry/pull/988
4. https://github.com/kubeflow/model-registry/pull/963
5. https://github.com/kubeflow/model-registry/pull/961
6. https://github.com/kubeflow/model-registry/pull/938
7. …
> OWNERS: add Al-Pragliola as approvers

- docker-compose-mysql.yaml
- docker-compose.yaml
1. refresh the existing compose-file using SQLite
2. add a new compose-file for analogous MySQL
locally with 
```
podman compose -f docker-compose-mysql.yaml up
```
and 
```
podman compose -f docker-compose-mysql.yaml down --volumes
```
- [ x Automated tests are provided as part of the PR for major new functionalities; testing instructions have been added in the PR body (for PRs involving changes that are not immediately obvious).
> demo: refresh and add new compose file

- ADOPTERS.md
- refine the description highlighting Organization subject
- add a link to the "meta-ADOPTERS.md" from Kubeflow Community
> docs: refine ADOPTERS.md description

- .github/workflows/build.yml
fix an oversight, since makefile does include scripts run
n/a
> ci: GHA build.yml should not ignore scripts changes

- CONTRIBUTING.md
While we strived to keep the repository scripts cross-compatible with GNU and BSD utilities, developers might want to consider installing the `coreutils` from Homebrew directly.
n/a
> docs: add suggestion to add coreutils

- manifests/kustomize/options/ui/base/kustomization.yaml
Fix https://github.com/kubeflow/model-registry/issues/1195
Reverting the right image. It should work just fine.
> Revert broken image url

- clients/python/pyproject.toml
- clients/python/src/model_registry/__init__.py
periodic bump following the usual release
> py: bump MR py client version to 0.2.20

- clients/ui/frontend/package-lock.json
- clients/ui/frontend/package.json
> Bump mod-arch-shared library version

- internal/proxy/readiness.go
- manifests/kustomize/README.md
Add troubleshooting steps in the case of a schema migration dirty state. 
> add troubleshooting for schema migration error

- internal/core/artifact.go
- internal/core/artifact_test.go
- internal/core/inference_service.go
- internal/core/inference_service_test.go
- internal/core/model_version.go
- internal/core/model_version_test.go
- internal/core/registered_model.go
- internal/core/registered_model_test.go
- internal/core/serve_model.go
- internal/core/serve_model_test.go
- internal/core/serving_environment.go
- internal/core/serving_environment_test.go
- internal/datastore/embedmd/mysql/connect.go
- internal/db/scopes/paginate.go
- internal/db/service/artifact.go
- internal/db/service/doc_artifact.go
- internal/db/service/inference_service.go
- internal/db/service/model_artifact.go
- internal/db/service/model_version.go
- internal/db/service/registered_model.go
- internal/db/service/serve_model.go
- internal/db/service/serving_environment.go
- pkg/api/error.go
This PR addressed failed tests from https://github.com/kubeflow/model-registry/pull/1242
Tested locally by comparing responses from the MLMD version and the current one
> fix: stateless tests

- manifests/kustomize/base/kustomization.yaml
- manifests/kustomize/options/csi/kustomization.yaml
- manifests/kustomize/options/ui/base/kustomization.yaml
per release process https://github.com/kubeflow/model-registry/blob/main/RELEASE.md
> chore: align manifest for 0.2.20

- clients/python/pyproject.toml
- clients/python/src/model_registry/__init__.py
> chore: bump MR py client version to 0.2.21

- README.md
> update broken link for dir rename in manifests

- OWNERS
Based on [the requirements](https://www.kubeflow.org/docs/about/membership/#requirements-1), I'd like to be a reviewer for model registry.
- Submitted PRs: https://github.com/kubeflow/model-registry/pulls?q=is%3Apr+author%3Apboyd+is%3Aclosed
- Reviewed PRs: https://github.com/kubeflow/model-registry/pulls?q=is%3Apr+is%3Aclosed+assignee%3Apboyd+
- Kubeflow member since [17 Mar](https://github.com/kubeflow/internal-acls/pull/759)
N/A
> chore: add myself as reviewer

- jobs/async-upload/README.md
- jobs/async-upload/job/config.py
The async job supports a long list of parameters. This PR expands the README.md in the async-job folder to list out those parameters, and indiciate which ones are required as well as a description for each of them.
> Expand README to list out available parameters for async job

- jobs/async-upload/Dockerfile
- jobs/async-upload/requirements.txt
- switches to pythhon-312-minimal with UBI
- leverage poetry for requirements export
- install in container the depedencies via vanilla pip
- remove stale requirements.txt from VCS/git
`podman build .`
> container: use UBI and poetry export

- .github/workflows/build.yml
- .github/workflows/check-db-schema-structs.yaml
- Dockerfile
- Dockerfile.odh
- README.md
- cmd/csi/Dockerfile.csi
- devenv/README.md
- docs/mr_go_library.md
- go.mod
- gorm-gen/go.mod
bump go to 1.24, this change enable to also update several dependencies
build locally
> feat: move to go 1.24

- jobs/async-upload/samples/sample_job_s3_to_oci.yaml
make consistent with makefile:
https://github.com/kubeflow/model-registry/blob/6dc35e1eb94d9200a66705c6aa4197a7fc62d4cb/jobs/async-upload/Makefile#L32-L33
see also https://github.com/kubeflow/model-registry/pkgs/container/model-registry%2Fjob%2Fasync-upload
n/a
> k8s(async-upload): fix Job Manifest default image name

- clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersions/ModelVersionListView.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisteredModels/RegisteredModelsTableToolbar.tsx
The register buttons are now centered as shown in the screenshots
Go to the pages as shown above and observe the buttons being centered.
> fix: centered header buttons

- manifests/kustomize/base/kustomization.yaml
- manifests/kustomize/options/csi/kustomization.yaml
- manifests/kustomize/options/ui/base/kustomization.yaml
> chore: align manifest for 0.2.21

- clients/ui/frontend/package-lock.json
Upgraded the form-data package to resolve CVE
You can check via `npm audit`
> Fixing form-data package CVE (CRITICAL)

- .gitignore
- clients/python/.gitignore
This is a temporary file written to in some Makefiles when running clusters locally for testing.
> Add .port-forwards.pid to .gitignore

- clients/ui/frontend/src/__tests__/cypress/cypress/pages/modelRegistry.ts
- clients/ui/frontend/src/__tests__/cypress/cypress/pages/modelRegistryView/modelDetailsCard.ts
- clients/ui/frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelDetailsCard.cy.ts
- clients/ui/frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersionDetails.cy.ts
- clients/ui/frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelVersions.cy.ts
- clients/ui/frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/registeredModelArchive.cy.ts
- clients/ui/frontend/src/app/pages/modelRegistry/ModelRegistryRoutes.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersions/ModelDetailsCard.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersions/ModelDetailsView.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersions/ModelVersions.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersions/ModelVersionsTabs.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersions/const.ts
- clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisteredModels/RegisteredModelTableRow.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/components/ModelEditableLabelsDescriptionListGroup.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/components/ModelPropertiesExpandableSection.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/components/ModelPropertiesTableRow.tsx
JIRA: [RHOAIENG-28034](https://issues.redhat.com/browse/RHOAIENG-28034)
1. Change "View details" to "Overview" in the kebab action of a registered model
2. Click on the registered model will navigate to the "Overview" tab (This is the previous "Details" tab) instead of the "Versions" tab
3. Move the "Overview" tab to the first tab and refactor the page
a. Remove the description of this page
b. Add all the model details to a card
c. Add the properties to an expandable section which is default to collapsed
NOTE: The changes for the label styles and the description line truncate will be implemented in the `mod-arch-shared` package and bump the version after that.
Go to the model details page to check the updates.
- All the commits have been …
> Refactor details page for the registered model

- .github/labeler.yml
as $subject
reusing previous infra
> chore: add Area label for Jobs/async-upload

- .gitignore
- README.md
- catalog/README.md
* Add links to existing READMEs to make components more discoverable
* Add a README for the model catalog
This is just documentation updates
> Add links to existing READMEs and add README for the model catalog

- catalog/README.md
update link for Model Catalog Swagger UI to KF website
follow-up to https://github.com/kubeflow/website/pull/4169
n/a
> doc: update link for Model Catalog Swagger UI to KF website

- manifests/kustomize/options/catalog/README.md
- manifests/kustomize/options/catalog/sources.yaml
Updates to the model catalog source documentation to better explain which properties are supported.
> update catalog source docs

- clients/ui/bff/internal/mocks/model_registry_client_mock.go
- clients/ui/frontend/src/__tests__/cypress/cypress/pages/modelRegistry.ts
- clients/ui/frontend/src/__tests__/cypress/cypress/pages/modelRegistryView/registeredModelArchive.ts
- clients/ui/frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/modelRegistry.cy.ts
- clients/ui/frontend/src/__tests__/cypress/cypress/tests/mocked/modelRegistry/registeredModelArchive.cy.ts
- clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersions/ModelVersionListView.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersionsArchive/ModelVersionsArchiveListView.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisteredModels/RegisteredModelListView.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisteredModels/RegisteredModelTable.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisteredModels/RegisteredModelTableRow.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisteredModels/RegisteredModelsTableColumns.ts
- clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisteredModelsArchive/RegisteredModelsArchiveListView.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/RegisteredModelsArchive/RegisteredModelsArchiveTable.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/components/ModelLabels.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/utils.ts
This PR aims to add latest version column to registered model list, change the placeholder text for filter(Registered models list, archived model lists, versions list, archived version list and archived model version list), update the Kebab action to include Overview and Versions, updated the labels to outlined one.
1. Go to registered model list - see the Latest version column, by clicking on that will navigate to version details page
2. Make sure the modelName and versionName links are inline in registered model page
3. Make sure the placeholder text update for filter
4. Check the kebab action - we have Overview(Navigates to model details) and Versions(navigates to version list)
5.  updated the labels to outlined one.
6. same goes for archived registered models list as well.
- All the …
> Add latest version column to models list

- .github/workflows/test-fuzz.yml
* Provide simplified mechanism for executing `make test-fuzz` for specific pull requests
This CI can only be tested after merged to main.
> ci: Enable execution of make test-fuzz via pull request comment

- clients/ui/bff/README.md
- clients/ui/bff/cmd/helpers.go
- clients/ui/bff/cmd/main.go
- clients/ui/bff/internal/api/middleware.go
- clients/ui/bff/internal/config/environment.go
- clients/ui/bff/internal/integrations/mrserver/http.go
- clients/ui/bff/internal/integrations/mrserver/http_test.go
In Model Registy bff server, in the current edition, the http client is configured to use TLSverify set to false, this is working around the security, and not checking for certs. 
Configure the http client, to use the certs with tlsverify to true, for proper execution.
> Structure MR BFF server to use secure HTTP calls

- clients/ui/OWNERS
@mturley is providing extensive contributions to the UI efforts both in terms of code, architecture, and coordination with UI team
> chore: add mturley to module clients/ui

- .github/workflows/async-upload-test.yml
- .github/workflows/build-and-push-csi-image.yml
- .github/workflows/build-and-push-image.yml
- .github/workflows/build-image-pr.yml
- .github/workflows/build-image-ui-pr.yml
- .github/workflows/build.yml
- .github/workflows/check-db-schema-structs.yaml
- .github/workflows/check-openapi-spec-pr.yaml
- .github/workflows/controller-test.yml
- .github/workflows/csi-test.yml
- .github/workflows/fossa-license-scanning.yml
- .github/workflows/prepare.yml
- .github/workflows/python-tests.yml
- .github/workflows/ui-bff-build.yml
- .github/workflows/ui-frontend-build.yml
clamp down GHA workflow with a set of minimal `permissions:` block
we need to enact this on the repo
> ci: clamp GHA with base pemissions: block

- internal/converter/openapi_converter_util.go
This PR fixes a possible int overflow issue introduced in the MLMD removal PR
Run security checks locally
```shell
codeql database create go-db  --language=go --overwrite
codeql database analyze go-db --format=sarif-latest --output=report-go.sarif
```
> fix: possible int overflow

- .github/workflows/build-and-push-image.yml
followup previous PR
- #1458
for `build-and-push-image` default `permissions:` block
> ci: followup #1458 for build-and-push-image defaults

- jobs/async-upload/samples/sample_job_s3_to_oci.yaml
add securityContext to async-upload Job sample
we are currently experiencing degraded ci/GHA on the E2E for the async-upload job for which we're aware
> feat: add securityContext to async-upload Job sample

- clients/ui/api/openapi/mod-arch.yaml
- clients/ui/bff/internal/api/model_registry_settings_handler.go
- clients/ui/bff/internal/models/model_registry_kind.go
- clients/ui/frontend/src/app/api/k8s.ts
- clients/ui/frontend/src/app/hooks/useModelRegistryCR.ts
This PR aims to update the response format of `GetModelRegistrySettingsHandler` and add endpoints to certificates route to unblock the development of `ModelRegistryDatabasePasssword` component and certificates for MR with Edit functionality.
check that the response includes databasePassword in the response
`curl -i -H "kubeflow-userid: user@example.com" "localhost:4000/api/v1/settings/model_registry/test?namespace=kubeflow"`
check that the response includes either sslRootCertificateConfigMap or sslRootCertificateSecret or none in the response
`curl -i -H "kubeflow-userid: user@example.com" "localhost:4000/api/v1/settings/model_registry?namespace=kubeflow"`
- All the commits have been [_signed-off_](https://github.com/kubeflow/community/tree/master/dco-signoff-hook#signing-off-commits) …
> Update model registry response format

- clients/python/tests/conftest.py
- clients/python/tests/constants.py
- clients/python/tests/fuzz_api/conftest.py
- clients/python/tests/fuzz_api/model_catalog/test_catalog_stateless.py
- clients/python/tests/fuzz_api/model_registry/test_mr_stateful.py
- clients/python/tests/fuzz_api/model_registry/test_mr_stateless.py
- Add stateless tests for the model catalog API
- Reorganize api tests in their own folder and move fixture closer to where they are used
tested on https://github.com/kubeflow/model-registry/actions/runs/17124067577 
> Add fuzz tests for model catalog and refactor folder structure

- clients/ui/frontend/src/__tests__/cypress/cypress/pages/modelCatalog.ts
- clients/ui/frontend/src/__tests__/cypress/cypress/tests/mocked/modelCatalog/modelCatalogDetails.cy.ts
- clients/ui/frontend/src/app/AppRoutes.tsx
- clients/ui/frontend/src/app/pages/modelCatalog/ModelCatalogCoreLoader.tsx
- clients/ui/frontend/src/app/pages/modelCatalog/ModelCatalogRoutes.tsx
- clients/ui/frontend/src/app/pages/modelCatalog/components/ModelCatalogCard.tsx
- clients/ui/frontend/src/app/pages/modelCatalog/screens/ModelCatalogPage.tsx
- clients/ui/frontend/src/app/pages/modelCatalog/screens/ModelDetailsPage.tsx
- clients/ui/frontend/src/app/pages/modelCatalog/screens/ModelDetailsView.tsx
- Added Model Catalog Details Page for each model 
- Introduced a dedicated route module
- Implemented the details page and view
- Updated navigation to details
[UI] Screenshots: 
[
](url)
- Cypress E2E (mocked) added to cover details navigation and core header/content assertions
- Manual verification:
- Navigate to `/model-catalog`, click a model card/name, confirm breadcrumb, provider line, and description display correctly.
- All the commits have been [signed-off](https://github.com/kubeflow/community/tree/master/dco-signoff-hook#signing-off-commits)  (To pass the `DCO` check)
> Model Catalog Details Page

- internal/apiutils/api_utils.go
- internal/csi/storage/modelregistry_provider.go
- test/csi/e2e_test.sh
Improve CSI logging, to complement #1532 investigations.
extending ci/GHA integration testing to report log from CSI container so to display the new log statements, will update PR below
> feat(csi): improve CSI logging

- .github/workflows/build-and-push-async-upload.yml
typically we emit a 'latest' and 'main' tag
for each published image:
this PR adds missing tags for the jobs/async-upload image
same setup per other GHA workflows.
> ci: add 'latest' and 'main' tags to async-upload image

- .github/workflows/trivy-image-scanning.yaml
I missed this when I originally onboarded the workflow 😅 
Implemented directions from: https://github.com/github/codeql-action?tab=readme-ov-file#workflow-permissions
can't be tested with Act, so will use `workflow_dispatch` after merge to detect any regression
> ci: add permissions block to trivy-image-scaning workflow

- .github/workflows/build-and-push-async-upload.yml
need to refactor following up to https://github.com/kubeflow/model-registry/pull/1542 since the locally build tag need to be passed between steps, so using github action docker-push for also tagging latest and main
need to merge the PR to ensure cache is passed between steps
> ci: refactor tag latest,main push using action

- .github/workflows/trivy-image-scanning.yaml
given the recent updates to the GHA for the job/async-upload, we can expand the trivy scan to latest container image, per the other container images.
extension to existing GHA
> ci: add job/async-upload to trivy scan

- README.md
add OpenSSF ScoreCard link in README
I've checked the hyperlinks from my browser and they don't 404
> docs: add OpenSSF ScoreCard link in README

- clients/ui/api/openapi/mod-arch.yaml
- clients/ui/bff/internal/mocks/model_catalog_client_mock.go
- clients/ui/bff/internal/mocks/static_data_mock.go
- clients/ui/frontend/src/app/api/modelCatalog/service.ts
- clients/ui/frontend/src/app/context/modelCatalog/ModelCatalogContext.tsx
- clients/ui/frontend/src/app/hooks/modelCatalog/useCatalogModelsBySource.ts
- clients/ui/frontend/src/app/modelCatalogTypes.ts
- clients/ui/frontend/src/app/pages/modelCatalog/EmptyModelCatalogState.tsx
- clients/ui/frontend/src/app/pages/modelCatalog/ModelCatalogCoreLoader.tsx
- clients/ui/frontend/src/app/pages/modelCatalog/ModelCatalogRoutes.tsx
- clients/ui/frontend/src/app/pages/modelCatalog/screens/InvalidCatalogSource.tsx
- clients/ui/frontend/src/app/pages/modelCatalog/screens/ModelCatalog.tsx
- clients/ui/frontend/src/app/pages/modelCatalog/screens/ModelCatalogPage.tsx
- clients/ui/frontend/src/app/pages/modelCatalog/screens/ModelCatalogSourceSelector.tsx
- clients/ui/frontend/src/app/pages/modelCatalog/screens/ModelCatalogSourceSelectorNavigator.tsx
- clients/ui/frontend/src/app/pages/modelCatalog/screens/ModelDetailsPage.tsx
- clients/ui/frontend/src/app/pages/modelCatalog/utils/modelCatalogUtils.ts
- clients/ui/frontend/src/app/pages/modelRegistry/screens/components/ThemeAwareSearchInput.tsx
This PR aims to add catalog source filter and search bar to model catalog page.
https://github.com/user-attachments/assets/f2fcb88a-9075-4107-9307-6a22f73fc964
run the application with mock - `make dev-start`
> Add filter and search bar to model catalog

- internal/db/constants/states.go
- internal/db/filter/query_builder.go
- internal/db/models/artifact.go
- internal/db/models/serve_model.go
This PR aims to fix bugs found via the fuzz testing (https://github.com/kubeflow/model-registry/actions/runs/17735195861/job/50395108456) on posgresql
run locally requests on the affected endpoints with the `?filterQuery=state='LIVE'`
> fix: postgres bugs found with the fuzz testing

- clients/ui/frontend/src/app/pages/modelCatalog/screens/ModelCatalogPage.tsx
- clients/ui/frontend/src/app/pages/modelCatalog/screens/ModelCatalogSourceSelector.tsx
This is the followup PR to https://github.com/kubeflow/model-registry/pull/1620 - fixing typo
make dev-start
> Fix typo in FE

- clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetails.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsTabs.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersionDetails/ModelVersionDetailsView.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersions/ModelDetailsView.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersions/ModelVersionsCard.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersionsArchive/ArchiveModelVersionDetails.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/ModelVersionsArchive/ModelVersionArchiveDetails.tsx
- clients/ui/frontend/src/app/pages/modelRegistry/screens/components/ModelPropertiesExpandableSection.tsx
This PR aims to fix the MR properties table and artifacts and registered model fetch. 
Also removed the description from the version details page and handled loading and error state for version cards in model details page
https://github.com/user-attachments/assets/6f5dc275-6055-4dc7-85be-ef655ef7c7c4
https://github.com/user-attachments/assets/5ac38257-18d3-4cfe-9c96-e0a3909d762f
https://github.com/user-attachments/assets/3e893b39-9cca-4f00-a72b-787ac3e695df
1. Go to Model details page and add new property -  make sure the properties table works fine when there are no properties and present and also when properties present
2. in version details page - 
- check the properties table in model card
- check the properties table in version card
3.  Make sure that the version details page has no …
> Fix MR properties table reload issue

- .gitignore
- catalog/internal/catalog/testdata/test-yaml-catalog.yaml
Add metadataType field to customProperties in test-yaml-catalog.yaml to ensure proper metadata type specification for test data.
**before PR code:**
run `make compose/local/up/postgres`
Point browser at and see error in logs:
http://localhost:8081/api/model_catalog/v1alpha1/sources/catalog1/models/rhelai1/granite-8b-code-instruct/artifacts
```
[model-catalog]  | E0919 01:23:55.737619       1 routers.go:84] error encoding JSON response: json: error calling MarshalJSON for type *openapi.CatalogModelArtifactList: json: error calling MarshalJSON for type openapi.CatalogModelArtifact: json: error calling MarshalJSON for type openapi.MetadataValue: unexpected end of JSON input
[model-catalog]  | 2025/09/19 01:23:55 "GET http://localhost:8081/api/model_catalog/v1alpha1/sources/catalog1/models/rhe …
```
> fix(catalog): add missing metadataType values in test catalog YAML

- clients/ui/bff/Makefile
make dev-start cmd was throwing error.
```
...deployment-mode=standalone --log-level=info --allowed-origins="" --insecure-skip-verify=
invalid boolean value "" for -insecure-skip-verify: parse error
```
run `make dev-start` - it should work just fine.
> Fix make file

- clients/ui/frontend/package-lock.json
Upgraded the axios version due to the CVE present in the current version.
Run `npm run build` in the directory
> upgraded axios version

- clients/ui/frontend/src/app/modelCatalogTypes.ts
Refactored TypeScript types in `clients/ui/frontend/src/app/modelCatalogTypes.ts`:
1. **Split `CatalogFilterOption`** into specific types:
- `CatalogFilterNumberOption` (with required range min/max)
- `CatalogFilterStringOption` (with required values array)
2. **Restructured `CatalogFilterOptionsList`** to use fixed keys:
- `task`, `provider`, `license`, `language` - all as string filter options
3. **Fixed property naming** from `Values` to `values`
This will unblock part of @rsun19 's ongoing work. We will need to enhance this type with additional keys for the performance filters as we prepare for them.
N/A, these types are only consumed by `useCatalogFilterOptionList` which is currently not called anywhere yet.
- All the commits have been …
> Use fixed keys for CatalogFilterOptionsList type

- clients/python/pyproject.toml
- clients/python/src/model_registry/__init__.py
per release process https://github.com/kubeflow/model-registry/pull/871
n/a
> chore: bump MR py client version to 0.3.2

- manifests/kustomize/options/catalog/base/kustomization.yaml
```shell
k describe pod model-catalog-postgres-0 | grep Failed
Warning  Failed            10s (x3 over 23s)  kubelet            Error: secret "model-catalog-postgres" not found
```
Prerequisites:
- a local kind cluster or a cluster in general
from project's root folder 
`kubectl apply -k ./manifests/kustomize/options/catalog/base`
> fix: catalog postgres secret name
